### PR TITLE
Output hierarchically-correct TF tree

### PR DESCRIPTION
**Pull request by gbiggs**
Currently the TF tree output by `drake_ros_tf2` is flat. Every frame is rooted in the world frame. This is because it only uses the Drake scene graph for getting the frames, which does not have any information on the hierarchy of the frames.

This PR changes `drake_ros_tf2` to output a correct TF frames hierarchy. It does this by pre-computing the hierarchy of frames in any MultibodyPlants that are registered to the Drake-ROS TF2 broadcaster. The hierarchy information can then be used during TF2 tree message creation to ensure any frames that originate in a MultibodyPlant are in the correct hierarchy. Any additional frames in the scene graph that are not in the MultibodyPlant(s) (which there may be) are still rooted in the world frame.

Before this PR, the TF tree looks like this:

After the PR, it looks like this:

For context, that is this system:

Although a flat TF tree is not technically a problem from the perspective of processing transforms, it makes it harder to debug complex TF trees. As an example, the TF tree for the [multirobot PR](#85) looks like this without this PR:

After applying this PR, the TF tree is much more visually understandable.

Context on the above system:

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/91)

### CODE REVIEW

**Review by IanTheEngineer — COMMENTED** [review]
+@calderpg-tri and +@iantheengineer for review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/91#-:-N55WFZ-8KfmzAd5ixwQ:by0w5qt)* status: 0 of 16 files reviewed, all discussions resolved (waiting on @calderpg-tri, @gbiggs, and @IanTheEngineer)

**Review by sloretz — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/91)* status: all files reviewed, 8 unresolved discussions (waiting on @calderpg-tri, @gbiggs, and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/91#-N6Q4l-W0HfcZ1UfMvFo:-N6Q4l-XCP6GOaaGH3VP:brqjlz3) (no related file):*
Looks like one of the tests needs `get_graph_query_port` -> `get_graph_query_input_port`

```
   6: E       AttributeError: 'drake_ros_viz.RvizVisualizer' object has no attribute 'get_graph_query_port'
  6: 
  6: ../../src/cj62zbfayhs/drake-ros/drake_ros_viz/test/test_python_bindings.py:133: AttributeError
```

___
___
*[`drake_ros_tf2/include/drake_ros_tf2/scene_tf_broadcaster_system.hpp` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/91#-N6Ow2mZ9YwQhBxL7wMx:-N6Ow2mZ9YwQhBxL7wMy:b-rv1j9r) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cb853a43d4f54e45db0382f63bbe287212fdad75/drake_ros_tf2/include/drake_ros_tf2/scene_tf_broadcaster_system.hpp#L1)):*
> ```cpp
> // Copyright 2021 Open Source Robotics Foundation, Inc.
> ```

Accidentally committed this file? It seems to be an older version of `scene_tf_broadcaster_system.h`.
___
*[`drake_ros_tf2/src/scene_tf_system.cc` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/91#-N6Q-LxU7kOpQu3lmyMQ:-N6Q-LxU7kOpQu3lmyMR:bdiit5s) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cb853a43d4f54e45db0382f63bbe287212fdad75/drake_ros_tf2/src/scene_tf_system.cc#L41)):*
> ```cpp
>     drake::multibody::BodyIndex body_index;
>     std::string name;
>     geometry_msgs::msg::TransformStamped transform;
> ```

I'm still learning [Drake's monogram notation](https://drake.mit.edu/doxygen_cxx/group__multibody__spatial__pose.html), but this variable name seems like a good place to use it. IIUC given parent frame P and child frame C, this variable holds the pose of C with respect to P in frame P, so it should be named `X_PC`.
___
*[`drake_ros_tf2/src/scene_tf_system.cc` line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/91#-N6Oyl5_24aeE-nyO3hS:-N6Oyl5_24aeE-nyO3hT:b-is7zn5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cb853a43d4f54e45db0382f63bbe287212fdad75/drake_ros_tf2/src/scene_tf_system.cc#L44)):*
> ```cpp
>   };
>   using ParentFrameMap = std::unordered_map<drake::geometry::FrameId, Frame>;
>   ParentFrameMap parent_frames_map;
> ```

nit, Looking at just this and the `Frame` type its not clear to me whether the key or the value is the parent. I can see the key is the child and the value is the parent in how it's used, but I'd recommend adding something here to make it clearer. Maybe add a comment above `parent_frames_map` saying which is which?
___
*[`drake_ros_tf2/src/scene_tf_system.cc` line 143 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/91#-N6Q0YkG9htJF2H99TA5:-N6Q0YkG9htJF2H99TA6:b97cmb6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cb853a43d4f54e45db0382f63bbe287212fdad75/drake_ros_tf2/src/scene_tf_system.cc#L143)):*
> ```cpp
>         parent_frame.transform.header.stamp =
>           rclcpp::Time() + rclcpp::Duration::from_seconds(context.get_time());
>         auto parent_transform = query_object.GetPoseInParent(parent_frame.id);
> ```

It seems like `GetPoseInParent` is returning the pose of the parent frame P with respect to the world. If so, I'd recommend naming this variable `X_WP` instead of `parent_transform`.
___
*[`drake_ros_tf2/src/scene_tf_system.cc` line 144 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/91#-N6Q0rr_4iwQr6irXxqR:-N6Q0rr_4iwQr6irXxqS:b-i9fpkc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cb853a43d4f54e45db0382f63bbe287212fdad75/drake_ros_tf2/src/scene_tf_system.cc#L144)):*
> ```cpp
>           rclcpp::Time() + rclcpp::Duration::from_seconds(context.get_time());
>         auto parent_transform = query_object.GetPoseInParent(parent_frame.id);
>         auto child_transform = query_object.GetPoseInParent(frame_id);
> ```

It seems like `GetPoseInParent` is returning the pose of the child frame C with respect to the world. If so, I'd recommend naming this variable `X_WC` instead of `child_transform`.
___
*[`drake_ros_tf2/src/scene_tf_system.cc` line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/91#-N6Q11tD5f7MRM7s1qMu:-N6Q11tD5f7MRM7s1qMv:b-n1r5m2) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cb853a43d4f54e45db0382f63bbe287212fdad75/drake_ros_tf2/src/scene_tf_system.cc#L146)):*
> ```cpp
>         auto child_transform = query_object.GetPoseInParent(frame_id);
>         parent_frame.transform.transform =
>             ToTransformMsg(parent_transform.inverse() * child_transform);
> ```

`X_WP.inverse() * X_WC` == `X_PW * X_WC` == `X_PC`, which looks correct so I think the comments above suggesting Drake's notation are also correct.
___
*[`drake_ros_viz/src/rviz_visualizer.cc` line 81 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/91#-N6Q5ffq06OvOOBCF8wq:-N6Q5ffq06OvOOBCF8wr:bks68cb) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cb853a43d4f54e45db0382f63bbe287212fdad75/drake_ros_viz/src/rviz_visualizer.cc#L81)):*
> ```cpp
>     builder.ConnectInput("graph_query",
>                          impl_->scene_tf_broadcaster->get_graph_query_input_port());
>     impl_->scene_tf_broadcaster->ComputeFrameHierarchy();
> ```

It seems like this might be a `noop` since no `MultibodyPlant`s have been registered with the `RVizVisualizer` yet. If so, I think this line should be removed.

**Review by gbiggs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/91)* status: 13 of 17 files reviewed, 7 unresolved discussions (waiting on @calderpg-tri, @gbiggs, @IanTheEngineer, and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/91#-N6Q4l-W0HfcZ1UfMvFo:-N9i12KE1FBiJUxIvi_4:bkgq5uf) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Looks like one of the tests needs `get_graph_query_port` -> `get_graph_query_input_port`

```
   6: E       AttributeError: 'drake_ros_viz.RvizVisualizer' object has no attribute 'get_graph_query_port'
  6: 
  6: ../../src/cj62zbfayhs/drake-ros/drake_ros_viz/test/test_python_bindings.py:133: AttributeError
```
</blockquote></details>

Fixed in cc23f84.

___
___
*[`drake_ros_tf2/include/drake_ros_tf2/scene_tf_broadcaster_system.hpp` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/91#-N6Ow2mZ9YwQhBxL7wMx:-N9i2d7A9oRiceqAcqA7:be8x8e7) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cb853a43d4f54e45db0382f63bbe287212fdad75/drake_ros_tf2/include/drake_ros_tf2/scene_tf_broadcaster_system.hpp#L1)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Accidentally committed this file? It seems to be an older version of `scene_tf_broadcaster_system.h`.
</blockquote></details>

Removed in ae465b8.
___
*[`drake_ros_tf2/src/scene_tf_system.cc` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/91#-N6Q-LxU7kOpQu3lmyMQ:-N9i4hTl9O1Ut0u-fGX1:bg3llxb) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cb853a43d4f54e45db0382f63bbe287212fdad75/drake_ros_tf2/src/scene_tf_system.cc#L41)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I'm still learning [Drake's monogram notation](https://drake.mit.edu/doxygen_cxx/group__multibody__spatial__pose.html), but this variable name seems like a good place to use it. IIUC given parent frame P and child frame C, this variable holds the pose of C with respect to P in frame P, so it should be named `X_PC`.
</blockquote></details>

Good idea. Changed in 2d72e76.
___
*[`drake_ros_tf2/src/scene_tf_system.cc` line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/91#-N6Oyl5_24aeE-nyO3hS:-N9i4jzdBNeG90b3neef:bxoqsrf) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cb853a43d4f54e45db0382f63bbe287212fdad75/drake_ros_tf2/src/scene_tf_system.cc#L44)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

nit, Looking at just this and the `Frame` type its not clear to me whether the key or the value is the parent. I can see the key is the child and the value is the parent in how it's used, but I'd recommend adding something here to make it clearer. Maybe add a comment above `parent_frames_map` saying which is which?
</blockquote></details>

I added a comment in 3f376a4.
___
*[`drake_ros_tf2/src/scene_tf_system.cc` line 143 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/91#-N6Q0YkG9htJF2H99TA5:-N9iiPz84g8ip9UlAJ_Z:br0j40y) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cb853a43d4f54e45db0382f63bbe287212fdad75/drake_ros_tf2/src/scene_tf_system.cc#L143)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

It seems like `GetPoseInParent` is returning the pose of the parent frame P with respect to the world. If so, I'd recommend naming this variable `X_WP` instead of `parent_transform`.
</blockquote></details>

Done in 2d2d695.
___
*[`drake_ros_tf2/src/scene_tf_system.cc` line 144 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/91#-N6Q0rr_4iwQr6irXxqR:-N9iiQys83LdwYYbv4cE:br0j40y) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cb853a43d4f54e45db0382f63bbe287212fdad75/drake_ros_tf2/src/scene_tf_system.cc#L144)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

It seems like `GetPoseInParent` is returning the pose of the child frame C with respect to the world. If so, I'd recommend naming this variable `X_WC` instead of `child_transform`.
</blockquote></details>

Done in 2d2d695.
___
*[`drake_ros_tf2/src/scene_tf_system.cc` line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/91#-N6Q11tD5f7MRM7s1qMu:-N9iiS5Y8b4lTXIy-CjC:br0j40y) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cb853a43d4f54e45db0382f63bbe287212fdad75/drake_ros_tf2/src/scene_tf_system.cc#L146)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

`X_WP.inverse() * X_WC` == `X_PW * X_WC` == `X_PC`, which looks correct so I think the comments above suggesting Drake's notation are also correct.
</blockquote></details>

Done in 2d2d695.
___
*[`drake_ros_viz/src/rviz_visualizer.cc` line 81 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/91#-N6Q5ffq06OvOOBCF8wq:-N9j7I9X13V3evdGodZP:blruo79) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cb853a43d4f54e45db0382f63bbe287212fdad75/drake_ros_viz/src/rviz_visualizer.cc#L81)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

It seems like this might be a `noop` since no `MultibodyPlant`s have been registered with the `RVizVisualizer` yet. If so, I think this line should be removed.
</blockquote></details>

I checked and you're right, it's unnecessary. Removed in 2c80c68.

**Review by sloretz — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/91)* status: all files reviewed, 1 unresolved discussion (waiting on @calderpg-tri, @gbiggs, and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/91#-NBJ2Tl88P05uZDV1fV9:-NBJ2Tl88P05uZDV1fVA:b7hcpi5) (no related file):*
The  changes LGTM when CI is green! Humble and Galactic CI report are a few test failures.

```
   1: -- run_test.py: verify result file '/__w/drake-ros/drake-ros/ros_ws/build/drake_ros_tf2/test_results/drake_ros_tf2/clang_format.xunit.xml'
  1/7 Test #1: clang_format .....................***Failed    0.31 sec
```


```
   5:         builder.Connect(
  5:             scene_graph.get_query_output_port(),
  5: >           scene_tf_broadcaster.get_graph_query_port())
  5: E       AttributeError: 'drake_ros_tf2.SceneTfBroadcasterSystem' object has no attribute 'get_graph_query_port'
  5: 
  5: ../../src/sagp552c0oc/drake-ros/drake_ros_tf2/test/test_tf_broadcaster.py:84: AttributeError
  5: - generated xml file: /__w/drake-ros/drake-ros/ros_ws/build/drake_ros_tf2/test_results/drake_ros_tf2/test_tf_broadcaster_py.xunit.xml -
  5: =========================== short test summary info ============================
  5: FAILED ../../src/sagp552c0oc/drake-ros/drake_ros_tf2/test/test_tf_broadcaster.py::test_nominal_case
```


```
   1: -- run_test.py: verify result file '/__w/drake-ros/drake-ros/ros_ws/build/drake_ros_viz/test_results/drake_ros_viz/clang_format.xunit.xml'
  1/6 Test #1: clang_format .....................***Failed    0.35 sec
```

___

**Review by gbiggs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/91)* status: 12 of 18 files reviewed, 1 unresolved discussion (waiting on @calderpg-tri, @gbiggs, @IanTheEngineer, and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/91#-NBJ2Tl88P05uZDV1fV9:-NCYyuLF64KFPKt_apXD:b-7j52si) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

The  changes LGTM when CI is green! Humble and Galactic CI report are a few test failures.

```
   1: -- run_test.py: verify result file '/__w/drake-ros/drake-ros/ros_ws/build/drake_ros_tf2/test_results/drake_ros_tf2/clang_format.xunit.xml'
  1/7 Test #1: clang_format .....................***Failed    0.31 sec
```


```
   5:         builder.Connect(
  5:             scene_graph.get_query_output_port(),
  5: >           scene_tf_broadcaster.get_graph_query_port())
  5: E       AttributeError: 'drake_ros_tf2.SceneTfBroadcasterSystem' object has no attribute 'get_graph_query_port'
  5: 
  5: ../../src/sagp552c0oc/drake-ros/drake_ros_tf2/test/test_tf_broadcaster.py:84: AttributeError
  5: - generated xml file: /__w/drake-ros/drake-ros/ros_ws/build/drake_ros_tf2/test_results/drake_ros_tf2/test_tf_broadcaster_py.xunit.xml -
  5: =========================== short test summary info ============================
  5: FAILED ../../src/sagp552c0oc/drake-ros/drake_ros_tf2/test/test_tf_broadcaster.py::test_nominal_case
```


```
   1: -- run_test.py: verify result file '/__w/drake-ros/drake-ros/ros_ws/build/drake_ros_viz/test_results/drake_ros_viz/clang_format.xunit.xml'
  1/6 Test #1: clang_format .....................***Failed    0.35 sec
```
</blockquote></details>

I fixed the broken test and the formatting errors (after much fighting with clang). Let's see how CI does this time!

___

**Review by sloretz — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/91)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @calderpg-tri and @IanTheEngineer)

**Pull request merged**
