### PR TITLE
Fastcdr CI cleanup, ros rolling API changes

### PR DESCRIPTION
**Pull request by adityapande-1995**
This is a temp PR meant to clean up CI. Resolves https://github.com/RobotLocomotion/drake-ros/issues/274

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/275)

### CODE REVIEW

**Review by sloretz — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/275)* status: all files reviewed, 1 unresolved discussion (waiting on @adityapande-1995)

___
*[`drake_ros/CMakeLists.txt` line 13 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/275#-NTPSl1cE8X8uBtqWXOG:-NTPSl1cE8X8uBtqWXOH:bom8xr4) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/46f44a00eb010f4f52467017b96ef015ce392d13/drake_ros/CMakeLists.txt#L13)):*
> ```CMake
> endif()
> 
> find_package(builtin_interfaces REQUIRED)
> ```

Do I understand correctly the workaround is to `find_package(builtin_interfaces)` so that it `find_package(fastcdr)` for us? How about we skip a step and `find_package(fastcdr)` instead?

**Review by adityapande-1995 — COMMENTED** [review]
Currently, the ``SubscriptionBase`` PI is different in rolling debs and archives, with the debs lagging behind. ``rclcpp`` just had a release, so this should be available via debs soon.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/275#-:-NTR7-KC7psh4mm9ODJ4:bzh2upl)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sloretz)

___
*[`drake_ros/CMakeLists.txt` line 13 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/275#-NTPSl1cE8X8uBtqWXOG:-NTR6kHj7DMFjzfJ6CNI:bph0j10) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/46f44a00eb010f4f52467017b96ef015ce392d13/drake_ros/CMakeLists.txt#L13)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Do I understand correctly the workaround is to `find_package(builtin_interfaces)` so that it `find_package(fastcdr)` for us? How about we skip a step and `find_package(fastcdr)` instead?
</blockquote></details>

Yup, even I thought so, but ``find_package(fastcdr)`` actually fails CI, saying it can't find the cmake config file.

**Comment by adityapande-1995** [comment]
Green CI !

**Review by sloretz — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/275)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Pull request merged**
