### PR TITLE
Bazelize drake_ros_tf2

### PR DESCRIPTION
**Pull request by sloretz**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/200)

### CODE REVIEW

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/200)* status: 0 of 4 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/200#-NIKCSqf9LshNzH-yYD8:-NIKCSqf9LshNzH-yYD9:bhdkiyt) (no related file):*


Current issue:


`test_tf_broadcaster_py` can't import from `drake_ros_core`.

```
Traceback (most recent call last):
  File "/home/osrf/.cache/bazel/_bazel_osrf/5c02e3f1f40a737d073de695c12319b8/sandbox/linux-sandbox/1/execroot/drake_ros_tf2/bazel-out/k8-fastbuild/bin/test_tf_broadcaster_py.runfiles/drake_ros_tf2/test/test_tf_broadcaster.py", line 19, in <module>
    from drake_ros_core import RosInterfaceSystem
ImportError: cannot import name 'RosInterfaceSystem' from 'drake_ros_core' (/home/osrf/.cache/bazel/_bazel_osrf/5c02e3f1f40a737d073de695c12319b8/sandbox/linux-sandbox/1/execroot/drake_ros_tf2/bazel-out/k8-fastbuild/bin/test_tf_broadcaster_py.runfiles/drake_ros_core/__init__.py)
```

I think the issue is the runfiles create a folder called `drake_ros_core` with an empty `__init__.py`, then create a `src/drake_ros_core/` folder which has the real `__init__.py`. I'm trying to see how I can [trick or modify pybind_py_library](https://github.com/RobotLocomotion/drake/blob/master/tools/skylark/pybind.bzl) to create the correct structure.

```console
$ tree /home/osrf/.cache/bazel/_bazel_osrf/5c02e3f1f40a737d073de695c12319b8/sandbox/linux-sandbox/1/execroot/drake_ros_tf2/bazel-out/k8-fastbuild/bin/test_tf_broadcaster_py.runfiles/drake_ros_core/
/home/osrf/.cache/bazel/_bazel_osrf/5c02e3f1f40a737d073de695c12319b8/sandbox/linux-sandbox/1/execroot/drake_ros_tf2/bazel-out/k8-fastbuild/bin/test_tf_broadcaster_py.runfiles/drake_ros_core/
├── _drake_ros_core.cpython-38-x86_64-linux-gnu.so -> /home/osrf/.cache/bazel/_bazel_osrf/5c02e3f1f40a737d073de695c12319b8/execroot/drake_ros_tf2/bazel-out/k8-fastbuild/bin/external/drake_ros_core/_drake_ros_core.cpython-38-x86_64-linux-gnu.so
├── __init__.py
├── __pycache__
│   └── __init__.cpython-38.pyc
└── src
    ├── drake_ros_core
    │   └── __init__.py -> /home/osrf/.cache/bazel/_bazel_osrf/5c02e3f1f40a737d073de695c12319b8/execroot/drake_ros_tf2/external/drake_ros_core/src/drake_ros_core/__init__.py
    └── __init__.py
```

___

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/200)* status: 0 of 4 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/200#-NIKCSqf9LshNzH-yYD8:-NIY47gVEP-tlk3MZ3uj:bantn0g) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>



Current issue:


`test_tf_broadcaster_py` can't import from `drake_ros_core`.

```
Traceback (most recent call last):
  File "/home/osrf/.cache/bazel/_bazel_osrf/5c02e3f1f40a737d073de695c12319b8/sandbox/linux-sandbox/1/execroot/drake_ros_tf2/bazel-out/k8-fastbuild/bin/test_tf_broadcaster_py.runfiles/drake_ros_tf2/test/test_tf_broadcaster.py", line 19, in <module>
    from drake_ros_core import RosInterfaceSystem
ImportError: cannot import name 'RosInterfaceSystem' from 'drake_ros_core' (/home/osrf/.cache/bazel/_bazel_osrf/5c02e3f1f40a737d073de695c12319b8/sandbox/linux-sandbox/1/execroot/drake_ros_tf2/bazel-out/k8-fastbuild/bin/test_tf_broadcaster_py.runfiles/drake_ros_core/__init__.py)
```

I think the issue is the runfiles create a folder called `drake_ros_core` with an empty `__init__.py`, then create a `src/drake_ros_core/` folder which has the real `__init__.py`. I'm trying to see how I can [trick or modify pybind_py_library](https://github.com/RobotLocomotion/drake/blob/master/tools/skylark/pybind.bzl) to create the correct structure.

```console
$ tree /home/osrf/.cache/bazel/_bazel_osrf/5c02e3f1f40a737d073de695c12319b8/sandbox/linux-sandbox/1/execroot/drake_ros_tf2/bazel-out/k8-fastbuild/bin/test_tf_broadcaster_py.runfiles/drake_ros_core/
/home/osrf/.cache/bazel/_bazel_osrf/5c02e3f1f40a737d073de695c12319b8/sandbox/linux-sandbox/1/execroot/drake_ros_tf2/bazel-out/k8-fastbuild/bin/test_tf_broadcaster_py.runfiles/drake_ros_core/
├── _drake_ros_core.cpython-38-x86_64-linux-gnu.so -> /home/osrf/.cache/bazel/_bazel_osrf/5c02e3f1f40a737d073de695c12319b8/execroot/drake_ros_tf2/bazel-out/k8-fastbuild/bin/external/drake_ros_core/_drake_ros_core.cpython-38-x86_64-linux-gnu.so
├── __init__.py
├── __pycache__
│   └── __init__.cpython-38.pyc
└── src
    ├── drake_ros_core
    │   └── __init__.py -> /home/osrf/.cache/bazel/_bazel_osrf/5c02e3f1f40a737d073de695c12319b8/execroot/drake_ros_tf2/external/drake_ros_core/src/drake_ros_core/__init__.py
    └── __init__.py
```
</blockquote></details>

Working: Will provide pointers on the oddities of Bazel's externals, shared libs and relative RPATH's, etc.

___

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/200)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/200#-NIKCSqf9LshNzH-yYD8:-NI_CSKmE7WTnTulCcTH:bnepwmu) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Will provide pointers on the oddities of Bazel's externals, shared libs and relative RPATH's, etc.
</blockquote></details>

I ended up tracing this issue to https://github.com/bazelbuild/bazel/issues/7386. Using `legacy_create_init = False` in the test resolves the issue.

___

**Comment by EricCousineau-TRI** [comment]
Nice! I was going to say maybe https://github.com/RobotLocomotion/drake/pull/8811 is related, but if this fixes it, then awesome!
(It could be the workaround is no longer relevant)

**Comment by EricCousineau-TRI** [comment]
Er, sorry - must have fat-fingered the closing!

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
First pass done, PTAL!

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/200#-:-NIbHAbkCZY3gslNHPLX:b-v6scke)* status: all files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/200#-NIKCSqf9LshNzH-yYD8:-NIbGrMu92spn9JXommz:bzftu3a) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I ended up tracing this issue to https://github.com/bazelbuild/bazel/issues/7386. Using `legacy_create_init = False` in the test resolves the issue.
</blockquote></details>

Sweet!

___
___
*[`drake_ros_tf2/BUILD.bazel` line 79 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/200#-NIbGV7lAUGwsvRcWeHW:-NIbGV7lAUGwsvRcWeHX:b-c3ckzk) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c2b642dc0798508dd332063ee4ab5a20e29ad359/drake_ros_tf2/BUILD.bazel#L79)):*
> ```Starlark
>     name = "drake_ros_tf2_py",
>     cc_deps = [
>         ":drake_ros_tf2",
> ```

This will (or at least should) cause an ODR issue between static Drake cc deps and the shared library Drake cc deps (that may come in through py deps).
Specifically, it should come in when using global counters (e.g. geometry ids, etc.).

For an example of this see what I linked to in https://github.com/RobotLocomotion/drake-ros/issues/151

Possible options to move forward:
- Huge TODO saying this is probably wrong.
- Fixing it here and now.
___
*[`drake_ros_tf2/WORKSPACE` line 39 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/200#-NIbG9CH-mF9pWg7ImsF:-NIbG9CH-mF9pWg7ImsG:b556c2m) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c2b642dc0798508dd332063ee4ab5a20e29ad359/drake_ros_tf2/WORKSPACE#L39)):*
> ```Starlark
> 
> # Depend on Drake
> DRAKE_TAG = "v1.10.0"
> ```

Working: Synchronizing this (and other components in this WORKSPACE) among separate repositories will quickly get away from us.
Filing issue...

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/200)* status: all files reviewed, 1 unresolved discussion (waiting on @sloretz)

___
*[`drake_ros_tf2/WORKSPACE` line 39 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/200#-NIbG9CH-mF9pWg7ImsF:-NIbHpVU1QJfLGmttiD6:b-6lid5f) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c2b642dc0798508dd332063ee4ab5a20e29ad359/drake_ros_tf2/WORKSPACE#L39)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Synchronizing this (and other components in this WORKSPACE) among separate repositories will quickly get away from us.
Filing issue...
</blockquote></details>

Done. Filed #201.

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/200)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`drake_ros_tf2/BUILD.bazel` line 79 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/200#-NIbGV7lAUGwsvRcWeHW:-NIcvfHC0aqzmGm0dlq0:b-tdr540) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c2b642dc0798508dd332063ee4ab5a20e29ad359/drake_ros_tf2/BUILD.bazel#L79)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This will (or at least should) cause an ODR issue between static Drake cc deps and the shared library Drake cc deps (that may come in through py deps).
Specifically, it should come in when using global counters (e.g. geometry ids, etc.).

For an example of this see what I linked to in https://github.com/RobotLocomotion/drake-ros/issues/151

Possible options to move forward:
- Huge TODO saying this is probably wrong.
- Fixing it here and now.
</blockquote></details>

ah, meaning using `:drake_ros_tf2` is equivalent to linking statically? That is if I made two pybind libraries `foo_pybind` and `bar_pybind`, and both depended on `:drake_ros_tf2`, followed by a pure python library `baz_py` then ODR would be violated? Is the solution to create a shared library target that depends on `:drake_ros_tf2`?

```
                                                                ┌─────────────┐
                                                                │drake_ros_tf2│
                                                                └──┬──────────┘
                                                                   │
                                                                   │:drake_ros_tf2
                                                                   │
              ┌─────────────┐                            ┌─────────▼──────────────┐
              │drake_ros_tf2│                            │drake_ros_tf2_shared_lib│
              └─┬───────┬───┘                            └───────┬───────┬────────┘
                │       │                                        │       │
                │       │                                        │       │
       ┌────────┘       └──────────┐                    ┌────────┘       └──────────┐
       │     :drake_ros_tf2        │                    │ :drake_ros_tf2_shared_lib │
       │                           │                    │                           │
       │                           │                    │                           │
┌──────▼───┐                 ┌─────▼────┐        ┌──────▼───┐                 ┌─────▼────┐
│foo_pybind│                 │bar_pybind│        │foo_pybind│                 │bar_pybind│
└─────┬────┘                 └─────┬────┘        └─────┬────┘                 └─────┬────┘
      │                            │                   │                            │
      │                            │                   │                            │
      │:foo_pybind                 │:bar_pybind        │:foo_pybind                 │:bar_pybind
      │                            │                   │                            │
      │                            │                   │                            │
      └───────────┐      ┌─────────┘                   └───────────┐      ┌─────────┘
                  │      │                                         │      │
                  │      │  [violates ODR]                         │      │    [OK because definitions
                 ┌▼──────▼┐                                       ┌▼──────▼┐    in one shared lib]
                 │ baz_py │                                       │ baz_py │
                 └────────┘                                       └────────┘
```

Or is it more complicated than that? I see the example shared library [depends on Drake's shared library](https://github.com/EricCousineau-TRI/repro/blob/1bc74a62fbaaff8e773b222e8a735d928386bc9d/drake_stuff/drake_downstream_pybind/common/BUILD.bazel#L43). Do we need to use shared libraries all the way back up the dependency tree so that ODR won't be violated by depending any transitive dependency twice?

**Comment by EricCousineau-TRI** [comment]
That being said, I think we can move forward on this PR, just with a big TODO that says "this works here, but may break in real usage" ?

**Review by sloretz — COMMENTED** [review]
Added TODO in https://github.com/RobotLocomotion/drake-ros/pull/200/commits/1f838a9261449728bba29f9d0fcb434b7739eeb7

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/200#-:-NIdp0LM3pM5yVx0Fbaw:b-r0llzg)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm_strong:, thanks!

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/200#-:-NIg3Uod8-gym13f_vDv:b5zo9cn)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

___
*[`drake_ros_tf2/BUILD.bazel` line 79 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/200#-NIbGV7lAUGwsvRcWeHW:-NIg3LFMBD7lh8CUFjiJ:b-3jkzpu) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c2b642dc0798508dd332063ee4ab5a20e29ad359/drake_ros_tf2/BUILD.bazel#L79)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

ah, meaning using `:drake_ros_tf2` is equivalent to linking statically? That is if I made two pybind libraries `foo_pybind` and `bar_pybind`, and both depended on `:drake_ros_tf2`, followed by a pure python library `baz_py` then ODR would be violated? Is the solution to create a shared library target that depends on `:drake_ros_tf2`?

```
                                                                ┌─────────────┐
                                                                │drake_ros_tf2│
                                                                └──┬──────────┘
                                                                   │
                                                                   │:drake_ros_tf2
                                                                   │
              ┌─────────────┐                            ┌─────────▼──────────────┐
              │drake_ros_tf2│                            │drake_ros_tf2_shared_lib│
              └─┬───────┬───┘                            └───────┬───────┬────────┘
                │       │                                        │       │
                │       │                                        │       │
       ┌────────┘       └──────────┐                    ┌────────┘       └──────────┐
       │     :drake_ros_tf2        │                    │ :drake_ros_tf2_shared_lib │
       │                           │                    │                           │
       │                           │                    │                           │
┌──────▼───┐                 ┌─────▼────┐        ┌──────▼───┐                 ┌─────▼────┐
│foo_pybind│                 │bar_pybind│        │foo_pybind│                 │bar_pybind│
└─────┬────┘                 └─────┬────┘        └─────┬────┘                 └─────┬────┘
      │                            │                   │                            │
      │                            │                   │                            │
      │:foo_pybind                 │:bar_pybind        │:foo_pybind                 │:bar_pybind
      │                            │                   │                            │
      │                            │                   │                            │
      └───────────┐      ┌─────────┘                   └───────────┐      ┌─────────┘
                  │      │                                         │      │
                  │      │  [violates ODR]                         │      │    [OK because definitions
                 ┌▼──────▼┐                                       ┌▼──────▼┐    in one shared lib]
                 │ baz_py │                                       │ baz_py │
                 └────────┘                                       └────────┘
```

Or is it more complicated than that? I see the example shared library [depends on Drake's shared library](https://github.com/EricCousineau-TRI/repro/blob/1bc74a62fbaaff8e773b222e8a735d928386bc9d/drake_stuff/drake_downstream_pybind/common/BUILD.bazel#L43). Do we need to use shared libraries all the way back up the dependency tree so that ODR won't be violated by depending any transitive dependency twice?
</blockquote></details>

OK Resolved in scope of immediate PR per TODO and tracked via #151

**Pull request merged**
