### PR TITLE
[py] Avoid ODR violations in bindings

### LINKED ISSUE #151: cc, py: Should avoid ODR and recompilation for cc targets linking against static Drake targets
Regarding discussion today, the following has example of ODR:
https://github.com/EricCousineau-TRI/repro/tree/1bc74a62/bazel/bazel_shared_lib_odr_instrumentation

This is akin to solution employed in Anzu (prototyped in Anzu PR 9421):
https://github.com/EricCousineau-TRI/repro/tree/1bc74a62/drake_stuff/drake_downstream_pybind
Note that this does a bit that what is present Anzu master, as evidenced by unchecked boxes in Anzu PR 9421.

FYI @sloretz @IanTheEngineer

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #151

Requires #238

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239)* status: 0 of 26 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239#-NPO5fmyBjv6VMKkT4j1:-NPO5fmyBjv6VMKkT4j2:bbr96hs) (no related file):*
Working: Going to hoist Shane's odr test from Anzu.

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239)* status: 0 of 26 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239#-NPO5fmyBjv6VMKkT4j1:-NPO5pE10wpP6fON_E04:b1io5dw) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Going to hoist Shane's odr test from Anzu.
</blockquote></details>

(or rather, copy some form of it - still worthwhile to have the test as-is in Anzu)

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239)* status: 0 of 28 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239#-NPO5fmyBjv6VMKkT4j1:-NPOGBbq5_5lc-PIJoyF:b5ufmvr) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(or rather, copy some form of it - still worthwhile to have the test as-is in Anzu)
</blockquote></details>

Done. Actually, I think we just keep this version, so "hoist from Anzu" works

___

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sloretz for review, please!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239#-:-NPu-K0vD7ljfmvRowzr:b-ioi1p3)* status: 0 of 33 files reviewed, all discussions resolved (waiting on @sloretz)

___
*[`drake_ros/CMakeLists.txt` line 46 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239#-NPu-QPm-beKOjDRFIDo:-NPu-QPm-beKOjDRFIDp:b-veadvj) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/8f989eb8ce353912ac4a9e23da99b14b00493ad1/drake_ros/CMakeLists.txt#L46)):*
> ```CMake
>     # TODO(eric.cousineau): Reenable once both clang-format and cpplint agree
>     # on the same formatting for drake_ros_pybind.h.
>     # ament_cpplint()
> ```

FYI This seems broken, and I don't think we should block progress due to broken linters.

**Comment by EricCousineau-TRI** [comment]
Yuck:
> image

**Comment by EricCousineau-TRI** [comment]
OK, sweet! Not exactly sure about the cache miss / invalidation, but it seems better (or the same?) as changes prior to #248.

**Comment by EricCousineau-TRI** [comment]
The commit on master immediately after #248 did not seem to have caching either:
https://github.com/RobotLocomotion/drake-ros/commit/4a90e35a75d3b91fda1e66aad007736587a25562

However, the commit thereafter did:
https://github.com/RobotLocomotion/drake-ros/commit/fc7ba9e48c5a94f828e651bcf278569f490333c4

Guesses:
- It's based on the worker machine's region / availability zone?
- Perhaps the caching is only allowed from `main` to PRs, and for one PR to itself, but not from a PR to `main` to avoid possible cache poisoning?

**Comment by EricCousineau-TRI** [comment]
That being said, I think we ignore it for now for this PR, because at least we can warm-up a single PR. It was unclear to me if caching was working properly before #248 given the full output root of Bazel possibly causing spillover / loss of useful cache data.

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239)* status: 21 of 33 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`drake_ros/drake_ros/core/cc_pybind.cc` line 31 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239#-NPxPwSUA8hRg1isHbVx:-NPxPwSVDNnEZyI2M2BU:bd9yjij) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/8f989eb8ce353912ac4a9e23da99b14b00493ad1/drake_ros/drake_ros/core/cc_pybind.cc#L31)):*
> ```cpp
> 
> // TODO(eric.cousineau): Why is DRAKE_ROS_NO_EXPORT necessary on the below
> // class when `drake_ros_py` is private per `drake_ros_pybind.h`?
> ```

This comment gives a clue to the thinking when visibility attributes on namespaces were implemented. It says it's valid for different openings of the same namespace to have different attributes. The `DRAKE_ROS_NO_EXPORT` use in the header probably does nothing because no symbols are defined in it.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=21764#c10

I get the sense from the patch (but I don't know the code very well) that it implemented as sort of syntactic sugar for `#pragma GCC visibility push(hidden)` when the namespace is entered, and `#pragma GCC visibility pop` when the namespace is exited. The visibility isn't attached to the namespace itself.

https://gcc.gnu.org/git/?p=gcc.git&a=commit;h=47477847fe14543cca650e796a7f4a07f3173e6b

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239)* status: 21 of 33 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sloretz)

___
*[`drake_ros/drake_ros/core/cc_pybind.cc` line 31 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239#-NPxPwSUA8hRg1isHbVx:-NPxUEbFDnhbNWpUsyIL:bcpq4l4) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/8f989eb8ce353912ac4a9e23da99b14b00493ad1/drake_ros/drake_ros/core/cc_pybind.cc#L31)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

This comment gives a clue to the thinking when visibility attributes on namespaces were implemented. It says it's valid for different openings of the same namespace to have different attributes. The `DRAKE_ROS_NO_EXPORT` use in the header probably does nothing because no symbols are defined in it.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=21764#c10

I get the sense from the patch (but I don't know the code very well) that it implemented as sort of syntactic sugar for `#pragma GCC visibility push(hidden)` when the namespace is entered, and `#pragma GCC visibility pop` when the namespace is exited. The visibility isn't attached to the namespace itself.

https://gcc.gnu.org/git/?p=gcc.git&a=commit;h=47477847fe14543cca650e796a7f4a07f3173e6b

</blockquote></details>

Working: Ah, gotcha. In that case, I will just decorate all of the namespaces.

\cc @jwnimmer-tri just in case you didn't already know re: https://github.com/RobotLocomotion/drake/pull/18677

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239)* status: 21 of 33 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sloretz)

___
*[`drake_ros/drake_ros/core/cc_pybind.cc` line 31 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239#-NPxPwSUA8hRg1isHbVx:-NPxV9F150FQBZOXcJiq:b-dbipyf) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/8f989eb8ce353912ac4a9e23da99b14b00493ad1/drake_ros/drake_ros/core/cc_pybind.cc#L31)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Ah, gotcha. In that case, I will just decorate all of the namespaces.

\cc @jwnimmer-tri just in case you didn't already know re: https://github.com/RobotLocomotion/drake/pull/18677
</blockquote></details>

`*` "decorate all of the namespaces" >= "decorate all *occurrences* of the namespace `drake_ros_py`"

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239)* status: 21 of 36 files reviewed, all discussions resolved (waiting on @sloretz)

___
*[`drake_ros/drake_ros/core/cc_pybind.cc` line 31 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239#-NPxPwSUA8hRg1isHbVx:-NPxVllb8DPj41xJhSVs:b-dtkds3) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/8f989eb8ce353912ac4a9e23da99b14b00493ad1/drake_ros/drake_ros/core/cc_pybind.cc#L31)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

`*` "decorate all of the namespaces" >= "decorate all *occurrences* of the namespace `drake_ros_py`"
</blockquote></details>

Done, thanks!

**Review by sloretz — COMMENTED** [review]
> Reviewed 2 of 31 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239)* status: 23 of 36 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`drake_ros/tools/skylark/drake_ros_cc.bzl` line 40 at r4](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239#-NPxdHxj8NrhNZxjHL0C:-NPxdHxj8NrhNZxjHL0D:b8wwpq1) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/34ccc62c65999d7a455290b15d4e1dbdf3f8199b/drake_ros/tools/skylark/drake_ros_cc.bzl#L40)):*
> ```Starlark
>     hdrs_target = "_" + name + "_hdrs"
> 
>     hdrs, srcs, data = _extract_shared_library_package_deps(
> ```

Do I understand correctly that this finds all header files, source files (optionally alternatively any object files compiled with -fPIC), and data dependencies from all labels in `package_deps`, so that they can be compiled again into a single shared library? Does that mean that any accidental direct or transtive `drake` static library targets in `package_deps` would get compiled into this shared library, and potentially violate ODR if we also link against `drake_shared_library`, so it's important to make sure `package-deps` are only labels from `drake_ros` itself?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239)* status: 23 of 36 files reviewed, all discussions resolved (waiting on @sloretz)

___
*[`drake_ros/tools/skylark/drake_ros_cc.bzl` line 40 at r4](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239#-NPxdHxj8NrhNZxjHL0C:-NPxnNPe-3UlYyXSgKOQ:b-p4gjwh) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/34ccc62c65999d7a455290b15d4e1dbdf3f8199b/drake_ros/tools/skylark/drake_ros_cc.bzl#L40)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Do I understand correctly that this finds all header files, source files (optionally alternatively any object files compiled with -fPIC), and data dependencies from all labels in `package_deps`, so that they can be compiled again into a single shared library? Does that mean that any accidental direct or transtive `drake` static library targets in `package_deps` would get compiled into this shared library, and potentially violate ODR if we also link against `drake_shared_library`, so it's important to make sure `package-deps` are only labels from `drake_ros` itself?
</blockquote></details>

Done. Added docs and "only this package check".

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239)* status: 23 of 36 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sloretz)

___
*[`drake_ros/tools/skylark/drake_ros_cc.bzl` line 33 at r5](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239#-NPxnypd6WF1WqUTtRwG:-NPxnypeAxtyA65k_Jiw:b-igmvos) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/b58c8c444e8099cafe968b72c3f4ba000ddbe523/drake_ros/tools/skylark/drake_ros_cc.bzl#L33)):*
> ```Starlark
> def drake_ros_cc_recompile_as_shared_library(
>         name,
>         package_deps,
> ```

Working: Will rename.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239)* status: 23 of 36 files reviewed, all discussions resolved (waiting on @sloretz)

___
*[`drake_ros/tools/skylark/drake_ros_cc.bzl` line 33 at r5](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239#-NPxnypd6WF1WqUTtRwG:-NPxq-js8mBpjo3JpEOM:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/b58c8c444e8099cafe968b72c3f4ba000ddbe523/drake_ros/tools/skylark/drake_ros_cc.bzl#L33)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Will rename.
</blockquote></details>

Done.

**Review by sloretz — COMMENTED** [review]
> Reviewed 3 of 31 files at r3, 4 of 4 files at r4, 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239)* status: 31 of 36 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`drake_ros/CMakeLists.txt` line 46 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239#-NPu-QPm-beKOjDRFIDo:-NPxzslgAtWNte6F-6gg:b-xdwe56) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/8f989eb8ce353912ac4a9e23da99b14b00493ad1/drake_ros/CMakeLists.txt#L46)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FYI This seems broken, and I don't think we should block progress due to broken linters.
</blockquote></details>

Seems like a clang-format bug. I opened a PR with a different workaround that keeps both tools enabled: https://github.com/EricCousineau-TRI/drake-ros/pull/7
___
*[`drake_ros/drake_ros/test/odr_py_test.py` line 14 at r6](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239#-NPxupSjAjtXUID5hKiD:-NPxupSjAjtXUID5hKiE:b-es4c4b) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/616f7fad368862696cfae164e7f81d2f6e5aaad4/drake_ros/drake_ros/test/odr_py_test.py#L14)):*
> ```Python
> from pydrake.geometry import GeometryId
> 
> # This is a purposefully unused import.
> ```

Purposely imported here because `drake_ros.viz` imports all of `drake_ros`, so that if there is a dependency on a static `drake` target somewhere then we would catch it?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239)* status: 27 of 36 files reviewed, 1 unresolved discussion (waiting on @sloretz)

___
*[`drake_ros/CMakeLists.txt` line 46 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239#-NPu-QPm-beKOjDRFIDo:-NPy0vMN0LZnjO6DsDhd:b-gtqo8n) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/8f989eb8ce353912ac4a9e23da99b14b00493ad1/drake_ros/CMakeLists.txt#L46)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Seems like a clang-format bug. I opened a PR with a different workaround that keeps both tools enabled: https://github.com/EricCousineau-TRI/drake-ros/pull/7
</blockquote></details>

Done, thank! Would you be able to file upstream issue?
___
*[`drake_ros/drake_ros/test/odr_py_test.py` line 14 at r6](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239#-NPxupSjAjtXUID5hKiD:-NPy0P2FD8IafppzG5gR:bwgn2ve) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/616f7fad368862696cfae164e7f81d2f6e5aaad4/drake_ros/drake_ros/test/odr_py_test.py#L14)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Purposely imported here because `drake_ros.viz` imports all of `drake_ros`, so that if there is a dependency on a static `drake` target somewhere then we would catch it?
</blockquote></details>

That was my intent, but I realize it was fuzzy, so your comment illustrates a defect with this testing - it's a tad bit indirect. Let me change it around.

I plan to put `NextGeometryId` into something like `drake_ros._cc.core._testing`
This confirms we don't violate ODR in a place we actually care about (the bindings), rather than illustrating the possible issue without testing it directly.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239)* status: 31 of 36 files reviewed, all discussions resolved (waiting on @sloretz)

___
*[`drake_ros/drake_ros/test/odr_py_test.py` line 14 at r6](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239#-NPxupSjAjtXUID5hKiD:-NPy3OuzBS3NnilzUZOA:bdpblio) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/616f7fad368862696cfae164e7f81d2f6e5aaad4/drake_ros/drake_ros/test/odr_py_test.py#L14)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I'm ok with it being indirect, as long as it's testing what it needs to.  A longer comment in the file might be helpful for future readers.
</blockquote></details>

Done. I think the more direct testing is more valuable, so went ahead and did that one.

**Review by sloretz — APPROVED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Review by sloretz — APPROVED** [review]
Filed upstream issue for namespace comments in clang-format: https://github.com/llvm/llvm-project/issues/61251

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239#-:-NPy8vJp8GRL13p95I9e:bjaqu89)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
oops, meant to add "violations" in the commit tile. oops!

**Pull request merged**
