### PR TITLE
Add option to set RMW_LOCALHOST_ONLY by default

### PR DESCRIPTION
**Pull request by sloretz**
This adds an option to `bazel_ros2_rules` that allows configuring whether `RMW_LOCALHOST_ONLY` is set to 0 or 1 by default.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/94)

### CODE REVIEW

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm_strong:, but with nit on what default value is. Thanks!

\cc @iantheengineer @calderpg-tri

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/94#-:-N80U-v063Cr4HYb_XY4:b-1mvfqs)* status: all files reviewed, 1 unresolved discussion (waiting on @sloretz)

___
*[`bazel_ros2_rules/ros2/resources/templates/distro.bzl.tpl` line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/94#-N80TgVZ6lAs0MzWh9gf:-N80TgVZ6lAs0MzWh9gg:b-eojp12) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f3a702ccec12b1fa79c1cb402053fd36a00ec88/bazel_ros2_rules/ros2/resources/templates/distro.bzl.tpl#L9)):*
> ```Smarty
>   "AMENT_PREFIX_PATH": ["path-prepend"] + @AMENT_PREFIX_PATHS@,
>   "${LOAD_PATH}": ["path-prepend"] + @LOAD_PATHS@,
>   "RMW_LOCALHOST_ONLY": ["set-if-not-set", @DEFAULT_LOCALHOST_ONLY@],
> ```

nit What is the default value when sourcing a setup? Is this set normally in scripts?

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/94)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`bazel_ros2_rules/ros2/resources/templates/distro.bzl.tpl` line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/94#-N80TgVZ6lAs0MzWh9gf:-N80WBeD0C1nCfRCO6Jq:bqh1xfm) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f3a702ccec12b1fa79c1cb402053fd36a00ec88/bazel_ros2_rules/ros2/resources/templates/distro.bzl.tpl#L9)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit What is the default value when sourcing a setup? Is this set normally in scripts?
</blockquote></details>

`RMW_LOCALHOST_ONLY` is normally not set. The default value when not specified is equivalent to `RMW_LOCALHOST_ONLY=0`.

**Comment by EricCousineau-TRI** [comment]
Thanks! The community way to reconsider that - it seems dangerous, IMO, but yeah, good for now!

**Review by EricCousineau-TRI — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/94)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

**Pull request merged**
