### PR TITLE
[drake] Upgrade to v1.25.0

### LINKED ISSUE #327: Please update DRAKE_SUGGESTED_VERSION to v1.25.0
https://github.com/RobotLocomotion/drake/releases/tag/v1.25.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #327.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/328)

### CODE REVIEW

**Comment by ahcorde** [comment]
I fixed the CI in this PR https://github.com/RobotLocomotion/drake-ros/pull/329

**Comment by adityapande-1995** [comment]
> I fixed the CI in this PR #329

Merged, and this one can be rebased now.

**Comment by jwnimmer-tri** [comment]
Ready to go.

**Review by IanTheEngineer — APPROVED** [review]
:LGTM: Thanks, Jeremy!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/328#-:-NotVvSJ0xet6RVDbmdE:bt0gbx7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Pull request merged**
