### PR TITLE
Add Drake C++ systems to drake_ros_viz package.

### PR DESCRIPTION
**Pull request by hidmic**
Spin off form #2. Built on top of #22.

To do:
- [x] Add tests for marker IDs when there are multiple markers using the same marker namespace. The IDs should be incremented for each instance.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/23)

### CODE REVIEW

**Comment by gbiggs** [comment]
@IanTheEngineer The tests for this PR pass. What's left to be done to make it ready to merge?

**Comment by gbiggs** [comment]
I've fixed the Reviewable comments, although I'm not sure if I resolved them correctly in Reviewable.

There are tests in this PR, and the examples PR (#39) includes samples on how to use it.

Once CI finishes (and passes) and the PR is approved, I think this is good to merge.

**Review by sloretz — COMMENTED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/23)* status: 35 of 39 files reviewed, 1 unresolved discussion (waiting on @hidmic and @sloretz)

___
*[drake_ros_viz/src/scene_markers_system.cc, line 195 at r6](https://reviewable.io/reviews/robotlocomotion/drake-ros/23#-N-hi_Qb276nH0DyHqhp:-N-hi_Qb276nH0DyHqhq:b-685j8b) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8a9827b8f97b1cac2b251892b51ce0422f11941e/drake_ros_viz/src/scene_markers_system.cc#L195)):*
> ```cpp
>     visualization_msgs::msg::Marker& upper_cap_marker =
>         marker_array_->markers.back();
>     upper_cap_marker.ns = prototype_marker_.ns + "/upper_cap";
> ```

I think it's a little inconvenient to have the capsule split into three namespaces. I would increment the marker ID instead. In the RViz UI each namespace is a checkbox that can be toggled on and off, so using different namespaces means it takes 3 checkboxes to start or stop visualizing it.

**Review by geoffor — COMMENTED** [review]
> Reviewed 2 of 39 files at r3, 1 of 2 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/23)* status: 37 of 39 files reviewed, 1 unresolved discussion (waiting on @geoffor and @sloretz)

___
*[drake_ros_viz/src/scene_markers_system.cc, line 195 at r6](https://reviewable.io/reviews/robotlocomotion/drake-ros/23#-N-hi_Qb276nH0DyHqhp:-N-v_nq29RCGoA_LXAnz:b-hglk8q) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8a9827b8f97b1cac2b251892b51ce0422f11941e/drake_ros_viz/src/scene_markers_system.cc#L195)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I think it's a little inconvenient to have the capsule split into three namespaces. I would increment the marker ID instead. In the RViz UI each namespace is a checkbox that can be toggled on and off, so using different namespaces means it takes 3 checkboxes to start or stop visualizing it.




</blockquote></details>

I've pushed a commit which removes the extra namespaces and instead increments the marker IDs for the upper and lower caps from the body marker. Can you please check that this resolves the usability issue?

**Review by sloretz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/23)* status: 37 of 39 files reviewed, 3 unresolved discussions (waiting on @geoffor, @hidmic, and @sloretz)

___
*[drake_ros_viz/src/scene_markers_system.cc, line 73 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/23#-N01beAX3IdyR9JlBvNq:-N01beAY7KcLQSsM2CVZ:b-feboou) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71732ab2e6efc743889057cbf9b5557dff4912c6/drake_ros_viz/src/scene_markers_system.cc#L73)):*
> ```cpp
>           plants,
>       const drake::geometry::GeometryId& geometry_id,
>       const std::string& marker_namespace, int marker_id,
> ```

There might there needs to be a way to communicate that multiple marker ID's were used to CalcSceneMarkers. Maybe a pointer to an int? Or maybe it would be fine if the caller is expected to read the last marker_id used in the marker_array before calling `Populate` again?
___
*[drake_ros_viz/src/scene_markers_system.cc, line 261 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/23#-N01awzaEesS0JBqkSIO:-N01awzaEesS0JBqkSIP:bg89ffq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71732ab2e6efc743889057cbf9b5557dff4912c6/drake_ros_viz/src/scene_markers_system.cc#L261)):*
> ```cpp
>   drake::systems::OutputPortIndex scene_markers_port_index;
>   std::unordered_set<const drake::multibody::MultibodyPlant<double>*> plants;
>   std::unordered_map<drake::geometry::GeometryId, int>
> ```

This map links the drake geometry id and the ROS Marker ID. Now that capsule markers have 3 ids, it might need some modification to support that. Maybe the current type is fine if it's documented the marker id for each geometry is the first marker used by it?

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/23)* status: 37 of 39 files reviewed, 3 unresolved discussions (waiting on @geoffor and @hidmic)

___
*[drake_ros_viz/src/scene_markers_system.cc, line 195 at r6](https://reviewable.io/reviews/robotlocomotion/drake-ros/23#-N-hi_Qb276nH0DyHqhp:-N02-yMQEgC4E7OfR3NF:bf9xpn2) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8a9827b8f97b1cac2b251892b51ce0422f11941e/drake_ros_viz/src/scene_markers_system.cc#L195)):*
<details><summary><i>Previously, geoffor wrote…</i></summary><blockquote>

I've pushed a commit which removes the extra namespaces and instead increments the marker IDs for the upper and lower caps from the body marker. Can you please check that this resolves the usability issue?
</blockquote></details>

I checked, and there's an issue with the marker ID's being reused. I'll see if I can add a test for the issue. It results in this second capsule not having it's bottom displayed



<details><summary>Markers message</summary>

```bash
$ ros2 topic echo --once /scene_markers/visual 
markers:
- header:
    stamp:
      sec: 208
      nanosec: 200000000
    frame_id: DefaultModelInstance/b_capsule/19
  ns: plant
  id: 0
  type: 3
  action: 0
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 0.5
    y: 0.5
    z: 2.0
  color:
    r: 1.0
    g: 0.0
    b: 1.0
    a: 1.0
  lifetime:
    sec: 0
    nanosec: 0
  frame_locked: true
  points: []
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
- header:
    stamp:
      sec: 208
      nanosec: 200000000
    frame_id: DefaultModelInstance/b_capsule/19
  ns: plant
  id: 1
  type: 2
  action: 0
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 1.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 0.5
    y: 0.5
    z: 0.5
  color:
    r: 1.0
    g: 0.0
    b: 1.0
    a: 1.0
  lifetime:
    sec: 0
    nanosec: 0
  frame_locked: true
  points: []
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
- header:
    stamp:
      sec: 208
      nanosec: 200000000
    frame_id: DefaultModelInstance/b_capsule/19
  ns: plant
  id: 2
  type: 2
  action: 0
  pose:
    position:
      x: 0.0
      y: 0.0
      z: -1.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 0.5
    y: 0.5
    z: 0.5
  color:
    r: 1.0
    g: 0.0
    b: 1.0
    a: 1.0
  lifetime:
    sec: 0
    nanosec: 0
  frame_locked: true
  points: []
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
- header:
    stamp:
      sec: 208
      nanosec: 200000000
    frame_id: DefaultModelInstance/a_capsule/16
  ns: plant
  id: 1
  type: 3
  action: 0
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 1.0
    y: 1.0
    z: 1.0
  color:
    r: 0.0
    g: 1.0
    b: 1.0
    a: 1.0
  lifetime:
    sec: 0
    nanosec: 0
  frame_locked: true
  points: []
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
- header:
    stamp:
      sec: 208
      nanosec: 200000000
    frame_id: DefaultModelInstance/a_capsule/16
  ns: plant
  id: 2
  type: 2
  action: 0
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.5
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 1.0
    y: 1.0
    z: 1.0
  color:
    r: 0.0
    g: 1.0
    b: 1.0
    a: 1.0
  lifetime:
    sec: 0
    nanosec: 0
  frame_locked: true
  points: []
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
- header:
    stamp:
      sec: 208
      nanosec: 200000000
    frame_id: DefaultModelInstance/a_capsule/16
  ns: plant
  id: 3
  type: 2
  action: 0
  pose:
    position:
      x: 0.0
      y: 0.0
      z: -0.5
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 1.0
    y: 1.0
    z: 1.0
  color:
    r: 0.0
    g: 1.0
    b: 1.0
    a: 1.0
  lifetime:
    sec: 0
    nanosec: 0
  frame_locked: true
  points: []
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
---
```
</details>

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/23)* status: 36 of 39 files reviewed, all discussions resolved (waiting on @geoffor)

___
*[drake_ros_viz/src/scene_markers_system.cc, line 195 at r6](https://reviewable.io/reviews/robotlocomotion/drake-ros/23#-N-hi_Qb276nH0DyHqhp:-N02Fkrp7h2QLjppHaqH:bqidp0v) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8a9827b8f97b1cac2b251892b51ce0422f11941e/drake_ros_viz/src/scene_markers_system.cc#L195)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I checked, and there's an issue with the marker ID's being reused. I'll see if I can add a test for the issue. It results in this second capsule not having it's bottom displayed



<details><summary>Markers message</summary>

```bash
$ ros2 topic echo --once /scene_markers/visual 
markers:
- header:
    stamp:
      sec: 208
      nanosec: 200000000
    frame_id: DefaultModelInstance/b_capsule/19
  ns: plant
  id: 0
  type: 3
  action: 0
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 0.5
    y: 0.5
    z: 2.0
  color:
    r: 1.0
    g: 0.0
    b: 1.0
    a: 1.0
  lifetime:
    sec: 0
    nanosec: 0
  frame_locked: true
  points: []
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
- header:
    stamp:
      sec: 208
      nanosec: 200000000
    frame_id: DefaultModelInstance/b_capsule/19
  ns: plant
  id: 1
  type: 2
  action: 0
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 1.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 0.5
    y: 0.5
    z: 0.5
  color:
    r: 1.0
    g: 0.0
    b: 1.0
    a: 1.0
  lifetime:
    sec: 0
    nanosec: 0
  frame_locked: true
  points: []
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
- header:
    stamp:
      sec: 208
      nanosec: 200000000
    frame_id: DefaultModelInstance/b_capsule/19
  ns: plant
  id: 2
  type: 2
  action: 0
  pose:
    position:
      x: 0.0
      y: 0.0
      z: -1.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 0.5
    y: 0.5
    z: 0.5
  color:
    r: 1.0
    g: 0.0
    b: 1.0
    a: 1.0
  lifetime:
    sec: 0
    nanosec: 0
  frame_locked: true
  points: []
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
- header:
    stamp:
      sec: 208
      nanosec: 200000000
    frame_id: DefaultModelInstance/a_capsule/16
  ns: plant
  id: 1
  type: 3
  action: 0
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 1.0
    y: 1.0
    z: 1.0
  color:
    r: 0.0
    g: 1.0
    b: 1.0
    a: 1.0
  lifetime:
    sec: 0
    nanosec: 0
  frame_locked: true
  points: []
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
- header:
    stamp:
      sec: 208
      nanosec: 200000000
    frame_id: DefaultModelInstance/a_capsule/16
  ns: plant
  id: 2
  type: 2
  action: 0
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.5
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 1.0
    y: 1.0
    z: 1.0
  color:
    r: 0.0
    g: 1.0
    b: 1.0
    a: 1.0
  lifetime:
    sec: 0
    nanosec: 0
  frame_locked: true
  points: []
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
- header:
    stamp:
      sec: 208
      nanosec: 200000000
    frame_id: DefaultModelInstance/a_capsule/16
  ns: plant
  id: 3
  type: 2
  action: 0
  pose:
    position:
      x: 0.0
      y: 0.0
      z: -0.5
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 1.0
    y: 1.0
    z: 1.0
  color:
    r: 0.0
    g: 1.0
    b: 1.0
    a: 1.0
  lifetime:
    sec: 0
    nanosec: 0
  frame_locked: true
  points: []
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
---
```
</details>

</blockquote></details>

Made the caller count the markers in c726baf


___
*[drake_ros_viz/src/scene_markers_system.cc, line 73 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/23#-N01beAX3IdyR9JlBvNq:-N02FdtIEpHS0rrDUs2T:bo1mh0b) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71732ab2e6efc743889057cbf9b5557dff4912c6/drake_ros_viz/src/scene_markers_system.cc#L73)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

There might there needs to be a way to communicate that multiple marker ID's were used to CalcSceneMarkers. Maybe a pointer to an int? Or maybe it would be fine if the caller is expected to read the last marker_id used in the marker_array before calling `Populate` again?
</blockquote></details>

Made the caller count the markers added in c726baf
___
*[drake_ros_viz/src/scene_markers_system.cc, line 261 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/23#-N01awzaEesS0JBqkSIO:-N02Fwke3xzJfkbju_CN:b-4c6u3g) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71732ab2e6efc743889057cbf9b5557dff4912c6/drake_ros_viz/src/scene_markers_system.cc#L261)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

This map links the drake geometry id and the ROS Marker ID. Now that capsule markers have 3 ids, it might need some modification to support that. Maybe the current type is fine if it's documented the marker id for each geometry is the first marker used by it?
</blockquote></details>

Documented the id is the first marker used for the geometry c726baf

**Review by sloretz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r6, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/23#-:-N0C2AH_0Mkc3cbkJYNE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hidmic)

**Comment by sloretz** [comment]
@gbiggs I think this is ready. I only hesitate because I made the last couple commits. Would you be willing to review, and if it looks good to you, approve and squash/merge it?

**Review by sloretz — APPROVED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hidmic)

**Review by gbiggs — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hidmic)

**Pull request merged**
