### PR TITLE
[ci] Allow disabling CI via PR label

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Using while prototyping things such #169

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/170)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sloretz for review, please
(not high priority)

I'm not sure if there is better way
\cc @iantheengineer 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/170#-:-NEup2YpEr7s-A_aRpel:biz5l3f)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @sloretz)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/170)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sloretz)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/170#-NEup9ud8RugBg3ZcelK):*
Working: This is example usage. Should remove before merging.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/170)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @jwnimmer-tri and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/170#-NEviQ88-Lr_oiLIhYOx:-NEviQ894ad9JBEH08Dg:b-2yd84w) (no related file):*
Working: Requires #179

___
___
*[`README.md` line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/170#-NEv4ngu2CNH9wdfCf3S:-NEviND_AgIjDkqMR6fp:b-9sng21) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/391a6337e4fc1ac5d0bb786766adce72e075f2de/README.md#L26)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

typo (while you're here anyway...)
</blockquote></details>

OK Thanks! Split off to #179

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/170)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/170#-NEviQ88-Lr_oiLIhYOx:-NEw4CG_0PncxWnsSAcU:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Requires #179
</blockquote></details>

Done.

___
___
*[`README.md` line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/170#-NEv4ngu2CNH9wdfCf3S:-NEw4B01C6PQh4TZfSrn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/391a6337e4fc1ac5d0bb786766adce72e075f2de/README.md#L26)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Thanks! Split off to #179
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
Thanks! Trying this out now.

Fake review: +@EricCousineau-TRI :lgtm:

Working to make reviewable block merging if `status: block ci` leveraging `drake-ci` example:
https://github.com/RobotLocomotion/drake-ci/wiki/reviewable.io-review-completion-condition

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/170#-:-NORypFU3K11KGoUxBMI:be2ybr5)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @sloretz)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/170)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/170#-NEup9ud8RugBg3ZcelK):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: This is example usage. Should remove before merging.
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
-@sloretz (to make GitHub happy as well)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/170#-:-NORzKrGDM7cEDQmkrAu:bvbvltq)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
> Working to make reviewable block merging if status: block ci leveraging drake-ci example ...

FYI I don't think Reviewable can do this soundly.  If someone adds the label, then CI gets skipped, then removes the label, then Reviewable can't know that CI was skipped.

I think either the label-checking code in the Actions configuration needs to _fail_ the build (not skip it), or else in the GitHub Settings tab you need to mark at least one of the CI status items as "required" in branch protections.

**Comment by EricCousineau-TRI** [comment]
SGTM!

**Comment by jwnimmer-tri** [comment]
I take it back, in part.  It looks like reviewable has a `checks` array in its input data, so you could probably scan for any skipped builds in there somehow.  In any case, I still the the best answer is to use branch protections to enforce any required tests.

**Comment by EricCousineau-TRI** [comment]
Briefly tried "make it fail", but got confused.
Added branch protection:
image

**Comment by EricCousineau-TRI** [comment]
Using "PR > Checks > Re-run all jobs" does not work. Closing re-opening just to verify that still works.

**Comment by EricCousineau-TRI** [comment]
K, closing and reopening still works. Confirming that pushing anew should work.

**Comment by EricCousineau-TRI** [comment]
K, pushing anew works.

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/170#-:-NOSMJUt3ldUUYsFjgOG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sloretz)

___
*[`CONTRIBUTING.md` line 13 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/170#-NOSLr5s8ZnZ0sUV74Ya:-NOSLr5s8ZnZ0sUV74Yb:b-9obs71) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ae6a7c3d745baa4f1d570bc1bc24f42d680670f9/CONTRIBUTING.md#L13)):*
> ```Markdown
> 
> If you are prototyping a PR, consider saving resources by disabling CI by
> adding the `status: block ci` label to your PR.
> ```

nit My only question is whether this is the optimal label name. 

I think it's probably fine to land as-is, but I wonder if there is something more immediately clear?

The best I could come up with would be "status: defer ci" or "status: suspend ci".



_Code quote:_
```Markdown
block ci
```

**Review by cottsay — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/170#-:-NOw7m2a8VP4grhpMo3U:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sloretz)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/170)* status: 2 of 7 files reviewed, all discussions resolved (waiting on @jwnimmer-tri and @sloretz)

___
*[`CONTRIBUTING.md` line 13 at r5](https://reviewable.io/reviews/RobotLocomotion/drake-ros/170#-NOSLr5s8ZnZ0sUV74Ya:-NOyQOfT9z3mPL3WWlwa:bphyyrq) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/ae6a7c3d745baa4f1d570bc1bc24f42d680670f9/CONTRIBUTING.md#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit My only question is whether this is the optimal label name. 

I think it's probably fine to land as-is, but I wonder if there is something more immediately clear?

The best I could come up with would be "status: defer ci" or "status: suspend ci".

</blockquote></details>

Done. Yeah, I can't come up with anything better either. Thankfully, seems easy enough to change.

**Review by jwnimmer-tri — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/170)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

**Comment by EricCousineau-TRI** [comment]
CI failure due to #221, merging this forward.

**Pull request merged**
