### PR TITLE
[bazel_ros2_rules] Revert ros_cc_test feature for shim control

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Partially reverts #233.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/261)

### CODE REVIEW

**Review by sloretz — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/261)* status: all files reviewed, 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`bazel_ros2_rules/ros2/ros_cc.bzl` line 184 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/261#-NQbW0IX062CK7PCrLS-:-NQbW0IX062CK7PCrLS0:b-ls8o4c) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/a8a4f1d6242ad8db55c933209aee8739b522deb2/bazel_ros2_rules/ros2/ros_cc.bzl#L184)):*
> ```Starlark
>         cc_test_rule: optional cc_test() rule override
> 
>     Additional keyword arguments are forwarded to the `cc_test_rule`.
> ```

nit, it looks like pre #233 it looks like this line said the keyword arguments are forwarded to the `cc_test_rule` and `cc_binary_rule`. It looks like that's still the case. `kwargs` passes through `remove_test_specific_kwargs` before being passed to the `cc_binary_rule`. I'd recommend restoring the old comment.

```diff
-    Additional keyword arguments are forwarded to the `cc_test_rule` and to the
-    `cc_binary_rule` (minus the test specific ones).
+    Additional keyword arguments are forwarded to the `cc_test_rule`.
```

**Review by jwnimmer-tri — COMMENTED** [review]
+@EricCousineau-TRI for review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/261#-:-NQfduH73T1p1-JPrSmw:b-uanxjs)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI and @sloretz)

**Review by sloretz — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/261)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm:, thanks!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/261#-:-NQfj3RkBSQquAbaygrw:bpqxd5f)* status: all files reviewed, 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ros/261#-NQfivWP7grTg2d98sz7):*
BTW "added" => "adding"

**Pull request merged**
