### PR TITLE
Add Ament hook to put pydrake in PYTHONPATH

### LINKED ISSUE #157: ament: Should ensure pydrake is available on PYTHON path
Per #156, I seemed to need to add something like `export PYTHONPATH=/opt/drake/lib/python3.10/site-packages` to make `colcon test` pass locally.

We should fix this.

Possible solutions:
- Similar to #143 via ament hook.
- Adding ctest env vars, similar to https://github.com/RobotLocomotion/drake-external-examples/pull/155

@cottsay Can you handle this over next two weeks?
Ideally, we don't have to figure out Python major/minor. I'm not sure if Drake's CMake setup has affordance for it; if not, ideally ament / ros2 has some affordance.

\cc @IanTheEngineer @sloretz

### PR DESCRIPTION
**Pull request by cottsay**
~~This change borrows from the `PYTHONPATH` hook creation mechanism used in `ament_cmake_core`.~~

~~It makes the following assumptions:~~
~~1. Drake installs Python modules to `platlib`, and not `purelib`~~
~~2. Drake installs Python modules to the same prefix as `libdrake.so`~~
~~3. Drake uses the same Python interpreter version as the system's default~~

~~Closes #157~~
~~Related to #143~~

Requires RobotLocomotion/drake#18201

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/160)

### CODE REVIEW

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/160)* status: all files reviewed, 2 unresolved discussions (waiting on @cottsay and @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/160#-NEusaz11yeSUr6a4Tdz:-NEuty2F9PiOWlOEWeDB:btsjw0s) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Needs testing.

I can reproduce workflow friction on #171 using `colcon test --packages-up-to drake_ros_core`
Will test as part of that PR
</blockquote></details>

It did not work as I expected in that PR; however, I can also reproduce using purely this PR.

On commit 1d753c1:
```
$ cd ros_ws
$ source /opt/ros/humble/setup.bash
$ colcon build --packages-up-to drake_ros_core
$ colcon test --packages-up-to drake_ros_core --event-handlers=console_cohesion+ --ctest-args -R test_pub_sub_py
...
5: ERROR ../.. - ModuleNotFoundError: No module named 'pydrake'
...
```

Please note that I assume `colcon test`leverages workspaces `setup.sh`, thus the ament hooks should implicitly be part of test env.

Looking at just the workspace env:
```
$ bash-isolate
$ source ./install/setup.sh
$ echo $PYTHONPATH | sed 's#:#\n#g'| grep /opt/drake
/opt/drake/local/lib/python3.10/dist-packages
# Wrong

$ [[ -d /opt/drake/lib/python3.10/site-packages ]] && echo Correct
Correct
```

___

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/160)* status: all files reviewed, 4 unresolved discussions (waiting on @cottsay)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/160#-NEuvd9Z93loVNUuoAVP:-NEuvd9Z93loVNUuoAVQ:b-ld72ie) (no related file):*
Above workflow testing showed that current CI testing is insufficient.

Can you ensure CI fails as I experienced it, at least for tarball provisioning, then fix it?
I assume that removing hack from Dockerfile should fix this.

___
___
*[`drake_ros_core/CMakeLists.txt` line 81 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/160#-NEuv_6A96fHXPGYx-JW:-NEuv_6A96fHXPGYx-JX:bzhfbyj) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1d753c1408c8c5d63db849274ccf3a08796309f7/drake_ros_core/CMakeLists.txt#L81)):*
> ```CMake
> set(_python_code
>   "import sysconfig"
>   "print(sysconfig.get_path('purelib', vars={'base': '${DRAKE_INSTALL_PREFIX}'}))"
> ```

Per above workflow testing, this is incorrect. I'm not exactly sure what correct solution is.

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/160)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @cottsay)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/160#-NFPT6yo2rjdl7I71RBf:-NFPT6yp3RskG63dOpgr:b-ubr7gx) (no related file):*
See proposal in https://github.com/RobotLocomotion/drake/issues/18150#issuecomment-1293660225

@cottsay Would you be up for PR'ing that change to Drake, and then we leverage that here?

I am assuming that CI failures may be due to nuance with aligning PYTHON Path.
However, if this setup works, please let me know, and we can defer upstream Drake fix.

___

**Comment by cottsay** [comment]
> I am assuming that CI failures may be due to nuance with aligning PYTHON Path.

Long story short, some major Linux distros got upset about pip overwriting system packages and decided to patch Python's `sysconfig` module to inject `local` into the paths reported therein. Unfortunately, the patches don't seem to care if you're trying to get the paths for an alternate (non-/usr) root, and just blindly inject `local` anyway. That's why this is breaking .

The patch landed in Fedora 36 and Ubuntu Jammy, which is why only Jammy builds are failing here. The whole thing is a mess. The backlash in Fedora was strong enough that they re-worked the patch for Fedora 37 to not break this scenario, but Debian Sid hasn't changed yet so I don't imagine we'll see a better hack in Ubuntu any time soon.

We're dealing with this problem in both Ament and colcon right now, and the way the Ubuntu hack was structured, it changes the behavior when you install setuptools using pip vs using the system package. Again, the whole thing is a mess.

I don't think I'll have a great solution here any time soon, so we should probably move forward with a Drake-specific fix.

**Comment by EricCousineau-TRI** [comment]
Ah, nuts! But yeah, let's do the Drake fix. Would you be up for submitting the Drake patch?

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/160)* status: all files reviewed, 2 unresolved discussions (waiting on @cottsay and @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/160#-NEusm0e5rDla-Q3ps06:-NFktWxz9B2WMSWlV8UK:b-nly1n9) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can we now remove `PYTHONPATH` hack from Dockerfile and other workflows?
</blockquote></details>

I  was wrong here; I thought we had control over the Dockerfile in this repo.
I now see that it's part of Drake's docker image.

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/160#-NEusaz11yeSUr6a4Tdz:-NFkthBh3rsVTFzxdPWs:b-fcw5vh) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

It did not work as I expected in that PR; however, I can also reproduce using purely this PR.

On commit 1d753c1:
```
$ cd ros_ws
$ source /opt/ros/humble/setup.bash
$ colcon build --packages-up-to drake_ros_core
$ colcon test --packages-up-to drake_ros_core --event-handlers=console_cohesion+ --ctest-args -R test_pub_sub_py
...
5: ERROR ../.. - ModuleNotFoundError: No module named 'pydrake'
...
```

Please note that I assume `colcon test`leverages workspaces `setup.sh`, thus the ament hooks should implicitly be part of test env.

Looking at just the workspace env:
```
$ bash-isolate
$ source ./install/setup.sh
$ echo $PYTHONPATH | sed 's#:#\n#g'| grep /opt/drake
/opt/drake/local/lib/python3.10/dist-packages
# Wrong

$ [[ -d /opt/drake/lib/python3.10/site-packages ]] && echo Correct
Correct
```
</blockquote></details>

Testing again...

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/160)* status: all files reviewed, 2 unresolved discussions (waiting on @cottsay)

___
*[`drake_ros_core/CMakeLists.txt` line 78 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/160#-NFktrqFEOoVL2G1j9eE:-NFktrqG6qNDcjUoFath:bhjlo1j) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e799dd97cf91ddc197d2438c4804d308c683096d/drake_ros_core/CMakeLists.txt#L78)):*
> ```CMake
> ### Python module path environment hook for pydrake
> set(
>   AMENT_CMAKE_ENVIRONMENT_HOOKS_DESC_pydrake_pythonpath
> ```

BTW Sorry for not catching this above, but this seems redundant.

Can I ask why we have to declare the intent of this environment variable twice, once in CMake and once in bash template?

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
:lgtm_strong: 
Will go ahead and merge, but would still like to know why ament env hooks seem so redundant.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/160#-:-NFkvmmi3nxVQQ1ns1xl:b-ul493l)* status: all files reviewed, 2 unresolved discussions (waiting on @cottsay and @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/160#-NEusaz11yeSUr6a4Tdz:-NFkvkXy2q3jG9aqXqGB:b-6v6nph) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Testing again...
</blockquote></details>

OK Confirmed via local testing, thanks!

___

**Review by EricCousineau-TRI — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/160)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cottsay)

**Pull request merged**
