### PR TITLE
Fix calculated name of ros C/C++ header files

### PR DESCRIPTION
**Pull request by sloretz**
This makes the lower case and underscore insertion logic match [`rosidl_cmake.convert_camel_case_to_lower_case_underscore.`](https://github.com/ros2/rosidl/blob/7a362b4ae12d0120238908677b9aa91ecccf024b/rosidl_cmake/rosidl_cmake/__init__.py#L27-L34).

This fixes a build error complaining about a file not being generated while building [this message](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/master/schunk_wsg_driver/msg/WSGState.msg). The existing logic predicts the file will be `w_s_g_state__type_support.cpp` when it's actually `wsg_state__type_support.cpp`.

Manual testing:

```python3
def foo(basename):
    basename_build = []
    alphabet = "abcdefghijklmnopqrstuvwxyz"
    numbers = "0123456789"
    for i in range(len(basename)):
        insert_underscore = False
        if basename[i] in alphabet.upper():
            # insert an underscore before any upper case letter
            # which is not followed by another upper case letter
            if i > 0 and i + 1 < len(basename):
                if basename[i+1] not in alphabet.upper():
                    insert_underscore = True
            # insert an underscore before any upper case letter
            # which is preseded by a lower case letter or number
            if i - 1 >= 0:
                if basename[i - 1] in numbers + alphabet.lower():
                    insert_underscore = True
        if insert_underscore:
            basename_build.append('_')
        basename_build.append(basename[i].lower())

    print("".join(basename_build))

foo('WSGState')
foo('PointCloud2')
foo('Header')
```

```console
$ python3 /tmp/test.py 
wsg_state
point_cloud2
header
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/86)

### CODE REVIEW

**Review by sloretz — COMMENTED** [review]
+@ericcousineau-tri  for review please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/86#-:-N31EBPQ8tu9zAxHFCZL:btagvl9)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm:, thank you for the manual testing! Just a nit on adding testing.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/86#-:-N32X1lr9kb_t385whmg:b-9p85vl)* status: all files reviewed, 1 unresolved discussion (waiting on @sloretz)

___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 151 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/86#-N32be146s-OfqOAmShL:-N32be146s-OfqOAmShM:bemh97m) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8c368432768750ba0fafd2eae2d168174a95ba69/bazel_ros2_rules/ros2/rosidl.bzl#L151)):*
> ```Starlark
>     basename, _, ext = base.rpartition(".")
> 
>     # Logic must match rosidl_cmake.convert_camel_case_to_lower_case_underscore
> ```

nit This code is rather complex.

Can you add a test of some form or fashion?
I've briefly tried out two options here for Starlark macro testing:
https://github.com/EricCousineau-TRI/repro/tree/134fb56/bazel/starlark_testing

If using "hacky" approach, consider adding `run_rosidl_macro_tests()` here.
If using `unittest.bzl` (formal) approach, you may want to put this macro in a separate, but private, starlark file, e.g. `_helpers.bzl`, and make the function public. (This way, Anzu or other repos don't have to depend on all of `bazel_skylib`)

**Review by EricCousineau-TRI — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/86)* status: all files reviewed, 1 unresolved discussion (waiting on @sloretz)

___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 151 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/86#-N32be146s-OfqOAmShL:-N32cICqCGjYHNsyc0QN:bs3co0t) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8c368432768750ba0fafd2eae2d168174a95ba69/bazel_ros2_rules/ros2/rosidl.bzl#L151)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This code is rather complex.

Can you add a test of some form or fashion?
I've briefly tried out two options here for Starlark macro testing:
https://github.com/EricCousineau-TRI/repro/tree/134fb56/bazel/starlark_testing

If using "hacky" approach, consider adding `run_rosidl_macro_tests()` here.
If using `unittest.bzl` (formal) approach, you may want to put this macro in a separate, but private, starlark file, e.g. `_helpers.bzl`, and make the function public. (This way, Anzu or other repos don't have to depend on all of `bazel_skylib`)
</blockquote></details>

to clarify "add a test" => "automate the test cases you listed above"?

**Review by EricCousineau-TRI — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/86)* status: all files reviewed, 2 unresolved discussions (waiting on @sloretz)

___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 151 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/86#-N32cT953jhQ77A1C-uT:-N32cT960qYaipGB6Gjb:bgl4p49) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8c368432768750ba0fafd2eae2d168174a95ba69/bazel_ros2_rules/ros2/rosidl.bzl#L151)):*
> ```Starlark
>     basename, _, ext = base.rpartition(".")
> 
>     # Logic must match rosidl_cmake.convert_camel_case_to_lower_case_underscore
> ```

nit Can you add reference to the upstream rosidl Python code here?
https://github.com/ros2/rosidl/blob/7a362b4/rosidl_cmake/rosidl_cmake/__init__.py#L27-L34

**Review by EricCousineau-TRI — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/86)* status: all files reviewed, 2 unresolved discussions (waiting on @sloretz)

___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 151 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/86#-N32cT953jhQ77A1C-uT:-N32c_sN1dndSF4QWt4t:b-datq1h) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8c368432768750ba0fafd2eae2d168174a95ba69/bazel_ros2_rules/ros2/rosidl.bzl#L151)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you add reference to the upstream rosidl Python code here?
https://github.com/ros2/rosidl/blob/7a362b4/rosidl_cmake/rosidl_cmake/__init__.py#L27-L34
</blockquote></details>

sorry - permalink - you already had a reference

**Review by EricCousineau-TRI — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/86)* status: all files reviewed, 2 unresolved discussions (waiting on @sloretz)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/86#-N32csYk38qAiyDg0doQ):*
BTW I like the term "calculation" better than "predicted".

"predicted" makes it sound mysterious / like it may not fully be unknowable :sweat_smile:

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/86)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 151 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/86#-N32be146s-OfqOAmShL:-N3vBQjp5xy2yb3t0QOO:b-wj81db) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8c368432768750ba0fafd2eae2d168174a95ba69/bazel_ros2_rules/ros2/rosidl.bzl#L151)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

to clarify "add a test" => "automate the test cases you listed above"?
</blockquote></details>

364c62018d227d249f65e0e031dfeb161ec93185 adds a test with the non-formal approach. I created test cases for all the interface files in my local `ros2` workspace. That uncovered a bug caused by me implementing the function based on the comments instead of the code, which has also been fixed in the same commit. https://github.com/ros2/rosidl/pull/683 fixes the comment upstream.
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 151 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/86#-N32cT953jhQ77A1C-uT:-N3vB_bk4P1FDrFv12Hx:b-dvg9wv) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8c368432768750ba0fafd2eae2d168174a95ba69/bazel_ros2_rules/ros2/rosidl.bzl#L151)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

sorry - permalink - you already had a reference
</blockquote></details>

364c62018d227d249f65e0e031dfeb161ec93185 adds a permanent link

**Review by EricCousineau-TRI — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/86)* status: all files reviewed, 2 unresolved discussions (waiting on @sloretz)

___
*[`bazel_ros2_rules/ros2/_calculate_rosidl_capitalization.bzl` line 30 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/86#-N3yqQ1e4z6p0wEuoG22:-N3yqQ1e4z6p0wEuoG23:b-5rm5dl) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/d9635c2fd3e3eb537b0ff761413784fa550603d9/bazel_ros2_rules/ros2/_calculate_rosidl_capitalization.bzl#L30)):*
> ```Starlark
> 
> 
> def run_calculate_rosidl_capitalization_tests():
> ```

BTW I think this testing would still be valuable if you reduced to like the first 10 or 15 cases.
___
*[`bazel_ros2_rules/ros2/BUILD.bazel` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/86#-N3yqdt-DsFaCnjp2STP:-N3yqdt-DsFaCnjp2STQ:b-7j3gnw) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/d9635c2fd3e3eb537b0ff761413784fa550603d9/bazel_ros2_rules/ros2/BUILD.bazel#L1)):*
> ```Starlark
> # Empty build file to mark package boundaries.
> ```

nit This is no longer accurate. Consider removing.
___
*[`bazel_ros2_rules/ros2/BUILD.bazel` line 4 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/86#-N3yqbl7-_N_ntkHObjr:-N3yqbl8ACiwrVodbIeV:b-7n9yu0) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/d9635c2fd3e3eb537b0ff761413784fa550603d9/bazel_ros2_rules/ros2/BUILD.bazel#L4)):*
> ```Starlark
> 
> load(
> 	":_calculate_rosidl_capitalization.bzl",
> ```

nit Should use spaces, not tabs.

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/86)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`bazel_ros2_rules/ros2/BUILD.bazel` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/86#-N3yqdt-DsFaCnjp2STP:-N49MmToCsRas31_sjI2:bbnswt6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/d9635c2fd3e3eb537b0ff761413784fa550603d9/bazel_ros2_rules/ros2/BUILD.bazel#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This is no longer accurate. Consider removing.
</blockquote></details>

Removed in https://github.com/RobotLocomotion/drake-ros/pull/86/commits/06909c41484ff34bdfb2090956b7ae6d34959053
___
*[`bazel_ros2_rules/ros2/BUILD.bazel` line 4 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/86#-N3yqbl7-_N_ntkHObjr:-N49MiQr3PAEIBAWCB0Z:bwuhyj4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/d9635c2fd3e3eb537b0ff761413784fa550603d9/bazel_ros2_rules/ros2/BUILD.bazel#L4)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Should use spaces, not tabs.
</blockquote></details>

Tabs to spaces in 0f78722

**Review by EricCousineau-TRI — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/86)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

**Pull request merged**
