### PR TITLE
[ci] Update github caching to be more similar to drake-blender

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Using suggestions from #247 / drake-blender

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/295)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
FYI @IanTheEngineer @calderpg-tri @jwnimmer-tri
I don't expect this to pass this first time, so will rerun a few times. Other bazel drake-ros CI jobs fail at around 90m

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/295)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/295#-Nbz51ZW8kVZUWHQPUeL:-NbzS6R19qvgoy18erqQ:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Ah, I need to use separate `/save` action + `if: always()` to ensure we save the cache on failure.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/295#-NbzS6voCMAzB_I3xhJ3:-NbzS6voCMAzB_I3xhJ4:b-yj08bo) (no related file):*
Working: Should confirm latest job saves cache, confirm cache appears under https://github.com/RobotLocomotion/drake-ros/actions/caches, and then confirm that re-running the job triggers a cache hit.

At the risk of cache poisoning, I may let caching from `main` use any caching as well, rather than the `drake-blender` approach of only letting `main` use caching from `main` builds.

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/295)* status: 0 of 3 files reviewed, 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/295#-NbzUlPu1CxNFpTbCOrL:-NbzUlPv2ORXHPP1JWXo:b-epvi1h) (no related file):*
Working: It is unclear if `drake_ros` and `drake_ros_examples` are sharing build cache for Drake.

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/295)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/295#-NbzS6voCMAzB_I3xhJ3:-Nc-BA-d5-5G_Xqf1W9H:bgyeguz) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Should confirm latest job saves cache, confirm cache appears under https://github.com/RobotLocomotion/drake-ros/actions/caches, and then confirm that re-running the job triggers a cache hit.

At the risk of cache poisoning, I may let caching from `main` use any caching as well, rather than the `drake-blender` approach of only letting `main` use caching from `main` builds.
</blockquote></details>

Cache saving failed:
https://github.com/RobotLocomotion/drake-ros/actions/runs/5881198700/job/15949178918?pr=295

```
Run actions/cache/save@v3
  with:
    path: ~/.cache/bazel_ci
    key: bazel_ci-refs/pull/295/merge-452-1
    enableCrossOsArchive: false
  env:
    LANG: en_US.UTF-8
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/drake-ros/drake-ros --files-from manifest.txt --use-compress-program zstdmt
zstd: error 70 : Write error : cannot write block : No space left on device 
/usr/bin/tar: cache.tzst: Wrote only 4096 of 10240 bytes
/usr/bin/tar: Child returned status 70
/usr/bin/tar: Error is not recoverable: exiting now
Warning: Failed to save: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 2
Warning: Cache save failed.
```

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/295#-NbzUlPu1CxNFpTbCOrL:-Nc-BL4x8wcs7i_A1Gns:b-9v8b4k) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: It is unclear if `drake_ros` and `drake_ros_examples` are sharing build cache for Drake.
</blockquote></details>

I do not believe they are :facepalm: 
https://github.com/RobotLocomotion/drake-ros/actions/runs/5881198700/job/15949178918?pr=295

`drake_ros`:
```
Run bazel build //...
...
INFO: Reading rc options for 'build' from /home/runner/work/drake-ros/drake-ros/.github/ci.bazelrc:
  'build' options: --repository_cache /home/runner/.cache/bazel_ci/bazel_externals --disk_cache /home/runner/.cache/bazel_ci/bazel_local_disk
```

`drake_ros_example`:
```
Run bazel build //...
  bazel build //...
  shell: /usr/bin/bash -e {0}
  env:
    LANG: en_US.UTF-8
...
Loading: 2 packages loaded
...
```

___

**Comment by EricCousineau-TRI** [comment]
CI keeps seem to be dying here, and I've timed out on my attempts here.
I will split out the fix for `drake_ros_examples` caching and merge that.

@IanTheEngineer @calderpg-tri Can I ask y'all to pick up here / delegate for ensuring we can use Bazel CI caching correctly?

**Review by adityapande-1995 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/295)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`.github/workflows/bazelized.yml` line 68 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ros/295#-NeoTq0Y7iuvhMFUZtJ6:-NeoTq0Y7iuvhMFUZtJ7:b-2fj3bd) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/678e1622d13edaf3c883ac24a38198c0a18af60a/.github/workflows/bazelized.yml#L68)):*
> ```YAML
>         working-directory: ros2_example_bazel_installed
>       - name: Test Bazel workspace (ros2_example_installed)
>         run: bazel test //... @ros2//...
> ```

In https://github.com/RobotLocomotion/drake-blender/pull/7/files, there is a linking step just before we run test : 
```
run: |
  ln -s .github/ci.bazelrc user.bazelrc 
  ./bazel test //...
```

Should we have that here ? 




EDIT : Nevermind, found the line, ignore this comment

**Review by adityapande-1995 — COMMENTED** [review]
Looks good with ref to https://github.com/RobotLocomotion/drake-blender/pull/7 ! Not sure why the first CI job keeps dying here. Could you clarify what the issue with ``drake_ros_examples`` is ? 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/295#-:-NeoWJnv47ZovxYzEzYZ:bz9b1fb)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/295)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @adityapande-1995)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/295#-NbzS6voCMAzB_I3xhJ3:-NezToMvCbU23x10oUBp:b9oo8cs) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Cache saving failed:
https://github.com/RobotLocomotion/drake-ros/actions/runs/5881198700/job/15949178918?pr=295

```
Run actions/cache/save@v3
  with:
    path: ~/.cache/bazel_ci
    key: bazel_ci-refs/pull/295/merge-452-1
    enableCrossOsArchive: false
  env:
    LANG: en_US.UTF-8
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/drake-ros/drake-ros --files-from manifest.txt --use-compress-program zstdmt
zstd: error 70 : Write error : cannot write block : No space left on device 
/usr/bin/tar: cache.tzst: Wrote only 4096 of 10240 bytes
/usr/bin/tar: Child returned status 70
/usr/bin/tar: Error is not recoverable: exiting now
Warning: Failed to save: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 2
Warning: Cache save failed.
```
</blockquote></details>

Cache save failed again, but maybe it'd work w/ `bazel clean`

___

**Review by EricCousineau-TRI — COMMENTED** [review]
FTR, we had met on Thursday - the primary issue was the cache not saving, which is now fixed with the post-run `bazel clean` so we can construct the cache archive.

Gonna go ahead and merge forward, and we include smaller fixes (e.g. #297 etc)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/295#-:-NfC3mYh7IVgtnsgU4AR:bg7quew)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @adityapande-1995)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/295#-NbzS6voCMAzB_I3xhJ3:-NfC3iH90VaEWDFNUR2d:b-gx2g5e) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Cache save failed again, but maybe it'd work w/ `bazel clean`
</blockquote></details>

OK Fixed per Aditya's fix to do `bazel clean` to save on space - thanks!

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/295#-NbzUlPu1CxNFpTbCOrL:-NfC3dT0BfuH4Nmy5o4U:bqdazrw) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I do not believe they are :facepalm: 
https://github.com/RobotLocomotion/drake-ros/actions/runs/5881198700/job/15949178918?pr=295

`drake_ros`:
```
Run bazel build //...
...
INFO: Reading rc options for 'build' from /home/runner/work/drake-ros/drake-ros/.github/ci.bazelrc:
  'build' options: --repository_cache /home/runner/.cache/bazel_ci/bazel_externals --disk_cache /home/runner/.cache/bazel_ci/bazel_local_disk
```

`drake_ros_example`:
```
Run bazel build //...
  bazel build //...
  shell: /usr/bin/bash -e {0}
  env:
    LANG: en_US.UTF-8
...
Loading: 2 packages loaded
...
```
</blockquote></details>

OK Delegated to #297.

___
___
*[`.github/workflows/bazelized.yml` line 68 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ros/295#-NeoTq0Y7iuvhMFUZtJ6:-NfC393p9Iwg4eO55pFE:b-r4jwww) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/678e1622d13edaf3c883ac24a38198c0a18af60a/.github/workflows/bazelized.yml#L68)):*
<details><summary><i>Previously, adityapande-1995 (Aditya Pande) wrote…</i></summary><blockquote>

In https://github.com/RobotLocomotion/drake-blender/pull/7/files, there is a linking step just before we run test : 
```
run: |
  ln -s .github/ci.bazelrc user.bazelrc 
  ./bazel test //...
```

Should we have that here ?
</blockquote></details>

OK Yup, done on L43 and 46 - albeit a tad hard to read.

**Pull request merged**
