### PR TITLE
Filter invalid labels before passing to templates

### LINKED ISSUE #60: `bazel build @ros2//:rviz_rviz` is misconfigured w/ amdgpu setup?
@calderpg-tri ran into this:
```sh
$ bazel build @ros2//:rviz2_rviz2
ERROR: {bazel_cache}/external/ros2/BUILD.bazel:551:11: @ros2//:rviz_ogre_vendor_cc: invalid label '/opt/amdgpu/lib/x86_64-linux-gnu/libGL.so.1' in element 24 of attribute 'srcs' in 'cc_library' rule: invalid target name '/opt/amdgpu/lib/x86_64-linux-gnu/libGL.so.1': target names may not start with '/'
ERROR: {bazel_cache}/external/ros2/BUILD.bazel:551:11: @ros2//:rviz_ogre_vendor_cc: invalid label '/opt/amdgpu/lib/x86_64-linux-gnu/libGL.so.1' in element 25 of attribute 'data' in 'cc_library' rule: invalid target name '/opt/amdgpu/lib/x86_64-linux-gnu/libGL.so.1': target names may not start with '/'
ERROR: error loading package '@ros2//': Package '' contains errors
...
```

for more info, see #59

### PR DESCRIPTION
**Pull request by sloretz**
Alternative to #61 
Fixes #60

This takes a different approach from #61 because it wasn't enough for my workflow with apptainer/singularity.

The problem described in #60 is things that [aren't lexically valid bazel labels](https://docs.bazel.build/versions/main/build-ref.html#lexi), like absolute paths to system libraries, are put into bazel rules that only accept labels. That causes the whole generated `BUILD.bazel` file to be invalid.

#60 expands where system libraries are search to include directories given in `/etc/ld.so.conf.d`. That way they [get filtered from the list of libraries a target depends on](https://github.com/RobotLocomotion/drake-ros/blob/7ac6b2fd8e22f293313a608545c0ceda75e554b4/bazel_ros2_rules/ros2/ros2bzl/scraping/ament_cmake.py#L70). System libraries are listed as absolute paths, absolute paths aren't valid bazel labels, so filtering them stops absolute paths from ending up in the fields that accept only bazel labels. I'm not sure if the system library filtering is necessary for anything other than working around this issue.

That doesn't work when using the `--nv` option to Apptainer/singularity. It sets `LD_LIBRARY_PATH` to include `/.singularity.d/libs` which contains graphics shared libraries from the host. The scraping code assumes anything in `LD_LIBRARY_PATH` is not a system library. That's not easy to work around because the ROS workspace uses `LD_LIBRARY_PATH` too.

This PR addresses the problem when the templates are expanded. It silently skips anything that's not a valid bazel label. Those thinks can't be in the `BUILD.bazel`, but they might not needed and skipping them allows the build to continue.

If this PR is merged, it might be that `is_system_library()` can be removed altogether, but I haven't tested that yet.

@IanTheEngineer & @EricCousineau-TRI mind taking a look?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/65)

### CODE REVIEW

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/65)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @IanTheEngineer and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/65#-N-ck_l38IEZry7Z6gL9:-N-ck_l38IEZry7Z6gLA:bsbzvz0) (no related file):*
I'm concerned about filtering will allow blatant errors to creep in (e.g. a bug in new scraping code produces inadvertently wrong label, and it silently fails).
I may need some time to get full context, but I do want to make sure I understand this before admit things like this.

> That doesn't work when using the `--nv`

Is there a small modification to #59, along with a specific Bazel command, that I can use to reproduce this error?

---

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/65)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/65#-N-ck_l38IEZry7Z6gL9:-N-d6qZ_9YmuwTav4fDH:b-503zjp) (no related file):*
> Is there a small modification to #59, along with a specific Bazel command, that I can use to reproduce this error?

<details><summary>Add rviz2 to WORKSPACE</summary>

```diff
diff --git a/ros2_example_bazel_installed/WORKSPACE b/ros2_example_bazel_installed/WORKSPACE
index 5292ad7..843b3ac 100644
--- a/ros2_example_bazel_installed/WORKSPACE
+++ b/ros2_example_bazel_installed/WORKSPACE
@@ -24,6 +24,7 @@ ROS2_PACKAGES = [
     "rclcpp_action",
     "rclcpp",
     "rclpy",
+    "rviz2",
     # RMW implementations
     "rmw_cyclonedds_cpp",
     "rmw_fastrtps_cpp",
```
</details>

<details><summary>repro.def</summary>

```def
Bootstrap: docker
From: robotlocomotion/drake:focal

%post
  export DEBIAN_FRONTEND=noninteractive

  apt-get update
  apt-get install -y \
    git \
    curl \
    locales \
    gnupg2 \
    lsb-release \
    software-properties-common \
    build-essential \
    tzdata

  locale-gen en_US en_US.UTF-8
  update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
  export LANG=en_US.UTF-8

  apt-add-repository universe
  apt-add-repository "deb http://security.ubuntu.com/ubuntu `lsb_release -cs`-security main restricted universe multiverse"

  curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -

  echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros1-stable.list
  echo "deb http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2.list

  apt-get update
  apt-get install -y python3-rosdep

  rosdep init

  yes | /drake-ros/ros2_example_bazel_installed/setup/install_prereqs.sh

  # Mess with /etc/ld.so.conf.d
  echo /opt/amdgpu-pro/lib/x86_64-linux-gnu/ > /etc/ld.so.conf.d/amdgpu-pro.conf
  mkdir -p /opt/amdgpu-pro/lib/x86_64-linux-gnu/
  # Put a lib in there that ROS 2 libs use
  cp  /usr/lib/x86_64-linux-gnu/libz.so.1 /opt/amdgpu-pro/lib/x86_64-linux-gnu/
  ldconfig

%environment
  export LANG=en_US.UTF-8
  export ROS_PYTHON_VERSION=3
```
</details>

<details><summary>Add --nv to run_on_host.sh</summary>

```bash
#!/bin/bash
set -eux

cd $(dirname ${BASH_SOURCE})

if [[ ! -f ./repro.sif ]]; then
    singularity build --fakeroot repro.sif repro.def
fi

mkdir -p bazel_cache

if [[ ! -f ./overlay.img ]]; then
    dd if=/dev/zero of=overlay.img bs=1M count=500
    mkfs.ext4 overlay.img
fi

# TODO(eric): How to make sandbox persistent?
# I replaced `--writeable` with `--overlay ... --bind ...`, but eww.
singularity exec \
    --fakeroot \
    --overlay ./overlay.img --bind ./bazel_cache:/root/.cache/bazel \
    --no-home --containall \
    --bind ..:/drake-ros \
    --pwd /drake-ros/ros2_example_bazel_installed \
    --nv \
    repro.sif \
    bazel build @ros2//:builtin_interfaces_cc

    # bazel build //ros2_example_apps:oracle_cc
```
</details>

Results in this error

```
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (597) bind mounts
Starting local Bazel server and connecting to it...
ERROR: /root/.cache/bazel/_bazel_root/0e056d0947872c4fa3e2ab8b92439151/external/ros2/BUILD.bazel:551:11: @ros2//:rviz_ogre_vendor_cc: invalid label '/.singularity.d/libs/libGL.so.1' in element 24 of attribute 'srcs' in 'cc_library' rule: invalid target name '/.singularity.d/libs/libGL.so.1': target names may not start with '/'
ERROR: /root/.cache/bazel/_bazel_root/0e056d0947872c4fa3e2ab8b92439151/external/ros2/BUILD.bazel:551:11: @ros2//:rviz_ogre_vendor_cc: invalid label '/.singularity.d/libs/libGL.so.1' in element 25 of attribute 'data' in 'cc_library' rule: invalid target name '/.singularity.d/libs/libGL.so.1': target names may not start with '/'
ERROR: error loading package '@ros2//': Package '' contains errors
INFO: Elapsed time: 89.461s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
INFO:    Cleaning up image...
```

---

**Comment by sloretz** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/65#-N-ck_l38IEZry7Z6gL9:-N-d8bqz7PP-FtokZhFe:b-ba0h8c) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

> Is there a small modification to #59, along with a specific Bazel command, that I can use to reproduce this error?

<details><summary>Add rviz2 to WORKSPACE</summary>

```diff
diff --git a/ros2_example_bazel_installed/WORKSPACE b/ros2_example_bazel_installed/WORKSPACE
index 5292ad7..843b3ac 100644
--- a/ros2_example_bazel_installed/WORKSPACE
+++ b/ros2_example_bazel_installed/WORKSPACE
@@ -24,6 +24,7 @@ ROS2_PACKAGES = [
     "rclcpp_action",
     "rclcpp",
     "rclpy",
+    "rviz2",
     # RMW implementations
     "rmw_cyclonedds_cpp",
     "rmw_fastrtps_cpp",
```
</details>

<details><summary>repro.def</summary>

```def
Bootstrap: docker
From: robotlocomotion/drake:focal

%post
  export DEBIAN_FRONTEND=noninteractive

  apt-get update
  apt-get install -y \
    git \
    curl \
    locales \
    gnupg2 \
    lsb-release \
    software-properties-common \
    build-essential \
    tzdata

  locale-gen en_US en_US.UTF-8
  update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
  export LANG=en_US.UTF-8

  apt-add-repository universe
  apt-add-repository "deb http://security.ubuntu.com/ubuntu `lsb_release -cs`-security main restricted universe multiverse"

  curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -

  echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros1-stable.list
  echo "deb http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2.list

  apt-get update
  apt-get install -y python3-rosdep

  rosdep init

  yes | /drake-ros/ros2_example_bazel_installed/setup/install_prereqs.sh

  # Mess with /etc/ld.so.conf.d
  echo /opt/amdgpu-pro/lib/x86_64-linux-gnu/ > /etc/ld.so.conf.d/amdgpu-pro.conf
  mkdir -p /opt/amdgpu-pro/lib/x86_64-linux-gnu/
  # Put a lib in there that ROS 2 libs use
  cp  /usr/lib/x86_64-linux-gnu/libz.so.1 /opt/amdgpu-pro/lib/x86_64-linux-gnu/
  ldconfig

%environment
  export LANG=en_US.UTF-8
  export ROS_PYTHON_VERSION=3
```
</details>

<details><summary>Add --nv to run_on_host.sh</summary>

```bash
#!/bin/bash
set -eux

cd $(dirname ${BASH_SOURCE})

if [[ ! -f ./repro.sif ]]; then
    singularity build --fakeroot repro.sif repro.def
fi

mkdir -p bazel_cache

if [[ ! -f ./overlay.img ]]; then
    dd if=/dev/zero of=overlay.img bs=1M count=500
    mkfs.ext4 overlay.img
fi

# TODO(eric): How to make sandbox persistent?
# I replaced `--writeable` with `--overlay ... --bind ...`, but eww.
singularity exec \
    --fakeroot \
    --overlay ./overlay.img --bind ./bazel_cache:/root/.cache/bazel \
    --no-home --containall \
    --bind ..:/drake-ros \
    --pwd /drake-ros/ros2_example_bazel_installed \
    --nv \
    repro.sif \
    bazel build @ros2//:builtin_interfaces_cc

    # bazel build //ros2_example_apps:oracle_cc
```
</details>

Results in this error

```
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (597) bind mounts
Starting local Bazel server and connecting to it...
ERROR: /root/.cache/bazel/_bazel_root/0e056d0947872c4fa3e2ab8b92439151/external/ros2/BUILD.bazel:551:11: @ros2//:rviz_ogre_vendor_cc: invalid label '/.singularity.d/libs/libGL.so.1' in element 24 of attribute 'srcs' in 'cc_library' rule: invalid target name '/.singularity.d/libs/libGL.so.1': target names may not start with '/'
ERROR: /root/.cache/bazel/_bazel_root/0e056d0947872c4fa3e2ab8b92439151/external/ros2/BUILD.bazel:551:11: @ros2//:rviz_ogre_vendor_cc: invalid label '/.singularity.d/libs/libGL.so.1' in element 25 of attribute 'data' in 'cc_library' rule: invalid target name '/.singularity.d/libs/libGL.so.1': target names may not start with '/'
ERROR: error loading package '@ros2//': Package '' contains errors
INFO: Elapsed time: 89.461s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
INFO:    Cleaning up image...
```
</blockquote></details>

That error message is while using the branch from #61 on d8ff92623ed9e39d916b53ce18cde2e6bbbf345e

---

**Comment by EricCousineau-TRI** [comment]
See https://github.com/RobotLocomotion/drake-ros/pull/59#issuecomment-1100333060 - unable to repro :crying_cat_face:

**Comment by EricCousineau-TRI** [comment]
094344c is more along what we should do, unless there's a more general (but still very explicit) way to do this.

Please note #66 - this change alone may not trigger rebuilding a workspace.

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/65)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @IanTheEngineer and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/65#-N-ck_l38IEZry7Z6gL9:-N-j0iRP1ax-dKHULh0A:b-le8fd0) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

That error message is while using the branch from #61 on d8ff92623ed9e39d916b53ce18cde2e6bbbf345e
</blockquote></details>

See counter-proposal above.

---

**Comment by sloretz** [comment]
Closing in favor of #69

**Pull request closed without merging**
