### PR TITLE
Docker build and CI

### PR DESCRIPTION
**Pull request by IanTheEngineer**
Adds docker build, along with a very basic Github Action CI workflow:

- based on prebuilt `ros:${ROS_DISTRO}-ros-base` docker container
  (rolling to start)
- installs Drake and Drake's dependencies
- copies drake-ros source code into the container
- installs source code dependencies
- builds source code
- runs unit tests & reports results

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/13)

### CODE REVIEW

**Review by IanTheEngineer — COMMENTED** [review]
+@sloretz for review please. cc @hidmic for fyi.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/13#-:-MhQ3riHE9QWun4sfcAB:bsq31vt)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @sloretz)

**Review by hidmic — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/13)* status: all files reviewed, 4 unresolved discussions (waiting on @IanTheEngineer and @sloretz)

___
*[-- commits, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/13#-MhQLTPi8tQB--AaaDRI:-MhQLTPj8f0rJlJWQ_YS:b346fy4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3877c765fb2713f863715e86159017a6076c0cc7/-- commits#L1)):*
@iantheengineer is this a changelog? How is it different from the raw commit history?
___
*[README.md, line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/13#-MhQKsqD2Az_lGhnerhz:-MhQKsqD2Az_lGhneri-:b-njlq75) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3877c765fb2713f863715e86159017a6076c0cc7/README.md#L15)):*
> ```Markdown
> 
> ### Interactive Shell in Docker container
> $ docker run -it --user root drake-ros  /bin/bash
> ```

@iantheengineer missing newline
___
*[.github/workflows/ci.yaml, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/13#-MhQL4iNCPgs1Lc2KIsu:-MhQL4iNCPgs1Lc2KIsv:br4diuu) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3877c765fb2713f863715e86159017a6076c0cc7/.github/workflows/ci.yaml#L14)):*
> ```YAML
>         uses: actions/checkout@v2
>       - name: Build and Test drake_ros_core
>         run: docker build -f tools/containers/drake_ros_core.Dockerfile  --build-arg ROS_DISTRO=rolling .
> ```

@iantheengineer meta: I wonder if it wouldn't make more sense to layout both build and test procedures in job steps ran within a container rather than collapsing all in an image build
___
*[tools/containers/drake_ros_core.Dockerfile, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/13#-MhQKbQw8RCe7LRiceLl:-MhQKbQw8RCe7LRiceLm:b-2m3coq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3877c765fb2713f863715e86159017a6076c0cc7/tools/containers/drake_ros_core.Dockerfile#L33)):*
> ```
> # TODO: Determine why test-msgs package needs to be installed manually.
> RUN apt-get update \
>     && apt-get install --no-install-recommends -y ros-${ROS_DISTRO}-test-msgs \
> ```

@iantheengineer hmm, doesn't this suggest `drake_ros_core`'s package.xml needs an update?

**Review by sloretz — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/13)* status: all files reviewed, 4 unresolved discussions (waiting on @IanTheEngineer)

___
*[-- commits, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/13#-MhQLTPi8tQB--AaaDRI:-MhQNHMlCuVu8iX_FWue:b-doku7l) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3877c765fb2713f863715e86159017a6076c0cc7/-- commits#L1)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

@iantheengineer is this a changelog? How is it different from the raw commit history?
</blockquote></details>

It doesn't appear on the Github UI. Maybe this is Revieable's way of checking commit messages?
___
*[tools/containers/drake_ros_core.Dockerfile, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/13#-MhQKbQw8RCe7LRiceLl:-MhQPCUM93Sde3omNZJ9:b-h33o1a) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3877c765fb2713f863715e86159017a6076c0cc7/tools/containers/drake_ros_core.Dockerfile#L33)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

@iantheengineer hmm, doesn't this suggest `drake_ros_core`'s package.xml needs an update?
</blockquote></details>

`drake_ros_core` seems to have `test_msgs` as a `<test_depend>` already https://github.com/RobotLocomotion/drake-ros/blob/70c23a55606a99fd7e41f0b8ff7ba439147c7365/drake_ros_core/package.xml#L20. I wonder why `rosdep install` didn't install it?

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/13)* status: all files reviewed, 4 unresolved discussions (waiting on @IanTheEngineer)

___
*[tools/containers/drake_ros_core.Dockerfile, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/13#-MhQKbQw8RCe7LRiceLl:-MhQTR4lEDH5nZTMHuVA:b9nzitw) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3877c765fb2713f863715e86159017a6076c0cc7/tools/containers/drake_ros_core.Dockerfile#L33)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

`drake_ros_core` seems to have `test_msgs` as a `<test_depend>` already https://github.com/RobotLocomotion/drake-ros/blob/70c23a55606a99fd7e41f0b8ff7ba439147c7365/drake_ros_core/package.xml#L20. I wonder why `rosdep install` didn't install it?
</blockquote></details>

I tried this locally in a clean container, and `ros-rolling-test-msgs` does get installed. It shows up in `--simulate` too. Maybe the `TODO` is out of date?

```console
$ rosdep install --simulate --from-paths src --ignore-src --rosdistro rolling -y
#[apt] Installation commands:
  apt-get install -y ros-rolling-rclcpp
  apt-get install -y ros-rolling-rosidl-runtime-c
  apt-get install -y ros-rolling-rosidl-typesupport-cpp
  apt-get install -y ros-rolling-ament-cmake-ros
  apt-get install -y ros-rolling-ament-cmake-gtest
  apt-get install -y ros-rolling-ament-lint-auto
  apt-get install -y ros-rolling-ament-lint-common
  apt-get install -y ros-rolling-test-msgs
```

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/13)* status: all files reviewed, 4 unresolved discussions (waiting on @IanTheEngineer)

___
*[tools/containers/drake_ros_core.Dockerfile, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/13#-MhQKbQw8RCe7LRiceLl:-MhZwvfW0kshzsqi2xxx:b-qgt3vj) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3877c765fb2713f863715e86159017a6076c0cc7/tools/containers/drake_ros_core.Dockerfile#L33)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I tried this locally in a clean container, and `ros-rolling-test-msgs` does get installed. It shows up in `--simulate` too. Maybe the `TODO` is out of date?

```console
$ rosdep install --simulate --from-paths src --ignore-src --rosdistro rolling -y
#[apt] Installation commands:
  apt-get install -y ros-rolling-rclcpp
  apt-get install -y ros-rolling-rosidl-runtime-c
  apt-get install -y ros-rolling-rosidl-typesupport-cpp
  apt-get install -y ros-rolling-ament-cmake-ros
  apt-get install -y ros-rolling-ament-cmake-gtest
  apt-get install -y ros-rolling-ament-lint-auto
  apt-get install -y ros-rolling-ament-lint-common
  apt-get install -y ros-rolling-test-msgs
```
</blockquote></details>

Removed in PR targeting this branch: https://github.com/RobotLocomotion/drake-ros/pull/18

**Comment by EricCousineau-TRI** [comment]
Per VC, we assume this Dockerfile was originally for CI. Per Shane's point above, will close this for now.

**Pull request closed without merging**
