### PR TITLE
Export ``ROS_DISTRO`` environment variable

### PR DESCRIPTION
**Pull request by adityapande-1995**
Resolves https://github.com/RobotLocomotion/drake-ros/issues/111, by exporting a default value for ``ROS_DISTRO``.

Signed-off-by: Aditya Pande <aditya.pande@openrobotics.org>

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/217)

### CODE REVIEW

**Review by sloretz — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/217)* status: all files reviewed, 1 unresolved discussion (waiting on @adityapande-1995)

___
*[`bazel_ros2_rules/ros2/resources/ros2bzl/scraping/__init__.py` line 102 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/217#-NNxQR8w3LfZWt_rFpDu:-NNxQR8w3LfZWt_rFpDv:bmpbud4) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/fce8de27804f5e83e5c52d7cadc81991b318445e/bazel_ros2_rules/ros2/resources/ros2bzl/scraping/__init__.py#L102)):*
> ```Python
>             'ament_prefix': ament_index_python.get_search_paths(),
>             'library_load': ld_library_path.split(os.path.pathsep),
>             'ros_distro': ros_distro
> ```

nit, I'd recommend putting this at the top level of the dictionary rather than in `paths` since it's not a path.

**Comment by EricCousineau-TRI** [comment]
Closing and re-opening to refresh CI

**Comment by adityapande-1995** [comment]
Is this one ready to be merged ? Rolling CI is failing due to a different reason that this PR.

**Comment by EricCousineau-TRI** [comment]
Let's give it another whirl now that #221 got resolved - I've gone ahead and rebased/squashed.
Thanks!

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm:, thanks!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/217#-:-NP-tCUrEoaMGudKguCk:bpqxd5f)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityapande-1995)

**Review by EricCousineau-TRI — APPROVED** [review]
-@sloretz

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/217#-:-NP-tGz56F4fRr3jTAeU:bnvrtmf)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityapande-1995)

**Comment by EricCousineau-TRI** [comment]
Ah, nuts. I think I messed up authorship. Let me briefly try to fix that.

**Comment by EricCousineau-TRI** [comment]
Hmm...

```sh
$ git log -n 1 --no-decorate
commit ca35a776b45e83cb28113b18b205369ae54b86de
Author: Aditya Pande <aditya.pande@openrobotics.org>
Date:   Fri Feb 10 22:12:58 2023 +0000

    Added ros distro to env variabes

    Removed ros_distro from under paths section
```

Authorship clear, committer not the best.
Will merge forward for now, but hoping there's a clearer way to denote true authorship in the future! (perhaps changing my author locally, or avoiding rebasing in the first place!)

**Comment by EricCousineau-TRI** [comment]
Ah, post-merge authorship OK, I think you just used multiple emails / accounts?

```sh
$ git log main -n 1 --no-decorate
commit bc34b5c59dcafb6040f2896d88536abe7d5f9192
Author: Aditya Pande <aditya050995@gmail.com>
Date:   Thu Feb 23 16:51:55 2023 -0800

    Added ros distro to env variabes (#217)

    Removed ros_distro from under paths section

    Co-authored-by: Aditya Pande <aditya.pande@openrobotics.org>
```

**Comment by adityapande-1995** [comment]
Ahh, I switched to a different machine while the PR was in progress, that had different git configs set up. 🤦

**Pull request merged**
