### PR TITLE
Update Bazelized build to use the latest ROS 2 Rolling underlay archive

### PR DESCRIPTION
**Pull request by cottsay**
The currently targeted archive was built on January 25th. This PR includes the necessary changes to use the purpose-built `drake-ros-underlay` archive, which is re-built weekly.

* Switch bazelized builds to use drake-ros-underlay tarball
* Drop rosidl_typesupport_c__visibility_control.h (dropped upstream in `rosidl_typesupport_c`)
* Update ROS 2 prerequisite rosdep key list (churn for 3 months of development)
* Drop prefix chaining workaround (fixed upstream in ros_buildfarm)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/71)

### CODE REVIEW

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm_strong: with small nit on comment / TODO

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/71#-:-N0WMtdp0OZbHB9jTmCF:bbfgq1e)* status: all files reviewed, 2 unresolved discussions (waiting on @cottsay)

___
*[`bazel_ros2_rules/ros2/defs.bzl` line 205 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/71#-N0WLhG18RkqR2afBPFN:-N0WLhG18RkqR2afBPFO:bfhrwzs) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8e83875cd302d3b62b86c2aa0bfd5264d0d01a4d/bazel_ros2_rules/ros2/defs.bzl#L205)):*
> ```Starlark
>     ),
>     "sha256_url": attr.string(
>         doc = "The URL to fetch the SHA-256 checksum file for the tarball.",
> ```

nit Unclear how this interacts with `sha256`.

Can you add documentation to this describing the interaction? e.g.
```
If you supply sha256, then it must exactly match the value fetched from the URL.
(In general, you may only want to supply one of these.)
```
___
*[`ros2_example_bazel_installed/WORKSPACE` line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/71#-N0WKthU1Es7f6o5HFgL:-N0WKthU1Es7f6o5HFgM:b-1r9tgg) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8e83875cd302d3b62b86c2aa0bfd5264d0d01a4d/ros2_example_bazel_installed/WORKSPACE#L35)):*
> ```Starlark
>     name = "ros2" if not ROS2_DISTRO_PREFIX else "ros2_ignored",
>     include_packages = ROS2_PACKAGES,
>     # TODO(hidmic): mirror this tarball for stability
> ```

nit Per VC, can we change this TODO to be advice to users, and mention release pinning? e.g.

```
# Note: If you want an exact / unchanging version, you will need to mirror the archive
# according to versions you want.
# TODO(hidmic,cottsay): Make release-pinned snapshots of this repository once `drake-ros`
# itself has versions.
```

**Review by cottsay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/71)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

___
*[`bazel_ros2_rules/ros2/defs.bzl` line 205 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/71#-N0WLhG18RkqR2afBPFN:-N0Xs6pR9_Tlx0CwhgPW:b-qrt4bh) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8e83875cd302d3b62b86c2aa0bfd5264d0d01a4d/bazel_ros2_rules/ros2/defs.bzl#L205)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear how this interacts with `sha256`.

Can you add documentation to this describing the interaction? e.g.
```
If you supply sha256, then it must exactly match the value fetched from the URL.
(In general, you may only want to supply one of these.)
```
</blockquote></details>

Sounds reasonable - applied in 9b67e8e, thanks.
___
*[`ros2_example_bazel_installed/WORKSPACE` line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/71#-N0WKthU1Es7f6o5HFgL:-N0XrzRI8MmcjySJn_6U:boca74o) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8e83875cd302d3b62b86c2aa0bfd5264d0d01a4d/ros2_example_bazel_installed/WORKSPACE#L35)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Per VC, can we change this TODO to be advice to users, and mention release pinning? e.g.

```
# Note: If you want an exact / unchanging version, you will need to mirror the archive
# according to versions you want.
# TODO(hidmic,cottsay): Make release-pinned snapshots of this repository once `drake-ros`
# itself has versions.
```
</blockquote></details>

Taken verbatim in 9b67e8e, thanks.

**Review by EricCousineau-TRI — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/71)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cottsay)

___
*[`bazel_ros2_rules/ros2/defs.bzl` line 205 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/71#-N0YLe-d1Q1OH9Xl_2nQ:-N0YLe-d1Q1OH9Xl_2nR:b-lxh8oi) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9b67e8ee112841de7cc066d6ba2857a8d66f119a/bazel_ros2_rules/ros2/defs.bzl#L205)):*
> ```Starlark
>     ),
>     "sha256_url": attr.string(
>         doc = "The URL to fetch the SHA-256 checksum file for the tarball. "
> ```

BTW CI is failing due to implicit string concat:
https://github.com/RobotLocomotion/drake-ros/runs/6166502873?check_suite_focus=true#step:6:8

**Review by EricCousineau-TRI — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/71)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cottsay)

**Pull request merged**
