### PR TITLE
README: Fix typo. Separate CONTRIBUTING doc

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Carved from #170

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/179)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri for review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/179#-:-NEviCKkB4sRkIV5nYmv:b-z97lb3)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

___
*[`README.md` line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/179#-NEviF2h7C5wNgom2VNn:-NEviF2h7C5wNgom2VNo:b-l1w77n) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/22d3d57ff48ca8115adbbceb4f6e68ac34070b85/README.md#L26)):*
> ```Markdown
> This code is prioritized for use within the TRI Dexterous Manipulation Group.
> We do not presently adhere to any stability commitment (e.g., deprecations,
> backports, etc.), so please use this code at your own discretion. (It's still
> ```

FYI Even seeing your suggestion, I still spelled it as the following two before I fixed it :facepalm: 
```
disgretion
disgrecion
```

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/179#-:-NEvmA8S9jvLq8ZWi1mf:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`CONTRIBUTING.md` line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/179#-NEvlwgYDc3LcTzB5rCu:-NEvlwgYDc3LcTzB5rCv:b-74xcy) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/22d3d57ff48ca8115adbbceb4f6e68ac34070b85/CONTRIBUTING.md#L8)):*
> ```Markdown
> guide](https://drake.mit.edu/code_style_guide.html).
> 
> ## Continuous Integration
> ```

nit Choose either "Title Case" or "Sentence case" consistently throughout these headings.



_Suggestion:_
```Markdown
Continuous integration
```
___
*[`CONTRIBUTING.md` line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/179#-NEvlMsY2IltcaN8jMpJ:-NEvlMsZAZ8TRxpk4BpY:be5rppr) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/22d3d57ff48ca8115adbbceb4f6e68ac34070b85/CONTRIBUTING.md#L10)):*
> ```Markdown
> ## Continuous Integration
> 
> This repository uses GitHub Actions to perform CI.
> ```

nit Consider whether you might want a final new section here at the end:



_Code snippet:_
```Markdown
## Terms and conditions

Refer to [LICENSE](./LICENSE) §5.
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/179)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

___
*[`CONTRIBUTING.md` line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/179#-NEvlwgYDc3LcTzB5rCu:-NEw-bup1iV1BWEKAqIc:b-tmchvc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/22d3d57ff48ca8115adbbceb4f6e68ac34070b85/CONTRIBUTING.md#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Choose either "Title Case" or "Sentence case" consistently throughout these headings.
</blockquote></details>

Done, I like "Title Case" a bit more
___
*[`CONTRIBUTING.md` line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/179#-NEvlMsY2IltcaN8jMpJ:-NEw-b5g9yVgqslvy_WE:b-49f9gj) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/22d3d57ff48ca8115adbbceb4f6e68ac34070b85/CONTRIBUTING.md#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Consider whether you might want a final new section here at the end:
</blockquote></details>

Done - considered!

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/179)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Pull request merged**
