### PR TITLE
Add talker/listener example using rmw_isolation

### PR DESCRIPTION
**Pull request by sloretz**
WIP towards #77 - I've implemented a C++ test so far.

+@EricCousineau-TRI for review please

I had to make the `:rmw_isolation_cc` target visible, and I had to set `ROS_HOME`. Maybe `ros_cc_test` should be setting `ROS_HOME` to a temporary directory? The default `~/.ros` isn't writable in the bazel sandbox.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/79)

### CODE REVIEW

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
Looks good thus far!

> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-:-N1BlTAEBrFBaHtLxhUg:b-6qbnx6)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-N1BiwNo003lppaAB52Z:-N1BiwNo003lppaAB52_:btudrw7) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7ff920ddf395779906007af62633dd706de93492/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L83)):*
> ```Starlark
> cc_library(
>     name = "listener_cc",
>     hdrs = ["listener.hh"],
> ```

For consistency, can you rename this from `.hh` to `.h`?
___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-N1BjW_P9lVBE52vGipS:-N1BjW_P9lVBE52vGipT:b-ubg6ls) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7ff920ddf395779906007af62633dd706de93492/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L98)):*
> ```Starlark
>   ],
>   # TODO(sloretz) can this be set inside TEST_TMPDIR?
>   env = {"ROS_HOME": "/tmp/.ros"},
> ```

nit Rather than set this via `env`, can you instead use a `bazel.rc` file?
Example:
https://github.com/RobotLocomotion/drake/blob/1b615ca7612f6d0d4bb5e6bdd9e00b33baf44d32/tools/bazel.rc#L40-L45

Similar to other things, perhaps we just disable it, e.g. `/do_not_read_or_write_to_home`?
Then perhaps the test / `isolate_rmw_by_path` calls?
```
setenv("ROS_HOME", fmt::format("{}/.ros", TEST_TMPDIR));
```
___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-N1Bjvo7EqFiolZYebbp:-N1Bjvo7EqFiolZYebbq:b7l0f4y) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7ff920ddf395779906007af62633dd706de93492/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L98)):*
> ```Starlark
>   ],
>   # TODO(sloretz) can this be set inside TEST_TMPDIR?
>   env = {"ROS_HOME": "/tmp/.ros"},
> ```

Why is this necessary? Why must we admit `ROS_HOME`?
___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-N1Bk5Cy-C5Llc0--bOq:-N1Bk5Cy-C5Llc0--bOr:b-oy09zu) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7ff920ddf395779906007af62633dd706de93492/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L98)):*
> ```Starlark
>   ],
>   # TODO(sloretz) can this be set inside TEST_TMPDIR?
>   env = {"ROS_HOME": "/tmp/.ros"},
> ```

For similar test isolation requirements, can you also ensure you disable 
___
*[`ros2_example_bazel_installed/ros2_example_apps/test/talker_listener.cc` line 29 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-N1BjJ5rBQ9hhoUKdQxA:-N1BjJ5rBQ9hhoUKdQxB:b-4cj4rr) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7ff920ddf395779906007af62633dd706de93492/ros2_example_bazel_installed/ros2_example_apps/test/talker_listener.cc#L29)):*
> ```cpp
>   auto got_message = listener->NextMessage();
> 
>   auto result = 
> ```

nit Trailing whitespace.

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/79)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-N1BiwNo003lppaAB52Z:-N1Eu0rwD-3fnGNQJNPV:b-74t1si) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7ff920ddf395779906007af62633dd706de93492/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L83)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

For consistency, can you rename this from `.hh` to `.h`?
</blockquote></details>

Renamed files in 95e51137471badf8a716e61dd5f34a0d7c9d448e
___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-N1Bjvo7EqFiolZYebbp:-N1ErMCK1ThVZF6OVzt_:b4mfk09) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7ff920ddf395779906007af62633dd706de93492/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L98)):*
`rcl_logging_spdlog` errors if it can't get the logging directory

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //ros2_example_apps:talker_listener_cc_test
-----------------------------------------------------------------------------

>>> [rcutils|error_handling.c:108] rcutils_set_error_state()
This error state is being overwritten:

  'rcutils_expand_user failed, at /tmp/ws/src/rcl_logging_interface/src/logging_dir.c:81'

with this new error message:

  'Failed to get logging directory, at /tmp/ws/src/rcl_logging_spdlog/src/rcl_logging_spdlog.cpp:83'

rcutils_reset_error() should be called after error handling to avoid this.
<<<
[ERROR] [1651681076.334153535] [rclcpp]: rcl context unexpectedly not shutdown during cleanup
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  failed to configure logging: Failed to get logging directory, at /tmp/ws/src/rcl_logging_spdlog/src/rcl_logging_spdlog.cpp:83
```


We could probably use a feature here that disabled trying to write to the filesystem altogether. Maybe an environment var `ROS_READ_ONLY_FILESYSTEM` that disables writing to the filesystem?
___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-N1BjW_P9lVBE52vGipS:-N1EsdiA-PRZ62EZXsUX:b-dlr5xt) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7ff920ddf395779906007af62633dd706de93492/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L98)):*
> /do_not_read_or_write_to_home

We can set it in the `.bazelrc`, but the `rcl_logging_spdlog` needs the folder to exist (cb11bd5dfcfde1051b030988f01c8a138dbc9dfe)

```
test --test_env=ROS_HOME=/do_not_read_or_write_to_home
```

results in

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //ros2_example_apps:talker_listener_cc_test
-----------------------------------------------------------------------------
[ERROR] [1651681365.663113714] [rclcpp]: rcl context unexpectedly not shutdown during cleanup
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  failed to configure logging: Failed to create log directory: /do_not_read_or_write_to_home/log, at /tmp/ws/src/rcl_logging_spdlog/src/rcl_logging_spdlog.cpp:90
```
___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-N1Bk5Cy-C5Llc0--bOq:-N1Eu4ZI-O7YqU1JAFca:b-ykpnkh) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7ff920ddf395779906007af62633dd706de93492/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L98)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

For similar test isolation requirements, can you also ensure you disable 
</blockquote></details>

I think the rest of this comment might have been cut off.
___
*[`ros2_example_bazel_installed/ros2_example_apps/test/talker_listener.cc` line 29 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-N1BjJ5rBQ9hhoUKdQxA:-N1EuV575ktrgEY1idTj:b8oqsp9) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7ff920ddf395779906007af62633dd706de93492/ros2_example_bazel_installed/ros2_example_apps/test/talker_listener.cc#L29)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Trailing whitespace.
</blockquote></details>

Removed trailing whitespace in c8d68f9

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/79)* status: all files reviewed, 3 unresolved discussions (waiting on @sloretz)

___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-N1Bjvo7EqFiolZYebbp:-N1_oRdvBIn-TuQMzDFZ:bay8ydb) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7ff920ddf395779906007af62633dd706de93492/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L98)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

`rcl_logging_spdlog` errors if it can't get the logging directory

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //ros2_example_apps:talker_listener_cc_test
-----------------------------------------------------------------------------

>>> [rcutils|error_handling.c:108] rcutils_set_error_state()
This error state is being overwritten:

  'rcutils_expand_user failed, at /tmp/ws/src/rcl_logging_interface/src/logging_dir.c:81'

with this new error message:

  'Failed to get logging directory, at /tmp/ws/src/rcl_logging_spdlog/src/rcl_logging_spdlog.cpp:83'

rcutils_reset_error() should be called after error handling to avoid this.
<<<
[ERROR] [1651681076.334153535] [rclcpp]: rcl context unexpectedly not shutdown during cleanup
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  failed to configure logging: Failed to get logging directory, at /tmp/ws/src/rcl_logging_spdlog/src/rcl_logging_spdlog.cpp:83
```


We could probably use a feature here that disabled trying to write to the filesystem altogether. Maybe an environment var `ROS_READ_ONLY_FILESYSTEM` that disables writing to the filesystem?
</blockquote></details>

Hm... While that may make sense, perhaps for now, we just leave it as-is?
The workarounds we have available (redirect to `/tmp` or `TEMP_DIR`) seem OK, just a tad odd.
Alternatively, is there a way to tell logging to use the `rcl_logging_noop` interface implementation?

As an aside - why does it fail on `expand_user`?
IMO, it's a bit weird for *that* function to care about a directory existing - should it be another function's responsibility?
___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-N1Bk5Cy-C5Llc0--bOq:-N1_p2y_0iGF76PUPA3K:b-bvuoxr) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7ff920ddf395779906007af62633dd706de93492/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L98)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I think the rest of this comment might have been cut off.
</blockquote></details>

Ah, sorry! Meant to say:

Can you also ensure you disable / cripple the communication endpoints? For example, in LCM, we make it use `memq://` by default; if inter-process (or inter-node) communication is needed, test author explicitly configures it:
https://github.com/RobotLocomotion/drake/blob/6482339ea56389d5adc2c27249b9857db9fa17b7/tools/bazel.rc#L40-L45
___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-N1BjW_P9lVBE52vGipS:-N1_pXfZ1qIEknEyPoX-:b-s6krl0) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7ff920ddf395779906007af62633dd706de93492/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L98)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

> /do_not_read_or_write_to_home

We can set it in the `.bazelrc`, but the `rcl_logging_spdlog` needs the folder to exist (cb11bd5dfcfde1051b030988f01c8a138dbc9dfe)

```
test --test_env=ROS_HOME=/do_not_read_or_write_to_home
```

results in

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //ros2_example_apps:talker_listener_cc_test
-----------------------------------------------------------------------------
[ERROR] [1651681365.663113714] [rclcpp]: rcl context unexpectedly not shutdown during cleanup
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  failed to configure logging: Failed to create log directory: /do_not_read_or_write_to_home/log, at /tmp/ws/src/rcl_logging_spdlog/src/rcl_logging_spdlog.cpp:90
```



</blockquote></details>

Gotcha, thanks for testing and confirming.

Seeing this now, perhaps your earlier suggestion is best - reconfigure to use `TEST_TEMPDIR` (or `/tmp` otherwise).
Otherwise, concurrent tests may encounter resource contention (I guess?)

Additionally, we should make things fail w/ a bread crumb, e.g. in `bazel.rc`:
```
--test_env=ROS_HOME=/does_not_exist/instead_please_reconfigure_in_test
```
then the error message is semi-helpful?

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/79)* status: all files reviewed, 3 unresolved discussions (waiting on @cottsay, @EricCousineau-TRI, and @sloretz)

___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-N1Bjvo7EqFiolZYebbp:-N1eYWtD2pWxkUdl-4Fc:b-n2ngn1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7ff920ddf395779906007af62633dd706de93492/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L98)):*
> Hm... While that may make sense, perhaps for now, we just leave it as-is?  The workarounds we have available (redirect to /tmp or TEMP_DIR) seem OK, just a tad odd.

If you're interested, there's a small discussion here about how to workaround it in this PR https://github.com/ros2/rcl_logging/pull/86

> Alternatively, is there a way to tell logging to use the rcl_logging_noop interface implementation?

 There is, but it's a compile time choice. @cottsay how much work would it be to switch the logging implementation in the `drake_ros_underlay` job? IIUC it means adding `-DRCL_LOGGING_IMPLEMENTATION=rcl_logging_noop` to the `rcl` build.
___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-N1Bk5Cy-C5Llc0--bOq:-N1ecvgH70-fXSAHBkV0:b-t7ka1p) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7ff920ddf395779906007af62633dd706de93492/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L98)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, sorry! Meant to say:

Can you also ensure you disable / cripple the communication endpoints? For example, in LCM, we make it use `memq://` by default; if inter-process (or inter-node) communication is needed, test author explicitly configures it:
https://github.com/RobotLocomotion/drake/blob/6482339ea56389d5adc2c27249b9857db9fa17b7/tools/bazel.rc#L40-L45
</blockquote></details>

I can set `ROS_LOCALHOST_ONLY` to restrict it to the current machine.

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/79)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @cottsay and @EricCousineau-TRI)

___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-N1BjW_P9lVBE52vGipS:-N1er7L_3MvnGjWpigxn:b-kcz8sj) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7ff920ddf395779906007af62633dd706de93492/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L98)):*
> setenv("ROS_HOME", fmt::format("{}/.ros", TEST_TMPDIR));

Setting `ROS_HOME` in the test in 7104cac9f28be107abc3b2766eaa3950330321dc

> Additionally, we should make things fail w/ a bread crumb, e.g. in bazel.rc:

Added ROS_HOME bread crumb to `.bazelrc` in afc0d86f094456983d78159bb852f825fc7949cb
___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-N1Bk5Cy-C5Llc0--bOq:-N1erO1AAk8BQHKbyc4i:bsg8xy8) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7ff920ddf395779906007af62633dd706de93492/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L98)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I can set `ROS_LOCALHOST_ONLY` to restrict it to the current machine.
</blockquote></details>

Using `ROS_LOCALHOST_ONLY` in d76763c26bb4c5ed0313960bc6e2627762e13bc2

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm: for C++! Would you be up for merging this PR, and tackling Python in separate PR?

> Reviewed 2 of 2 files at r3, all commit messages.
> Dismissed @sloretz from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-:-N1fIYUs9gWlTZ1nCWYf:bda2o71)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-N1Bk5Cy-C5Llc0--bOq:-N1fHNvQBBeEKjeKtbEQ:b89ecb5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7ff920ddf395779906007af62633dd706de93492/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L98)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Using `ROS_LOCALHOST_ONLY` in d76763c26bb4c5ed0313960bc6e2627762e13bc2
</blockquote></details>

OK That's better! At some point, we should perhaps have it fail fast, s.t. it requires testing to encapsulate. But we can handle that in future revisions.
___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/79#-N1Bjvo7EqFiolZYebbp:-N1fHZ-a6HkAKnjVovum:b-q73kce) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7ff920ddf395779906007af62633dd706de93492/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L98)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

> Hm... While that may make sense, perhaps for now, we just leave it as-is?  The workarounds we have available (redirect to /tmp or TEMP_DIR) seem OK, just a tad odd.

If you're interested, there's a small discussion here about how to workaround it in this PR https://github.com/ros2/rcl_logging/pull/86

> Alternatively, is there a way to tell logging to use the rcl_logging_noop interface implementation?

 There is, but it's a compile time choice. @cottsay how much work would it be to switch the logging implementation in the `drake_ros_underlay` job? IIUC it means adding `-DRCL_LOGGING_IMPLEMENTATION=rcl_logging_noop` to the `rcl` build.
</blockquote></details>

Ah, if it's compile time, then no need atm. I'd much rather have spdlog and work around, rather than completely use the noop interface.

I also liked Chris's the idea of redirecting spdlog sink to stderr, so we can always await that improvement.

Deferred "why error here" to https://github.com/ros2/rcutils/issues/358

Marking myself as satisfied!

**Pull request merged**
