### PR TITLE
Use DeclareStateOutputPort instead of DeclareAbstractOutputPort

### PR DESCRIPTION
**Pull request by sloretz**
Follow up to https://github.com/RobotLocomotion/drake-ros/pull/11/files#r690758458

Mimics https://github.com/RobotLocomotion/drake/pull/15563

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/12)

### CODE REVIEW

**Review by IanTheEngineer — APPROVED** [review]
:LGTM: Thanks for keeping this library close to it's LCM counterpart.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/12#-:-MhPvi5s3Uh_5jB_Ob6U:b-rjfc06)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

**Comment by sloretz** [comment]
Process question @IanTheEngineer, is an approving review all this PR needs before merging in this repo? Squash-merge?

**Comment by sloretz** [comment]
Ah, cherry-picked to #11! I'll close this one :)

**Comment by sloretz** [comment]
Ah, not cherry-picked. Reopening!

**Comment by IanTheEngineer** [comment]
Great questions, @sloretz. Let's default to squash-merge or squash-rebase-merge (as Drake does). I've disabled merge-commits merge for now. Once it's approved, either of us can merge the PR. In this specific case, I'll merge both.

**Pull request merged**
