### PR TITLE
Expose `bazel_ros2_rules` ros2 repository logic.

### PR DESCRIPTION
**Pull request by hidmic**
Precisely what the title says. Useful to implement other ROS 2 repository rules downstream.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/45)

### CODE REVIEW

**Comment by hidmic** [comment]
+@EricCousineau-TRI for peer review.

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm_strong: with two small nits on docs

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/45#-:-MxBcLUF23Pt84bWviva:b-rkw6d2)* status: all files reviewed, 2 unresolved discussions (waiting on @hidmic)

___
*[bazel_ros2_rules/ros2/defs.bzl, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/45#-MxBc0bc1A5YNOCVszZd:-MxBc0bc1A5YNOCVszZe:b-1yuf17) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9f476d1438a6180d61ca466fd99ef5ac9938a653/bazel_ros2_rules/ros2/defs.bzl#L33)):*
> ```Starlark
> 
> def base_ros2_repository(repo_ctx, workspaces):
>     """
> ```

nit Not immediately clear that `repo_ctx` depends on the `_attrs()` flavor being used.

Can you make that explicit here?
___
*[bazel_ros2_rules/ros2/defs.bzl, line 115 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/45#-MxBc74cEeVSi8-F_ieq:-MxBc74cEeVSi8-F_ier:bf8kz9p) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9f476d1438a6180d61ca466fd99ef5ac9938a653/bazel_ros2_rules/ros2/defs.bzl#L115)):*
> ```Starlark
>     return Label("//ros2:" + relpath)
> 
> def base_ros2_repository_attrs():
> ```

nit In isolation, unclear what this is intended for.

Can you add brief docstring?
(will do same for `external_data` parallel)

**Comment by EricCousineau-TRI** [comment]
See https://github.com/robotlocomotion/bazel-external-data/pull/27

**Review by EricCousineau-TRI — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/45)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hidmic)

**Pull request merged**
