### PR TITLE
Upgrade to Drake 1.34.0

### LINKED ISSUE #367: Please update DRAKE_SUGGESTED_VERSION to v1.34.0
https://github.com/RobotLocomotion/drake/releases/tag/v1.33.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #367.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/368)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
I don't seem to have push access? The suggested patch for CMake error is below:

diff --git a/drake_ros/CMakeLists.txt b/drake_ros/CMakeLists.txt
index a40174c..82b6996 100644
--- a/drake_ros/CMakeLists.txt
+++ b/drake_ros/CMakeLists.txt
@@ -13,6 +13,7 @@ endif()
 find_package(ament_cmake_ros REQUIRED)

 find_package(drake REQUIRED)
+find_package(Python3 COMPONENTS Interpreter Development)
 # Must use Drake's fork of Pybind11
 find_package(pybind11 REQUIRED HINTS "${drake_DIR}/../pybind11" NO_DEFAULT_PATH)

diff --git a/drake_ros/drake_ros/CMakeLists.txt b/drake_ros/drake_ros/CMakeLists.txt
index fba53e3..05b7a13 100644
--- a/drake_ros/drake_ros/CMakeLists.txt
+++ b/drake_ros/drake_ros/CMakeLists.txt
@@ -25,7 +25,6 @@ install(
 )

 if(BUILD_TESTING)
-  find_package(Python3 COMPONENTS Interpreter)
   find_package(ament_cmake_test REQUIRED)

   # TODO(eric.cousineau): I am not sure how to place a test-only Python library

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/368#-:-O9LfI5F0eYi6UBU7W2S:b-19vz6d)* status: 0 of 3 files reviewed, all discussions resolved

**Review by BetsyMcPhail — COMMENTED** [review]
Formatting - yikes! Let't try again...

```
diff --git a/drake_ros/CMakeLists.txt b/drake_ros/CMakeLists.txt
index a40174c..82b6996 100644
--- a/drake_ros/CMakeLists.txt
+++ b/drake_ros/CMakeLists.txt
@@ -13,6 +13,7 @@ endif()
 find_package(ament_cmake_ros REQUIRED)

 find_package(drake REQUIRED)
+find_package(Python3 COMPONENTS Interpreter Development)
 # Must use Drake's fork of Pybind11
 find_package(pybind11 REQUIRED HINTS "${drake_DIR}/../pybind11" NO_DEFAULT_PATH)

diff --git a/drake_ros/drake_ros/CMakeLists.txt b/drake_ros/drake_ros/CMakeLists.txt
index fba53e3..05b7a13 100644
--- a/drake_ros/drake_ros/CMakeLists.txt
+++ b/drake_ros/drake_ros/CMakeLists.txt
@@ -25,7 +25,6 @@ install(
 )

 if(BUILD_TESTING)
-  find_package(Python3 COMPONENTS Interpreter)
   find_package(ament_cmake_test REQUIRED)

   # TODO(eric.cousineau): I am not sure how to place a test-only Python library
```

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/368#-:-O9LfVfUCUITcpPEILnQ:b-skkv8g)* status: 0 of 3 files reviewed, all discussions resolved

**Comment by jwnimmer-tri** [comment]
Please try another push?  I added you to the project settings just now.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: x2

To the extent that I've ever touched/looked at drake-ros. But it all seems resonable and well spelled.

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/368#-:-O9Lv_9780qD5jYNQfNj:b-kx3pqc)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Pull request merged**
