### PR TITLE
[minor] Removes outdated text for paused subproject

### PR DESCRIPTION
**Pull request by adeeb10abbas**
Based on my conversation w/ @EricCousineau-TRI 
Reflects the current state of drake-ros. Removes misleading, outdated language.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/267)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Changed title, will merge once CI passes

**Comment by EricCousineau-TRI** [comment]
ah, keep forgetting to change commit messages - oops!

**Comment by adeeb10abbas** [comment]
Ah lol, can ya amend it now?

**Comment by EricCousineau-TRI** [comment]
nah, not a huge deal. I just need to be less trigger happy :grin:

**Pull request merged**
