### PR TITLE
Upgrade Drake to latest release 1.20.0

### LINKED ISSUE #296: Please update DRAKE_SUGGESTED_VERSION to v1.20.0
https://github.com/RobotLocomotion/drake/releases/tag/v1.20.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #296.

See also #293.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/294)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for review, please.

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm:, thanks! \cc @IanTheEngineer @calderpg-tri

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/294#-:-NbtgpM12qvuvk-txURS:b-qnoqrz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
I think the one of the builds keeps timing out.  I'm not sure if I should keep retrying it, but I'll give it another go.

**Comment by EricCousineau-TRI** [comment]
I've filed #295 to try and fix the caching issues as you've mentioned a ways back.
I will test locally using `./run_all_Tests.sh`, and then force merge if that works out.

**Comment by jwnimmer-tri** [comment]
We'll probably have Drake v1.20 tagged before CI is ready here, in which case I'll plan to rework this to pin v1.20 instead.

**Comment by jwnimmer-tri** [comment]
Hah, our posts crossed in the wind.

I guess I don't mind whether we land this with 1.19 now or wait a couple hours for 1.20.

**Comment by EricCousineau-TRI** [comment]
Ah, probably good to just wait out v1.20.0. I'll let my local tests continue to run, just in case.

**Comment by jwnimmer-tri** [comment]
Pushed up to 1.20 now.

**Comment by EricCousineau-TRI** [comment]
Local testing passed w/ newer `v1.20.0` push - merging!

**Pull request merged**
