### PR TITLE
Add fix_ament_lint script

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
While working on #175, #171. Found it painful to try and reason about how to reformat error messages into fixes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/176)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sloretz for review, please
\cc @iantheengineer 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/176#-:-NEvGCNF2MaFmHMAw3OI:b-gk0ook)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @sloretz)

**Review by sloretz — APPROVED** [review]

**Review by sloretz — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/176#-:-NGUD_B06leFaXZStwOG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Review by sloretz — COMMENTED** [review]
> +@sloretz for review, please

I seem to have lost the ability to approve PRs on this repo.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/176#-:-NGUDaqa91MGFzKYvOfx:b-nldkk3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Review by sloretz — APPROVED** [review]
Nevermind, now it worked.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/176#-:-NGUDplK77-RoM35ZnoD:b-fu5vq8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
Yeah, I just changed you to have "Write" permissions. I thought you'd be able to approve and merge, but I guess that makes sense.
Sorry about that!

**Pull request merged**
