### PR TITLE
[drake_ros_example] Add Getting Started indicator

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/235)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sloretz for review, please
I'd like to land this by Monday PM.

If you have any high-level comments, can I ask you to file a meta-PR?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/235#-:-NPE2NJzDiEa7KRHcdEz:bp4rrx0)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @sloretz)

**Review by adeeb10abbas — COMMENTED** [review]
minor :We should change all the "ROS2" instances in our docs to "ROS 2" in order to reflect [OSRF's standards (and stern requests :))](https://www.linkedin.com/posts/open-source-robotics-foundation_rosbrandguidepdf-activity-7034276256657399809-yOMT?utm_source=share&utm_medium=member_desktop)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/235#-:-NPE5Y3E6l5fHRERgct_:b-ns8lpl)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @sloretz)

**Review by EricCousineau-TRI — COMMENTED** [review]
done. hehe, yeah, everyone seems to be having a field day there.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/235#-:-NPE8MnlDeDt7CNAW4ee:bfoc3d4)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @sloretz)

**Review by EricCousineau-TRI — COMMENTED** [review]
Gonna go ahead and merge forward now, but we can fix-forward any other stuff in subsequent PRs!
-@sloretz +@EricCousineau-TRI :lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/235#-:-NPJwmbmEB6UTRsGxTOc:bp4ta4b)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 11 of 13 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/235)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Pull request merged**
