### PR TITLE
[viz] Use inlined byte array for heatmap png; remove VTK as dep

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
As mentioned in #305

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/307)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri Would you be up for review?
\cc @kunimatsu-tri @calderpg-tri @IanTheEngineer 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/307#-:-NhlQyQF79pcErc88LNw:b-1nqiua)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/307)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/307#-Nhlr-vf4Q1ivJqP1KR1:-Nhlr-vgARb3kof8r8g8:bkiy9ds) (no related file):*
The need for VTK in drake_ros is extremely minimal.  The code only uses it to encode a constant RGB array into constant PNG bytes.

The simpler fix would be to put the PNG data into a `constexpr char kHeapmapPng[] = ...` and purge VTK entirely.  Within the next release or two of Drake, we will have a PNG-to-memory writer public API, so you could revert to back using that pattern if you don't like the constexpr long-term.

___
___
*[`.github/workflows/bazelized_drake_ros.yml` line 57 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/307#-Nhlqwne2Z__aSf7XLR3:-Nhlqwne2Z__aSf7XLR4:b-tckyxz) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/e475875492f182c3edeec06bebab652340b60fe8/.github/workflows/bazelized_drake_ros.yml#L57)):*
> ```YAML
>         # but can't download the archive with bazel until we have the dependencies installed
>         # so bazel_ros2_rules can inspect it.
>         run: sudo apt-get install -y libconsole-bridge-dev libvtk9-dev
> ```

So this is adding the package to CI.  How are users of drake-ros supposed to know that they need this package?

This PR seems only to unwind the deprecation console warning, but not actually solve the more acute problem of a build failure for users.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/307)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/307#-Nhlr-vf4Q1ivJqP1KR1:-NhnNPEBCZk1LOkZBXPg:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The need for VTK in drake_ros is extremely minimal.  The code only uses it to encode a constant RGB array into constant PNG bytes.

The simpler fix would be to put the PNG data into a `constexpr char kHeapmapPng[] = ...` and purge VTK entirely.  Within the next release or two of Drake, we will have a PNG-to-memory writer public API, so you could revert to back using that pattern if you don't like the constexpr long-term.
</blockquote></details>

Done.

___
___
*[`.github/workflows/bazelized_drake_ros.yml` line 57 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/307#-Nhlqwne2Z__aSf7XLR3:-Nhn0vijCIPUfkPPKN1g:b-gbrv25) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/e475875492f182c3edeec06bebab652340b60fe8/.github/workflows/bazelized_drake_ros.yml#L57)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

So this is adding the package to CI.  How are users of drake-ros supposed to know that they need this package?

This PR seems only to unwind the deprecation console warning, but not actually solve the more acute problem of a build failure for users.
</blockquote></details>

See TODO above - we can't (easily) use `rosdep` for this CI setup because of the current usage of tarball.
For developers, `rosdep` should handle it, as mentioned here:
https://github.com/RobotLocomotion/drake-ros/blob/8e8f411a6e6819370521ec640a91f8dcdb17029a/drake_ros_examples/README.md#L89-L90
This is referenced by `CONTRIBUTING.md`.

(Moot now though)

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm: it's so good.

> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/307#-:-NhnQ51OClKiZ1JkoCgr:btof9uv)* status: all files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`drake_ros/viz/BUILD.bazel` line 28 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ros/307#-NhnQ8RT7sDGQLd7n-7c:-NhnQ8RU0-kJsaZ8GBAX:b-wtcfok) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/3e81a1cf468e00389d0e6457e93907799e83086b/drake_ros/viz/BUILD.bazel#L28)):*
> ```Starlark
>     hdrs = glob(
>         ["*.h"],
>         exclude = ["heamtap_png.raw.h"],
> ```

BTW If you make the `*.inc` change, this particular edit could disappear.
___
*[`drake_ros/viz/contact_markers_system.cc` line 91 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ros/307#-NhnPux8Cfsuv1oP-X0u:-NhnPux8Cfsuv1oP-X0v:b-9j29e1) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/3e81a1cf468e00389d0e6457e93907799e83086b/drake_ros/viz/contact_markers_system.cc#L91)):*
> ```cpp
> std::vector<uint8_t> GenerateHeatmapPng() {
>   return
> #include "./heatmap_png.raw.h"
> ```

BTW In my experience, a more typical extension for this file would be `*.inc` as in `#include "./heatmap_png.inc"`.

https://drake.mit.edu/styleguide/cppguide.html#Self_contained_Headers

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/307)* status: 9 of 14 files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

___
*[`drake_ros/viz/BUILD.bazel` line 28 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ros/307#-NhnQ8RT7sDGQLd7n-7c:-NhrNBNV6hGiLTY6XiwS:b-dtkds3) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/3e81a1cf468e00389d0e6457e93907799e83086b/drake_ros/viz/BUILD.bazel#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW If you make the `*.inc` change, this particular edit could disappear.
</blockquote></details>

Done, thanks!
___
*[`drake_ros/viz/contact_markers_system.cc` line 91 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ros/307#-NhnPux8Cfsuv1oP-X0u:-NhrNCd405bhM7xGqDtw:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/3e81a1cf468e00389d0e6457e93907799e83086b/drake_ros/viz/contact_markers_system.cc#L91)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW In my experience, a more typical extension for this file would be `*.inc` as in `#include "./heatmap_png.inc"`.

https://drake.mit.edu/styleguide/cppguide.html#Self_contained_Headers
</blockquote></details>

Done

**Review by jwnimmer-tri — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/307)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
CI failure not immediately clear, but assuming it's once again "out of disk space". Merging.

**Pull request merged**
