### PR TITLE
Add drake_ros_examples package

### PR DESCRIPTION
**Pull request by aaronchongth**
Spin off from #2. Built on top of #24.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/39)

### CODE REVIEW

**Comment by aaronchongth** [comment]
Per VC, 
* The `iiwa_manipulator` example is currently broken, a working example can be found in [a separate branch](https://github.com/RobotLocomotion/drake-ros/tree/aaron/drake_ros_examples_working/drake_ros_examples), the issue could possibly be the changes in the `header::frame_id`, `ns` and `id` of the marker messages,

```
ros2 run drake_ros_examples iiwa_manipulator
ros2 topic echo /scene_marker/visual
```

  * [frame_id](https://github.com/RobotLocomotion/drake-ros/pull/20): in order to support similar MbPs, the transform names will need to be namespaced with their relevant frame IDs, while the previous implementation does not include any frame IDs

before:
Screenshot from 2022-04-04 20-44-51

after:
Screenshot from 2022-04-04 20-51-53

  * [marker ns and id](https://github.com/RobotLocomotion/drake-ros/pull/22): [geometry IDs are not necessarily always in the same order between instances](https://github.com/RobotLocomotion/drake-ros/pull/22#pullrequestreview-922245237), therefore marker namespaces are generated using sources of the geometry IDs while marker IDs are only incremented when there are clashing namespaces

**Review by gbiggs — COMMENTED** [review]
I tested the `iiwa_manipulator` example and it worked for me. I'll keep prodding it in case I've missed something, but for now I think the first item can be checked off.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-:-N1aOMo52EFJGBxh5zfw:b-bolkuq)* status: 0 of 21 files reviewed, all discussions resolved

**Review by gbiggs — COMMENTED** [review]
I tried out the multirobot example to see how the frame IDs turned out. Below is the result. It looks like each individual robot is namespaced already to me.



> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-:-N1bOhqa6fAshiOu3LJW:b-jq1wis)* status: 0 of 21 files reviewed, all discussions resolved

**Review by gbiggs — COMMENTED** [review]
I have confirmed with @aaronchongth that the third point is a general note, not something that requires fixing. This PR is ready for review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-:-N1bTsYy2yg_oE7es6Fk:b-cnqwgk)* status: 0 of 21 files reviewed, all discussions resolved

**Review by sloretz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 20 of 20 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/39)* status: all files reviewed, 9 unresolved discussions (waiting on @aaronchongth)

___
*[`drake_ros_core/package.xml` line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-N1jrEED5cTGjIb_BgjE:-N1jrEED5cTGjIb_BgjF:b-ydmked) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1fb51f487bf509e13b8e2e262e5901702ce60122/drake_ros_core/package.xml#L13)):*
> ```XML
>   <buildtool_depend>ament_cmake_ros</buildtool_depend>
> 
>   <depend>pybind11-dev</depend>
> ```

I think this can be removed since we use `pybind11` from `drake`.
___
*[`drake_ros_examples/README.md` line 28 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-N1jrtVj4jrqNxvXZMc1:-N1jrtVj4jrqNxvXZMc2:b-z6msjb) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1fb51f487bf509e13b8e2e262e5901702ce60122/drake_ros_examples/README.md#L28)):*
> ```Markdown
> ## Running
> 
> * If you built with `colcon`, then source your workspace.
> ```

Nit, this sentence can be deleted because there's now only instructions on building with Colcon.
___
*[`drake_ros_examples/examples/CMakeLists.txt` line 2 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-N1js8GI69Xm09JECAp_:-N1js8GI69Xm09JECApa:bkmb5q6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1fb51f487bf509e13b8e2e262e5901702ce60122/drake_ros_examples/examples/CMakeLists.txt#L2)):*
> ```CMake
> add_subdirectory(iiwa_manipulator)
> add_subdirectory(rs_flip_flop)
> ```

Nit, subjectively I'd prefer these `add_subdirectories` where in the main `CMakeListst.txt` instead of a separate file. Feel free to ignore if you feel differently.

```CMake
add_subdirectory(examples/iiwa_manipulator)
add_subdirectory(examples/rs_flip_flop)
```
___
*[`drake_ros_examples/examples/iiwa_manipulator/iiwa_manipulator.py` line 38 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-N1uJSA64Shp8ubHDCoD:-N1uJSA64Shp8ubHDCoE:b-ys7jl3) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1fb51f487bf509e13b8e2e262e5901702ce60122/drake_ros_examples/examples/iiwa_manipulator/iiwa_manipulator.py#L38)):*
> ```Python
>     manipulation_station.SetupClutterClearingStation()
>     manipulation_station.Finalize()
>     pdb.set_trace()
> ```

This debug statement should be removed.
___
*[`drake_ros_examples/examples/iiwa_manipulator/README.md` line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-N1uJ3BI5v7112nYleLp:-N1uJ3BI5v7112nYleLq:b-z9wge7) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1fb51f487bf509e13b8e2e262e5901702ce60122/drake_ros_examples/examples/iiwa_manipulator/README.md#L13)):*
> ```Markdown
> ## How To
> 
> Run either the C++ `iiwa_manipulator` executable or the Python `iiwa_manipulator.py` script as explained [here](../../README.md#running).
> ```

I'd recommend including the commands to run this example in this file too.


```
ros2 run drake_ros_examples iiwa_manipulator
ros2 run drake_ros_examples iiwa_manipulator.py
```
___
*[`drake_ros_examples/examples/rs_flip_flop/README.md` line 18 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-N1uHYIa3R5aOq2-Na9Z:-N1uHYIa3R5aOq2-Na9_:bim5syr) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1fb51f487bf509e13b8e2e262e5901702ce60122/drake_ros_examples/examples/rs_flip_flop/README.md#L18)):*
> ```Markdown
> ## How To
> 
> Run either the C++ `rs_flip_flop` executable or the Python `rs_flip_flop.py` script as explained [here](../../README.md#running).
> ```

I'd recommend pasting the commands to run the examples here


```
ros2 run drake_ros_examples rs_flip_flop
ros2 run drake_ros_examples rs_flip_flop.py
```
___
*[`drake_ros_examples/examples/rs_flip_flop/README.md` line 34 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-N1uIZEQ9PYlpuPQVGyu:-N1uIZER4vkIZPu5ivgn:b-sgyib7) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1fb51f487bf509e13b8e2e262e5901702ce60122/drake_ros_examples/examples/rs_flip_flop/README.md#L34)):*
> ```Markdown
> ```
> ros2 topic pub /S std_msgs/msg/Bool "data: false"
> ros2 topic pub /S std_msgs/msg/Bool "data: true"
> ```

I'd recommend regrouping the commands so that `Q` actually changes. As it is, if I copy past these commands from top to bottom Q will always be `false. Something like

---


Make `Q` true with

```
ros2 topic pub /S std_msgs/msg/Bool "data: false"
ros2 topic pub /R std_msgs/msg/Bool "data: true"
```

Make `Q` false again with

```
ros2 topic pub /R std_msgs/msg/Bool "data: false"
ros2 topic pub /S std_msgs/msg/Bool "data: true"
```
___
*[`drake_ros_examples/examples/rs_flip_flop/rs_flip_flop.py` line 1 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-N1uHz-_4Ara7eHz_cBc:-N1uHz-_4Ara7eHz_cBd:b-wck4l8) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1fb51f487bf509e13b8e2e262e5901702ce60122/drake_ros_examples/examples/rs_flip_flop/rs_flip_flop.py#L1)):*
> ```Python
> # Copyright 2020 Open Source Robotics Foundation, Inc.
> ```

I think this needs a `#!/usr/bin/env python3`

```console
$ ros2 run drake_ros_examples rs_flip_flop.py 
Traceback (most recent call last):
  File "/opt/ros/rolling/bin/ros2", line 11, in <module>
    load_entry_point('ros2cli==0.17.1', 'console_scripts', 'ros2')()
  File "/opt/ros/rolling/lib/python3.8/site-packages/ros2cli/cli.py", line 89, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/rolling/lib/python3.8/site-packages/ros2run/command/run.py", line 70, in main
    return run_executable(path=path, argv=args.argv, prefix=prefix)
  File "/opt/ros/rolling/lib/python3.8/site-packages/ros2run/api/__init__.py", line 64, in run_executable
    process = subprocess.Popen(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/osrf/ws/drake/install/lib/drake_ros_examples/rs_flip_flop.py'
```
___
*[`drake_ros_examples/examples/rs_flip_flop/rs_flip_flop.py` line 145 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-N1uIJoY9xEnCdMNpnBd:-N1uIJoY9xEnCdMNpnBe:b6lfyyd) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1fb51f487bf509e13b8e2e262e5901702ce60122/drake_ros_examples/examples/rs_flip_flop/rs_flip_flop.py#L145)):*
> ```Python
> 
>     while True:
>         simulator.AdvanceTo(simulator_context.get_time() + 0.1)
> ```

Need an

```python
if __name__ == '__main__':
    main()
```

**Review by gbiggs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/39)* status: all files reviewed, 8 unresolved discussions (waiting on @sloretz)

___
*[`drake_ros_core/package.xml` line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-N1jrEED5cTGjIb_BgjE:-N2H1-fk5dDlppPZKnjl:bu6g7e4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1fb51f487bf509e13b8e2e262e5901702ce60122/drake_ros_core/package.xml#L13)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I think this can be removed since we use `pybind11` from `drake`.
</blockquote></details>

Removed in 7161030.
___
*[`drake_ros_examples/README.md` line 28 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-N1jrtVj4jrqNxvXZMc1:-N2H1Dus9ksCeU1Tpi4V:b-89he1p) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1fb51f487bf509e13b8e2e262e5901702ce60122/drake_ros_examples/README.md#L28)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Nit, this sentence can be deleted because there's now only instructions on building with Colcon.
</blockquote></details>

Corrected in c2294f2.
___
*[`drake_ros_examples/examples/CMakeLists.txt` line 2 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-N1js8GI69Xm09JECAp_:-N2H1U7j75BtA20_Plc1:bh26r4h) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1fb51f487bf509e13b8e2e262e5901702ce60122/drake_ros_examples/examples/CMakeLists.txt#L2)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Nit, subjectively I'd prefer these `add_subdirectories` where in the main `CMakeListst.txt` instead of a separate file. Feel free to ignore if you feel differently.

```CMake
add_subdirectory(examples/iiwa_manipulator)
add_subdirectory(examples/rs_flip_flop)
```
</blockquote></details>

Done in 47ff0f8.
___
*[`drake_ros_examples/examples/iiwa_manipulator/iiwa_manipulator.py` line 38 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-N1uJSA64Shp8ubHDCoD:-N2H3KVJEXDNxsuba7uH:b9f9o2l) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1fb51f487bf509e13b8e2e262e5901702ce60122/drake_ros_examples/examples/iiwa_manipulator/iiwa_manipulator.py#L38)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

This debug statement should be removed.
</blockquote></details>

Removed in 1b7b22c.
___
*[`drake_ros_examples/examples/iiwa_manipulator/README.md` line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-N1uJ3BI5v7112nYleLp:-N2H3pXI7erzrrsNzg8W:bio8z12) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1fb51f487bf509e13b8e2e262e5901702ce60122/drake_ros_examples/examples/iiwa_manipulator/README.md#L13)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I'd recommend including the commands to run this example in this file too.


```
ros2 run drake_ros_examples iiwa_manipulator
ros2 run drake_ros_examples iiwa_manipulator.py
```



</blockquote></details>

Added in a0c27c8.
___
*[`drake_ros_examples/examples/rs_flip_flop/README.md` line 18 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-N1uHYIa3R5aOq2-Na9Z:-N2H4BpRAlx9HxqeNf2s:b-su6a9u) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1fb51f487bf509e13b8e2e262e5901702ce60122/drake_ros_examples/examples/rs_flip_flop/README.md#L18)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I'd recommend pasting the commands to run the examples here


```
ros2 run drake_ros_examples rs_flip_flop
ros2 run drake_ros_examples rs_flip_flop.py
```
</blockquote></details>

Clarified in 12ba117.
___
*[`drake_ros_examples/examples/rs_flip_flop/README.md` line 34 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-N1uIZEQ9PYlpuPQVGyu:-N2H5Bx0EQO5ZseMD-6Q:b-1oye05) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1fb51f487bf509e13b8e2e262e5901702ce60122/drake_ros_examples/examples/rs_flip_flop/README.md#L34)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I'd recommend regrouping the commands so that `Q` actually changes. As it is, if I copy past these commands from top to bottom Q will always be `false. Something like

---


Make `Q` true with

```
ros2 topic pub /S std_msgs/msg/Bool "data: false"
ros2 topic pub /R std_msgs/msg/Bool "data: true"
```

Make `Q` false again with

```
ros2 topic pub /R std_msgs/msg/Bool "data: false"
ros2 topic pub /S std_msgs/msg/Bool "data: true"
```


</blockquote></details>

Good catch! Clarified in 199bb3e.
___
*[`drake_ros_examples/examples/rs_flip_flop/rs_flip_flop.py` line 1 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-N1uHz-_4Ara7eHz_cBc:-N2HFDiP2efqx4Zkm5-o:b-77meb0) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1fb51f487bf509e13b8e2e262e5901702ce60122/drake_ros_examples/examples/rs_flip_flop/rs_flip_flop.py#L1)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I think this needs a `#!/usr/bin/env python3`

```console
$ ros2 run drake_ros_examples rs_flip_flop.py 
Traceback (most recent call last):
  File "/opt/ros/rolling/bin/ros2", line 11, in <module>
    load_entry_point('ros2cli==0.17.1', 'console_scripts', 'ros2')()
  File "/opt/ros/rolling/lib/python3.8/site-packages/ros2cli/cli.py", line 89, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/rolling/lib/python3.8/site-packages/ros2run/command/run.py", line 70, in main
    return run_executable(path=path, argv=args.argv, prefix=prefix)
  File "/opt/ros/rolling/lib/python3.8/site-packages/ros2run/api/__init__.py", line 64, in run_executable
    process = subprocess.Popen(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/osrf/ws/drake/install/lib/drake_ros_examples/rs_flip_flop.py'
```
</blockquote></details>

Added in eb33c9c.
___
*[`drake_ros_examples/examples/rs_flip_flop/rs_flip_flop.py` line 145 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-N1uIJoY9xEnCdMNpnBd:-N2HG1GtEivsvXcUssLn:b-fp8p5c) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1fb51f487bf509e13b8e2e262e5901702ce60122/drake_ros_examples/examples/rs_flip_flop/rs_flip_flop.py#L145)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Need an

```python
if __name__ == '__main__':
    main()
```
</blockquote></details>

Done in 0e45e4e.

**Comment by gbiggs** [comment]
Thanks for the review, @sloretz. I've made the appropriate fixes. Unfortunately it turns out that the flip flop Python example doesn't actually run, so I need to fix that before this can be merged.

**Comment by gbiggs** [comment]
@sloretz I've corrected the API usage in the Python `rs_flip_flop` sample so it functions now. If you're happy, I think we're ready to merge this.

**Review by sloretz — APPROVED** [review]
I tested the examples locally. This :lgtm: :tada: 

> Reviewed 7 of 8 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/39#-:-N2mBMQhEGyMhoqzTS4i:blx9koz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronchongth)

**Pull request merged**
