### PR TITLE
[rosidl] Ensure *_defs data is added to *_py and *_cc targets

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards Anzu bugfix

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/305)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@kunimatsu-tri for review, please!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/305#-:-NhiP6Fs61x6lkSUqUPs:bjmcw9h)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @kunimatsu-tri)

**Comment by EricCousineau-TRI** [comment]
`Bazel Drake-ROS Continuous Integration` tests pass locally for me.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/305)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @kunimatsu-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/305#-NhiTgC72xkOoyIeL4J4:-NhiTgC72xkOoyIeL4J5:bml3nbg) (no related file):*
Working: Certain Anzu tests fail with something like:
```
  File "{runfiles}/bazel_ros2_rules/ros2/tools/dload_shim.py", line 58, in do_dload_shim
    os.execv(real_executable_path, argv)
OSError: [Errno 7] Argument list too long
```

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/305)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @kunimatsu-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/305#-NhiTgC72xkOoyIeL4J4:-NhiZuG5BKFFxqeFT_I0:b-jzz43f) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Certain Anzu tests fail with something like:
```
  File "{runfiles}/bazel_ros2_rules/ros2/tools/dload_shim.py", line 58, in do_dload_shim
    os.execv(real_executable_path, argv)
OSError: [Errno 7] Argument list too long
```
</blockquote></details>

The `AMENT_INDEX_PATH` environment variable has ~800 duplicate entries for `rosidl_generate_ament_index_entry`

These should be deduplicated

___

**Comment by kunimatsu-tri** [comment]
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 402 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/305#-Nhi_UizBpNKwJOjqVp1:-Nhi_UizBpNKwJOjqVp2:b1wtu2j) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/0b754cd9260e59e8b70298e99770d288cbf2de9f/bazel_ros2_rules/ros2/rosidl.bzl#L402)):*
> ```Starlark
>         interfaces,
>         includes = [],
>         data = [],
> ```

nit Can I ask you to add a corresponding doc string to the data argument?

Ditto for all the interface changes.

**Comment by kunimatsu-tri** [comment]
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

The `AMENT_INDEX_PATH` environment variable has ~800 duplicate entries for `rosidl_generate_ament_index_entry`

These should be deduplicated
</blockquote></details>

:(

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/305)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @kunimatsu-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/305#-NhiTgC72xkOoyIeL4J4:-NhidKlEBmz_zgCHRD-e:b-896fix) (no related file):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

:(
</blockquote></details>

Done.

___
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 402 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/305#-Nhi_UizBpNKwJOjqVp1:-NhidK6r6UNOLx2Tqh7W:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/0b754cd9260e59e8b70298e99770d288cbf2de9f/bazel_ros2_rules/ros2/rosidl.bzl#L402)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

nit Can I ask you to add a corresponding doc string to the data argument?

Ditto for all the interface changes.
</blockquote></details>

Done.

**Review by kunimatsu-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/305)* status: 2 of 3 files reviewed, all discussions resolved

**Comment by kunimatsu-tri** [comment]
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:)

**Review by kunimatsu-tri — COMMENTED** [review]
I confirmed that `custom_message_list_test` passes locally. 

Thanks for this quick fix! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/305#-:-NhivcJvCogC-XxQDvEG:bgosji9)* status: 2 of 3 files reviewed, all discussions resolved

**Comment by kunimatsu-tri** [comment]
`Build drake_ros` in CI failed with the following error:

```
ERROR: /home/runner/.cache/bazel/\_bazel\_runner/d07b19e4bc14c7eead45599d9bb941ba/external/vtk/BUILD.bazel:31:11: Middleman \_middlemen/@vtk\_S\_S\_Cvtkkwiml-cc\_library-compile failed: missing input file '@vtk//:include/vtk-9.1/vtk\_kwiml.h'

[136](https://github.com/RobotLocomotion/drake-ros/actions/runs/6661541550/job/18104550754#step:13:137)ERROR: /home/runner/.cache/bazel/\_bazel\_runner/d07b19e4bc14c7eead45599d9bb941ba/external/vtk/BUILD.bazel:31:11: Middleman \_middlemen/@vtk\_S\_S\_Cvtkkwiml-cc\_library-compile failed: missing input file '@vtk//:include/vtk-9.1/vtkkwiml/abi.h'

[137](https://github.com/RobotLocomotion/drake-ros/actions/runs/6661541550/job/18104550754#step:13:138)ERROR: /home/runner/.cache/bazel/\_bazel\_runner/d07b19e4bc14c7eead45599d9bb941ba/external/vtk/BUILD.bazel:31:11: Middleman \_middlemen/@vtk\_S\_S\_Cvtkkwiml-cc\_library-compile failed: missing input file '@vtk//:include/vtk-9.1/vtkkwiml/int.h'

[138](https://github.com/RobotLocomotion/drake-ros/actions/runs/6661541550/job/18104550754#step:13:139)ERROR: /home/runner/.cache/bazel/\_bazel\_runner/d07b19e4bc14c7eead45599d9bb941ba/external/vtk/BUILD.bazel:31:11: Middleman \_middlemen/@vtk\_S\_S\_Cvtkkwiml-cc\_library-compile failed: 3 input file(s) do not exist
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/305)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @kunimatsu-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/305#-NhizdvK59wR_A85rRbR:-NhjC3-s2Ee4p7qLfpsB:b9h2364) (no related file):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

`Build drake_ros` in CI failed with the following error:

```
ERROR: /home/runner/.cache/bazel/\_bazel\_runner/d07b19e4bc14c7eead45599d9bb941ba/external/vtk/BUILD.bazel:31:11: Middleman \_middlemen/@vtk\_S\_S\_Cvtkkwiml-cc\_library-compile failed: missing input file '@vtk//:include/vtk-9.1/vtk\_kwiml.h'

[136](https://github.com/RobotLocomotion/drake-ros/actions/runs/6661541550/job/18104550754#step:13:137)ERROR: /home/runner/.cache/bazel/\_bazel\_runner/d07b19e4bc14c7eead45599d9bb941ba/external/vtk/BUILD.bazel:31:11: Middleman \_middlemen/@vtk\_S\_S\_Cvtkkwiml-cc\_library-compile failed: missing input file '@vtk//:include/vtk-9.1/vtkkwiml/abi.h'

[137](https://github.com/RobotLocomotion/drake-ros/actions/runs/6661541550/job/18104550754#step:13:138)ERROR: /home/runner/.cache/bazel/\_bazel\_runner/d07b19e4bc14c7eead45599d9bb941ba/external/vtk/BUILD.bazel:31:11: Middleman \_middlemen/@vtk\_S\_S\_Cvtkkwiml-cc\_library-compile failed: missing input file '@vtk//:include/vtk-9.1/vtkkwiml/int.h'

[138](https://github.com/RobotLocomotion/drake-ros/actions/runs/6661541550/job/18104550754#step:13:139)ERROR: /home/runner/.cache/bazel/\_bazel\_runner/d07b19e4bc14c7eead45599d9bb941ba/external/vtk/BUILD.bazel:31:11: Middleman \_middlemen/@vtk\_S\_S\_Cvtkkwiml-cc\_library-compile failed: 3 input file(s) do not exist
```
</blockquote></details>

BTW That's because #304 upgraded the Drake pin but did not account for the VTK deprecation warning.  The `contact_markers_system.cc` is doing `#include <vtkImageData.h>` using Drake's deprecated VTK repository rule, but somehow has not installed `libvtk9-dev`?  However, I do see `drake_ros/package.xml` has `<depend>libvtk9-dev</depend>` so I'm not sure why that package apparently isn't installed in CI.

___

**Comment by EricCousineau-TRI** [comment]
Ah, nuts. For now, I'll merge this PR (since testing passed locally) and fix the vtk issue in a separate PR.

**Pull request merged**
