### PR TITLE
[drake] Upgrade to v1.24.0

### LINKED ISSUE #321: Please update DRAKE_SUGGESTED_VERSION to v1.24.0
https://github.com/RobotLocomotion/drake/releases/tag/v1.24.0

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #321

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/322)

### CODE REVIEW

**Comment by ahcorde** [comment]
I included this change in this other PR https://github.com/RobotLocomotion/drake-ros/pull/325 and now CI is green

**Comment by ahcorde** [comment]
already included and merged in this PR https://github.com/RobotLocomotion/drake-ros/pull/325

**Comment by adityapande-1995** [comment]
Closing this and the connected issue.

**Comment by EricCousineau-TRI** [comment]
thanks!

**Pull request closed without merging**
