### PR TITLE
Add multirobot sample in C++ and Python

### PR DESCRIPTION
**Pull request by gbiggs**
This PR adds a multirobot example using Drake-ROS. It creates a two-dimensional array of Kuka LBR iiwa robots, which can then be visualised using rviz.

See the included README.md file for how to run the example.

This PR is a re-do of #46.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/85)

### CODE REVIEW

**Review by sloretz — CHANGES_REQUESTED** [review]
I like how everything is commented! The code feels really clear and easy to follow.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/85#-:-N49UMDtC3cbtrVfj_0h:be6xgud)* status: all files reviewed, 6 unresolved discussions (waiting on @gbiggs)

___
*[`drake_ros_examples/examples/multirobot/multirobot.cc` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/85#-N49TPf83h2iwTKiixA5:-N49TPf9CxGiRHSq7_Kj:bk3fj2n) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e12cf97241bbb06a9895a47e873170c2eae23138/drake_ros_examples/examples/multirobot/multirobot.cc#L38)):*
> ```cpp
> 
> 
> int main()
> ```

clang_format and cpp_lint tests are failing on this file. Mind formatting it?
___
*[`drake_ros_examples/examples/multirobot/multirobot.cc` line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/85#-N49Td1W8FcvZjwAPWaF:-N49Td1W8FcvZjwAPWaG:b-qg3jby) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e12cf97241bbb06a9895a47e873170c2eae23138/drake_ros_examples/examples/multirobot/multirobot.cc#L64)):*
> ```cpp
>     ros_interface_system->get_ros_interface(),
>     drake_ros_viz::RvizVisualizerParams{
>       {drake::systems::TriggerType::kPeriodic}, 0.05, true});
> ```

I'd recommend making this `kForced` to match the TF broadcaster. IIUC the markers will always be the same so RViz is only going to show movement when it gets the updated TF Transforms. This looks like it publishes the markers twice as often as the transforms.
___
*[`drake_ros_examples/examples/multirobot/multirobot.cc` line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/85#-N49U8Yp5khc5SjQpKmU:-N49U8Yp5khc5SjQpKmV:b7mx63s) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e12cf97241bbb06a9895a47e873170c2eae23138/drake_ros_examples/examples/multirobot/multirobot.cc#L70)):*
> ```cpp
>   // Prepare to load the robot model
>   auto parser = drake::multibody::Parser(&plant);
>   parser.package_map().PopulateFromEnvironment("AMENT_PREFIX_PATH");
> ```

Same comment about this not being necessary
___
*[`drake_ros_examples/examples/multirobot/multirobot.py` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/85#-N49UunE8IXnChBd6wSu:-N49UunE8IXnChBd6wSv:b-76n871) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e12cf97241bbb06a9895a47e873170c2eae23138/drake_ros_examples/examples/multirobot/multirobot.py#L58)):*
> ```Python
>             sys_ros_interface.get_ros_interface(),
>             params=RvizVisualizerParams(
>                 publish_triggers={TriggerType.kPeriodic}
> ```

Same comment about matching the TF transform publisher
___
*[`drake_ros_examples/examples/multirobot/multirobot.py` line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/85#-N49SEuW40Q_ofkTR4Y4:-N49SEuW40Q_ofkTR4Y5:b-sfahtg) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e12cf97241bbb06a9895a47e873170c2eae23138/drake_ros_examples/examples/multirobot/multirobot.py#L68)):*
> ```Python
>     # Prepare to load the robot model
>     parser = Parser(plant)
>     parser.package_map().PopulateFromEnvironment('AMENT_PREFIX_PATH')
> ```

I don't think this is necessary because the default constructor for PackageMap populates it with the Drake package.xml . The demo works fine if I comment it out.

https://github.com/RobotLocomotion/drake/blob/e11134f425cc12b80246617421a6d528df96765b/multibody/parsing/package_map.cc#L31
___
*[`drake_ros_examples/examples/multirobot/multirobot.py` line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/85#-N49S4LB8k4dm7miMh6j:-N49S4LB8k4dm7miMh6k:bdtp96a) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e12cf97241bbb06a9895a47e873170c2eae23138/drake_ros_examples/examples/multirobot/multirobot.py#L97)):*
> ```Python
>     for x in range(NUM_ROWS):
>         for y in range(NUM_COLS):
>             # Get the number of degrees of freedom for the robot
> ```

missing initialization of `model`. The example works if I add:

```
            model = models[x][y]
```

**Review by gbiggs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/85)* status: all files reviewed, 5 unresolved discussions (waiting on @gbiggs and @sloretz)

___
*[`drake_ros_examples/examples/multirobot/multirobot.cc` line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/85#-N49Td1W8FcvZjwAPWaF:-N5-67oz2CQcpfmu2sn5:b7grmnf) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e12cf97241bbb06a9895a47e873170c2eae23138/drake_ros_examples/examples/multirobot/multirobot.cc#L64)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I'd recommend making this `kForced` to match the TF broadcaster. IIUC the markers will always be the same so RViz is only going to show movement when it gets the updated TF Transforms. This looks like it publishes the markers twice as often as the transforms.
</blockquote></details>

Done in 4bcbab3.
___
*[`drake_ros_examples/examples/multirobot/multirobot.cc` line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/85#-N49U8Yp5khc5SjQpKmU:-N5-5YxF3QqY5euHWmjD:bqk0eg1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e12cf97241bbb06a9895a47e873170c2eae23138/drake_ros_examples/examples/multirobot/multirobot.cc#L70)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Same comment about this not being necessary
</blockquote></details>

Fixed in b05bb4d.
___
*[`drake_ros_examples/examples/multirobot/multirobot.py` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/85#-N49UunE8IXnChBd6wSu:-N5-6ieD1tppFPI0kM65:bepcudm) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e12cf97241bbb06a9895a47e873170c2eae23138/drake_ros_examples/examples/multirobot/multirobot.py#L58)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Same comment about matching the TF transform publisher
</blockquote></details>

Done in 2c7d63a.
___
*[`drake_ros_examples/examples/multirobot/multirobot.py` line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/85#-N49SEuW40Q_ofkTR4Y4:-N5-5X9g40Ge9GMVu22F:bqk0eg1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e12cf97241bbb06a9895a47e873170c2eae23138/drake_ros_examples/examples/multirobot/multirobot.py#L68)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I don't think this is necessary because the default constructor for PackageMap populates it with the Drake package.xml . The demo works fine if I comment it out.

https://github.com/RobotLocomotion/drake/blob/e11134f425cc12b80246617421a6d528df96765b/multibody/parsing/package_map.cc#L31
</blockquote></details>

Fixed in b05bb4d.
___
*[`drake_ros_examples/examples/multirobot/multirobot.py` line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/85#-N49S4LB8k4dm7miMh6j:-N5-5E7p65bnsY05rwQ3:bnbew1v) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e12cf97241bbb06a9895a47e873170c2eae23138/drake_ros_examples/examples/multirobot/multirobot.py#L97)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

missing initialization of `model`. The example works if I add:

```
            model = models[x][y]
```
</blockquote></details>

Fixed in a5fe9b1.

**Review by gbiggs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/85)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @sloretz)

___
*[`drake_ros_examples/examples/multirobot/multirobot.cc` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/85#-N49TPf83h2iwTKiixA5:-N5-9mAq9EhsNgG4KjJ3:b7d3cm1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e12cf97241bbb06a9895a47e873170c2eae23138/drake_ros_examples/examples/multirobot/multirobot.cc#L38)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

clang_format and cpp_lint tests are failing on this file. Mind formatting it?
</blockquote></details>

Done in 3582c1a.

**Review by sloretz — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbiggs)

**Pull request merged**
