### PR TITLE
[py] Make it easier to pass C++ node pointers in Python

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
I would like to not get too creative when trying to bind C++ code that has `rclcpp::Node` arguments. This is one approach.
Relates https://github.com/ros2/rclpy/issues/291

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/285)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sloretz Might you have time to review this?

\cc @dmcconachie-tri @calderpg-tri @IanTheEngineer 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/285#-:-NXvcw8sEVf5gGlPtJcn:b-17jxd8)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @sloretz)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/285)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sloretz)

___
*[`drake_ros/drake_ros/core/cc_pybind.cc` line 143 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/285#-NXvkrtMBh1Q7k-GRcox:-NXvkrtMBh1Q7k-GRcoy:bhjweey) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/a2e94fdcecfc6c1d58f5688e2384137c4e65af0d/drake_ros/drake_ros/core/cc_pybind.cc#L143)):*
> ```cpp
> 
>   py::class_<rclcpp::Node, std::shared_ptr<rclcpp::Node>>(m, "CppNode",
>                                                           py::module_local())
> ```

Working: This seems to cause a segfault in Anzu. Removing `py::module_local()` makes things a bit happier.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/285)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/285#-NXvnrSjBSan-YUOu8FH:-NXvnrSjBSan-YUOu8FI:b-nc8g5n) (no related file):*
There seems to be a new CI failure, most likely unrelated to this PR:
https://github.com/RobotLocomotion/drake-ros/actions/runs/5272233626/jobs/9534218327?pr=285#step:7:345
```
  CMake Error at drake_ros/CMakeLists.txt:7 (target_link_libraries):
    Error evaluating generator expression:
  
      $<TARGET_PROPERTY:fastcdr,TYPE>
  
    Target "fastcdr" not found.
```

@sloretz Is this something we need to work around, or is there something else going awry here?

___
___
*[`drake_ros/drake_ros/core/cc_pybind.cc` line 143 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/285#-NXvkrtMBh1Q7k-GRcox:-NXvnlACEaXWjSWGZy7e:b-tqeiu0) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/a2e94fdcecfc6c1d58f5688e2384137c4e65af0d/drake_ros/drake_ros/core/cc_pybind.cc#L143)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: This seems to cause a segfault in Anzu. Removing `py::module_local()` makes things a bit happier.
</blockquote></details>

Done. For now, making this global; can take a step back if/when it interferes with another library's bindings.

**Review by adityapande-1995 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/285)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

___
*[`drake_ros/drake_ros/test/core_test.py` line 122 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ros/285#-NYUeDbzCC5XPaq0lt_L:-NYUeDbzCC5XPaq0lt_M:b-48ugj7) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/43c13c04a04ff78d98d3e71706bb2cfbf84964c5/drake_ros/drake_ros/test/core_test.py#L122)):*
> ```Python
>     assert not cpp_node_options.use_global_arguments
>     node_cpp = CppNode("direct_node", node_options=cpp_node_options)
>     assert node_cpp.get_name() == "direct_node"
> ```

1. If we are planning to expose existing rclcpp nodes to python, what APIs are we planning to connect ? i.e. can we add subscribers, publishers, callbacks, etc ?
It'd be nice to add tests for and document the features that we'll be exposing as a docstring, and also the limitations of this binding.

2. I'd be great if we can add a test that shows that this node can actually spin and receive / send msgs, and play alongside existing "vanilla" rclpy nodes. I'm curious to see how rclpy.spin() and rclcpp::spin() interact.

**Review by adityapande-1995 — COMMENTED** [review]
If we're planning to bind subscribers or publishers, this automatiically requires a generic typecaster for data types : https://github.com/RobotLocomotion/drake-ros/pull/257

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/285#-:-NYUhA7y9hKIJxt6aeGf:b-teod9j)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/285)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @sloretz)

___
*[`drake_ros/drake_ros/test/core_test.py` line 122 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ros/285#-NYUeDbzCC5XPaq0lt_L:-NYUj7WDENeoYE7Lm7J9:b1962l9) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/43c13c04a04ff78d98d3e71706bb2cfbf84964c5/drake_ros/drake_ros/test/core_test.py#L122)):*
<details><summary><i>Previously, adityapande-1995 (Aditya Pande) wrote…</i></summary><blockquote>

1. If we are planning to expose existing rclcpp nodes to python, what APIs are we planning to connect ? i.e. can we add subscribers, publishers, callbacks, etc ?
It'd be nice to add tests for and document the features that we'll be exposing as a docstring, and also the limitations of this binding.

2. I'd be great if we can add a test that shows that this node can actually spin and receive / send msgs, and play alongside existing "vanilla" rclpy nodes. I'm curious to see how rclpy.spin() and rclcpp::spin() interact.
</blockquote></details>

Working: Per Slack DM, the intent of this is to only bind the minimum amount of the C++ Node API in Python so we don't need too much creativity in writing downstream bindings.
I'm going to hold off on binding additional facets, but I will add a quick test.

(I think functionality that consumes `DrakeRos` effectively shows it, but yes, it'd be nice to just test directly.)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/285)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @adityapande-1995 and @sloretz)

___
*[`drake_ros/drake_ros/test/core_test.py` line 122 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ros/285#-NYUeDbzCC5XPaq0lt_L:-NYUrxtm-A6rpxAjRLSA:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/43c13c04a04ff78d98d3e71706bb2cfbf84964c5/drake_ros/drake_ros/test/core_test.py#L122)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Per Slack DM, the intent of this is to only bind the minimum amount of the C++ Node API in Python so we don't need too much creativity in writing downstream bindings.
I'm going to hold off on binding additional facets, but I will add a quick test.

(I think functionality that consumes `DrakeRos` effectively shows it, but yes, it'd be nice to just test directly.)
</blockquote></details>

Done.

**Comment by EricCousineau-TRI** [comment]
Done, I think. I had an odd failure of CMake-based ROS failing, but will see if CI shows the same issue.

**Comment by EricCousineau-TRI** [comment]
@adityapande-1995 CI seems to have failed.

Can I ask if you can reproduce this (Bazel passes, CMake fails) and, if so, what might be the problem?

```sh
# Bazel
cd drake-ros
cd drake_ros
bazel run //drake_ros:core_test
# Passes

# CMake
cd ros_ws
colcon build --packages-up-to drake_ros --symlink-install
# "Shortcut" - not sure how to run single test
source install/setup.bash
( cd build/drake_ros && ctest -V -R core_test_py; )
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/285)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @adityapande-1995 and @sloretz)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/285#-NXvnrSjBSan-YUOu8FH:-NYYhc26-bzPuvbBUBK7:bjwfb0e) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

There seems to be a new CI failure, most likely unrelated to this PR:
https://github.com/RobotLocomotion/drake-ros/actions/runs/5272233626/jobs/9534218327?pr=285#step:7:345
```
  CMake Error at drake_ros/CMakeLists.txt:7 (target_link_libraries):
    Error evaluating generator expression:
  
      $<TARGET_PROPERTY:fastcdr,TYPE>
  
    Target "fastcdr" not found.
```

@sloretz Is this something we need to work around, or is there something else going awry here?
</blockquote></details>

Done (I think) - I did not see this error once I rebased onto latest `main`

___

**Review by EricCousineau-TRI — COMMENTED** [review]
This appears to be an RMW implementation issue. I've addressed it with a workaround, will file an issue.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/285#-:-NYy0YKP-nagVuS_xYjw:b-3wtstj)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @adityapande-1995 and @sloretz)

**Comment by EricCousineau-TRI** [comment]
Core bazel testing of `drake_ros` is done. I'm going to go ahead and skip `drake_ros_examples` because our caching is still broken.

**Pull request merged**
