### PR TITLE
Use --output so ROS_DISTRO being set doesn't affect build

### LINKED ISSUE #53: Should prevent ROS_DISTRO from polluting build
As encountered in Anzu build, if a ROS 1 workspace / setup is sourced, then the build may fail, e.g.:
```sh
INFO: Repository ros2 instantiated at:
  {source}/WORKSPACE:56:25: in <toplevel>
  {source}/tools/workspace/default.bzl:282:24: in add_default_repositories
  {source}/tools/workspace/ros2/repository.bzl:53:26: in ros2_repository
Repository rule _ros2_repository_rule defined at:
  {source}/tools/workspace/ros2/repository.bzl:42:40: in <toplevel>
ERROR: An error occurred during the fetch of repository 'ros2':
   Traceback (most recent call last):
    File "{source}/tools/workspace/ros2/repository.bzl", line 27, column 25, in _ros2_repository_impl
        base_ros2_repository(
    File "{workspace}/external/bazel_ros2_rules/ros2/defs.bzl", line 87, column 29, in base_ros2_repository
        result = execute_or_fail(repo_ctx, cmd, quiet=True)
    File "{workspace}/external/bazel_ros2_rules/tools/execute.bzl", line 16, column 13, in execute_or_fail
        fail("Failed to setup @{} repository: {}".format(
Error in fail: Failed to setup @ros2 repository: './run.bash {workspace}/external/bazel_ros2_rules/ros2/generate_distro_file.py -s {workspace}/external/ros2/ros2-linux:ros2-linux -d distro_metadata.json ros2' exited with 1
--- captured stdout ---
ROS_DISTRO was set to 'noetic' before. Please make sure that the environment does not mix paths from different distributions.

--- captured stderr ---
Traceback (most recent call last):
  File "{workspace}/external/bazel_ros2_rules/ros2/generate_distro_file.py", line 105, in <module>
    main()
  File "{workspace}/external/bazel_ros2_rules/ros2/generate_distro_file.py", line 98, in main
    args = parse_arguments()
  File "{workspace}/external/bazel_ros2_rules/ros2/generate_distro_file.py", line 64, in parse_arguments
    args.distro = json.load(args.distro_file)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR: {source}/WORKSPACE:56:25: fetching _ros2_repository_rule rule //external:ros2: Traceback (most recent call last):
    File "{source}/tools/workspace/ros2/repository.bzl", line 27, column 25, in _ros2_repository_impl
        base_ros2_repository(
    File "{workspace}/external/bazel_ros2_rules/ros2/defs.bzl", line 87, column 29, in base_ros2_repository
        result = execute_or_fail(repo_ctx, cmd, quiet=True)
    File "{workspace}/external/bazel_ros2_rules/tools/execute.bzl", line 16, column 13, in execute_or_fail
        fail("Failed to setup @{} repository: {}".format(
```

\cc @IanTheEngineer

### PR DESCRIPTION
**Pull request by sloretz**
Fixes #53 thats to @hidmic's comment https://github.com/RobotLocomotion/drake-ros/issues/53#issuecomment-1088740125

@IanTheEngineer & @EricCousineau-TRI

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/54)

### CODE REVIEW

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/54)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/54#-Mzuq8T64zAdE-4RDa_7:-Mzuq8T72jWiDAF9a9Wb:b-f79vt4) (no related file):*
Working: Testing locally.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/54#-:-Mzus395B0YOjbvvfdit:b-uwkowd)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/54#-Mzuq8T64zAdE-4RDa_7:-Mzuro4QB8kLP6wC9-dp:blpaztg) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Testing locally.
</blockquote></details>

OK Confirmed it works!

---
___
*[bazel_ros2_rules/ros2/defs.bzl, line 75 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/54#-MzurpqOD3AA1d-6w9zo:-MzurpqP95m17Btum39z:b-80oaj7) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/84219c62a0425cead80e8265cf342056fd2059a0/bazel_ros2_rules/ros2/defs.bzl#L75)):*
> ```Starlark
>     for package in repo_ctx.attr.exclude_packages:
>         cmd.extend(["-e", package])
>     cmd.extend(["-o", "distro_metadata.json"])
> ```

BTW I'm wondering Miche's invalidations may have been due to not declaring the file?
That being said, this is strictly better - thanks!

**Review by EricCousineau-TRI — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/54)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IanTheEngineer)

**Comment by sloretz** [comment]
*[bazel_ros2_rules/ros2/defs.bzl, line 75 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/54#-MzurpqOD3AA1d-6w9zo:-Mzusou1Dd5bLw0rqLbV:b6hhumf) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/84219c62a0425cead80e8265cf342056fd2059a0/bazel_ros2_rules/ros2/defs.bzl#L75)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW I'm wondering Miche's invalidations may have been due to not declaring the file?
That being said, this is strictly better - thanks!
</blockquote></details>

How do I declare these files? Is that a blocker to merging this?

**Review by EricCousineau-TRI — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/54)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IanTheEngineer)

___
*[bazel_ros2_rules/ros2/defs.bzl, line 75 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/54#-MzurpqOD3AA1d-6w9zo:-Mzv9zBI74uJuxzv-YD5:b57248x) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/84219c62a0425cead80e8265cf342056fd2059a0/bazel_ros2_rules/ros2/defs.bzl#L75)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

How do I declare these files? Is that a blocker to merging this?
</blockquote></details>

OK Not a blocker! Actually, I may have also been confused; `repository_ctx` does not seem to have `declare_file`:
https://docs.reviewable.io/discussions.html#checking-and-changing-dispositions

I was instead thinking about `ctx.actions.declare_file` (https://bazel.build/rules/lib/actions#declare_file), which is not for the loading phase (external repos) - sorry for the noise!

Just so ya know, Reviewable has disposition keywords that influence a PR's "approval status":
https://docs.reviewable.io/discussions.html#checking-and-changing-dispositions

**Review by IanTheEngineer — APPROVED** [review]
:lgtm: as well.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/54#-:-MzvAxQf49J6wV9Jp5m3:b7jneht)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

**Comment by sloretz** [comment]
Rebased without changes so PR job will pass.

**Pull request merged**
