### PR TITLE
Hotfix for rosidl cpp visibility header addition

### PR DESCRIPTION
**Pull request by calderpg-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/371)

### CODE REVIEW

**Review by IanTheEngineer — COMMENTED** [review]
+@IanTheEngineer for review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/371#-:-ODS0ygZ4oaZac1NMJjM:bavr1fn)* status: 0 of 1 files reviewed, all discussions resolved

**Review by IanTheEngineer — COMMENTED** [review]
I am in agreement that finding and using the actual template file on disk is preferable to having it here in string form. For future reference, the file is now located here:
`/opt/ros/humble/share/rosidl_generator_cpp/resource/rosidl_generator_cpp__visibility_control.hpp.in`

With that said, the required Bazel-structure to access this file is not immediately clear, so I am okay leaving this as a TODO for now.

:LGTM: Thank you for the quick patch, Calder.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/371#-:-ODS1Hjm0CDlnTM6nhCE:btob03w)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @calderpg-tri)

**Comment by jwnimmer-tri** [comment]
Let me know if you want me to force this into master (and if the PR title is what you want for the squashed commit subject).

**Review by calderpg-tri — COMMENTED** [review]
I've changed the title slightly. I believe @IanTheEngineer is going to try to fix the CI configuration here, but it's probably fine to force it into `main` for now.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/371#-:-ODSIW_c8EU1FNDSEdpN:b7etp3n)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @IanTheEngineer)

**Comment by jwnimmer-tri** [comment]
Okay, I've confirmed that the CI failure is not reproducible locally.  I'll force this in now.

**Comment by IanTheEngineer** [comment]
I was about to comment the same thing! I cannot reproduce the CI failure either. Thanks for merging, Jeremy.

**Comment by jwnimmer-tri** [comment]
I think the failure happens when the older ROS packages are installed but the newer code is being run -- and because the GHA CI doesn't run `apt upgrade` apparently the `image: ros:humble-ros-base-jammy` image doesn't have the latest packages yet.

**Pull request merged**
