### PR TITLE
Model-interop inital prereqs, README and CI

### PR DESCRIPTION
**Pull request by marcoag**
**Model-interop** provides an automated workflow to import articulated robots (URDF / SDFormat) from other ecosystems into Drake.

Initial setup with a README placeholder, setup/install_prereqs, along with a new setup for CI as requested in: https://github.com/EricCousineau-TRI/repro/pull/73#pullrequestreview-942789120.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/76)

### CODE REVIEW

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
+@ericcousineau-tri for review - first pass done, PTAL!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-:-N16hTecANMS16Z5Po5_:b-yh0l08)* status: all files reviewed, 6 unresolved discussions (waiting on @marcoag)

___
*[`.github/workflows/modelinterop.yml` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-N16h8K074J-qjEVQxkR:-N16h8K074J-qjEVQxkS:b-sqs7jq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e08965989f2f82ed216e034de62b0e6a8f7241f5/.github/workflows/modelinterop.yml#L1)):*
> ```YAML
> name: Model-interop Continuous Integration
> ```

nit Can you rename this file to be the same as the project dir?
___
*[`model_interop/README.md` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-N16hHFC8hZheLL3ZcPN:-N16hHFC8hZheLL3ZcPO:bvvsvv8) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e08965989f2f82ed216e034de62b0e6a8f7241f5/model_interop/README.md#L1)):*
> ```Markdown
> # Model interop
> ```

We should qualify this folder as `drake_model_interop`, as it should parallel other packages.here.
___
*[`model_interop/README.md` line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-N16hX2SAexVHo63R1oW:-N16hX2T9jdRl2ykmHSI:bwunn7k) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e08965989f2f82ed216e034de62b0e6a8f7241f5/model_interop/README.md#L5)):*
> ```Markdown
> ## About
> 
> This tool provides an automated workflow to import articulated robots (URDF / SDFormat) from other ecosystems into Drake.
> ```

nit Also, this automates testing.

Can you add that here?
___
*[`model_interop/README.md` line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-N16h_Xb7h69tS79_7C5:-N16h_Xb7h69tS79_7C6:b-bgvxz) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e08965989f2f82ed216e034de62b0e6a8f7241f5/model_interop/README.md#L14)):*
> ```Markdown
> sudo ./setup/install_prereqs.sh
> ```
> ```

nit Should add TODO to indicate this isn't complete yet?
___
*[`model_interop/setup/install_prereqs.sh` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-N16hdT64jrOEtGv46qT:-N16hdT64jrOEtGv46qU:b70nn15) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e08965989f2f82ed216e034de62b0e6a8f7241f5/model_interop/setup/install_prereqs.sh#L1)):*
> ```Shell
> apt-get update
> ```

All bash scripts need `set -eu` (and `-o pipefail`) unless there's an explicit reason not to have it.
___
*[`model_interop/setup/install_prereqs.sh` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-N16hhqk4Z1IBjsPeDch:-N16hhql6jDSLTjJjyGc:b-e79679) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e08965989f2f82ed216e034de62b0e6a8f7241f5/model_interop/setup/install_prereqs.sh#L1)):*
> ```Shell
> apt-get update
> ```

nit For traceability on CI, be sure to also have `set -x`. (to combine with above, `set -eux -o pipefail`)

**Review by marcoag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/76)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`.github/workflows/modelinterop.yml` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-N16h8K074J-qjEVQxkR:-N1HU_6f6gL0ZwZvNp7G:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e08965989f2f82ed216e034de62b0e6a8f7241f5/.github/workflows/modelinterop.yml#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you rename this file to be the same as the project dir?
</blockquote></details>

Done.
___
*[`model_interop/README.md` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-N16hHFC8hZheLL3ZcPN:-N1HgoCu4NEEhtoxoJUN:bybsb35) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e08965989f2f82ed216e034de62b0e6a8f7241f5/model_interop/README.md#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

We should qualify this folder as `drake_model_interop`, as it should parallel other packages.here.
</blockquote></details>

True, changed the name.
___
*[`model_interop/README.md` line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-N16hX2SAexVHo63R1oW:-N1HV5v2BAHmMDM4Tzmo:bqmjwcz) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e08965989f2f82ed216e034de62b0e6a8f7241f5/model_interop/README.md#L5)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Also, this automates testing.

Can you add that here?
</blockquote></details>

Added.
___
*[`model_interop/README.md` line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-N16h_Xb7h69tS79_7C5:-N1HV83fD1w5O9KwL2Of:b-1woebw) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e08965989f2f82ed216e034de62b0e6a8f7241f5/model_interop/README.md#L14)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Should add TODO to indicate this isn't complete yet?
</blockquote></details>

Yup, will complete when I add the scripts into the repo.
___
*[`model_interop/setup/install_prereqs.sh` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-N16hdT64jrOEtGv46qT:-N1HVwHF2FUQgaYJvnH2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e08965989f2f82ed216e034de62b0e6a8f7241f5/model_interop/setup/install_prereqs.sh#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

All bash scripts need `set -eu` (and `-o pipefail`) unless there's an explicit reason not to have it.
</blockquote></details>

Done.
___
*[`model_interop/setup/install_prereqs.sh` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-N16hhqk4Z1IBjsPeDch:-N1HVzI6Aups4gVl6JcU:b642pzi) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e08965989f2f82ed216e034de62b0e6a8f7241f5/model_interop/setup/install_prereqs.sh#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For traceability on CI, be sure to also have `set -x`. (to combine with above, `set -eux -o pipefail`)
</blockquote></details>

Yup, added `set -eux -o pipefail`.

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm: with two small nits on titles / names - thanks!

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-:-N1JD8N3-sVhmgsib2r6:b-3v9yba)* status: all files reviewed, 2 unresolved discussions (waiting on @marcoag)

___
*[`.github/workflows/drake_model_interop.yml` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-N1JCwes3P9ofI772_1w:-N1JCwes3P9ofI772_1x:b-3psy8y) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/32d57c6b65d4ef1bc3975399beeecafc1255e7ef/.github/workflows/drake_model_interop.yml#L1)):*
> ```YAML
> name: Model-interop Continuous Integration
> ```

nit Can you reflect proper name here too? `drake_model_interop`?
___
*[`drake_model_interop/README.md` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-N1JD-nx4FqrrGWlio0r:-N1JD-nx4FqrrGWlio0s:b-u8uouy) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/32d57c6b65d4ef1bc3975399beeecafc1255e7ef/drake_model_interop/README.md#L1)):*
> ```Markdown
> # Model interop
> ```

nit Can you change heading to `Drake Model Interop`?

**Review by marcoag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/76)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

___
*[`.github/workflows/drake_model_interop.yml` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-N1JCwes3P9ofI772_1w:-N1JU0eo9ZQjUtt76UAP:bs7wumb) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/32d57c6b65d4ef1bc3975399beeecafc1255e7ef/.github/workflows/drake_model_interop.yml#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you reflect proper name here too? `drake_model_interop`?
</blockquote></details>

Done.
___
*[`drake_model_interop/README.md` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-N1JD-nx4FqrrGWlio0r:-N1JU4HLDFrsiNRDi8wa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/32d57c6b65d4ef1bc3975399beeecafc1255e7ef/drake_model_interop/README.md#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you change heading to `Drake Model Interop`?
</blockquote></details>

Done.

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/76)* status: all files reviewed, 1 unresolved discussion (waiting on @marcoag)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-N1JVXZ37BamQqo49uSo:-N1JVXZ37BamQqo49uSp:ba8vn8w) (no related file):*
CI is currently failing:
https://github.com/RobotLocomotion/drake-ros/runs/6307442699?check_suite_focus=true

Perhaps a missing field?

---

**Review by marcoag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/76)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-N1JVXZ37BamQqo49uSo:-N1JlBVi9nGSBbwurY9p:be513pl) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

CI is currently failing:
https://github.com/RobotLocomotion/drake-ros/runs/6307442699?check_suite_focus=true

Perhaps a missing field?
</blockquote></details>

It is most probably the working directory since I changed the name as you suggested but forgot to update it in the CI.

---

**Review by EricCousineau-TRI — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/76)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marcoag)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/76#-N1JVXZ37BamQqo49uSo:-N1JnRei9r3KgpIEf90o:b-w196av) (no related file):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

It is most probably the working directory since I changed the name as you suggested but forgot to update it in the CI.
</blockquote></details>

OK Thanks!

---

**Pull request merged**
