### PR TITLE
[ci] Drop galactic testing

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Address TODO pending moving past ROS 2 Galactic

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/192)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@cottsay for review, please! \cc @sloretz 

In view of driving towards Ubuntu 22.04 Jammy and keeping apace w/ ROS 2 Humble and Rolling, I'd like to stop worrying about constraints / overhead induced by ROS 2 Galactic.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/192#-:-NH9xQzK36x4cXrO7Vxs:b-gmoetc)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @cottsay)

**Comment by EricCousineau-TRI** [comment]
("driving towards Ubuntu 22.04 Jammy" => more specifically, that TRI Dex Manip is going to upgrade to it)

**Review by sloretz — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/192)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cottsay)

**Review by EricCousineau-TRI — COMMENTED** [review]
Thanks Shane! I'll take your review for moving ahead.
I've also dropped the `NOLINT` specifier - something still breaks and I don't feel like figuring out why.

-@cottsay +@sloretz 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/192#-:-NHRKMXq-kPsnMGaDr4C:b7gv12c)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @sloretz)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/192)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Pull request merged**
