### PR TITLE
Ensure all ROS 2 Bazel projects use .bazelrc testing setup

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
As noticed in https://github.com/RobotLocomotion/drake-ros/pull/295#pullrequestreview-1581431056

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/297)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@IanTheEngineer for review, please! I could use some help on organizing, though - if you have suggestions, could I ask you to make a meta PR?
\cc @calderpg-tri

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/297#-:-Nc9b1CRAQjY7BigrYeS:b-9l8mp4)* status: 0 of 23 files reviewed, all discussions resolved (waiting on @IanTheEngineer)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/297)* status: 0 of 23 files reviewed, all discussions resolved (waiting on @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/297#-NfC4Ft174LzoZxTqDgi:-NfCn4kZ0QMzvL5k4Cv_:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: This PR currently does two things - try to ensure build flags are the same to help caching, and then ensure test flags are the same to force isolation.

I'm going to split the caching portion off of this, and make this PR only responsible for isolation flags.
</blockquote></details>

Done.

___

**Review by IanTheEngineer — APPROVED** [review]
:LGTM: Thanks for the update, Eric. These changes look good to me, and seem reasonable to help with ROS test isolation.

@adityapande-1995 , the CI failure in this PR claims to be due to running out of space. I know you've been looking into this on other PR's. Do you have any insight on solutions?

> Reviewed 18 of 19 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/297#-:-NfD1jHaE5-BhlktFy-5:b-q19v86)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`bazel_ros2_rules/ros2/resources/bazel_ros_env/bazel_ros_env.py` line 1 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ros/297#-NfCzxnv6jAJf9LCdSez:-NfCzxnv6jAJf9LCdSf-:b-b30t9g) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/f04cf92cb95ed71b417f39be2798493bfbf18fc0/bazel_ros2_rules/ros2/resources/bazel_ros_env/bazel_ros_env.py#L1)):*
> ```Python
> # TODO(eric.cousineau): Move RMW + ROS isolation to a location accessible by
> ```

BTW: The TODO is perfectly fine here, but to keep track a a higher level an issue would be helpful.

**Review by EricCousineau-TRI — COMMENTED** [review]
Thanks!

> the CI failure in this PR claims to be due to running out of space

Aye, mentioned in https://github.com/RobotLocomotion/drake-ros/issues/247#issuecomment-1734387985
My plan is to run testing locally, then merge it.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/297#-:-NfDSy3k5GrX09U28Nev:b8omrwf)* status: 22 of 23 files reviewed, all discussions resolved (waiting on @IanTheEngineer)

___
*[`bazel_ros2_rules/ros2/resources/bazel_ros_env/bazel_ros_env.py` line 1 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ros/297#-NfCzxnv6jAJf9LCdSez:-NfDSvvUA2itrqkTYr_1:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/f04cf92cb95ed71b417f39be2798493bfbf18fc0/bazel_ros2_rules/ros2/resources/bazel_ros_env/bazel_ros_env.py#L1)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

BTW: The TODO is perfectly fine here, but to keep track a a higher level an issue would be helpful.
</blockquote></details>

Done.

**Comment by EricCousineau-TRI** [comment]
Local testing passed, merging forward.

**Pull request merged**
