### PR TITLE
setup: Use Bazel 5.1.0

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
In parallel w/ Anzu PR 8708, Drake PR https://github.com/RobotLocomotion/drake/pull/16878

\cc @IanTheEngineer

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/62)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sloretz for review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/62#-:-N-NOQR43_-DZczsiKnF:b-ioi1p3)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @sloretz)

**Review by IanTheEngineer — CHANGES_REQUESTED** [review]
I know I'm only a CC, but I figured I'd take a look. Question below:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/62#-:-N-O-J-lCUTR2Gk5ZzbG:b-y2zgih)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sloretz)

___
*[ros2_example_bazel_installed/setup/install_prereqs.sh, line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/62#-N-NzrtV4VbJT4Gdez2e:-N-NzrtV4VbJT4Gdez2f:b-pfz6gg) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5a808fa412ebf209d603711738a1de3c901b0e85/ros2_example_bazel_installed/setup/install_prereqs.sh#L61)):*
> ```Shell
> apt install g++ unzip zlib1g-dev
> 
> dpkg_install_from_wget \
> ```

I'm poking around to see where this function is defined. Is it missing? Why change from `dpkg_install_from_curl`?



_Code quote:_
```Shell
dpkg_install_from_wget
```

**Review by IanTheEngineer — COMMENTED** [review]
:lgtm: Thanks for the update!

> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/62#-:-N-OTX55-e-DtokyQe4_:b-k19lhy)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @IanTheEngineer and @sloretz)

**Review by sloretz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/62#-:-N-P3MWa-yPV92-Jdylt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Pull request merged**
