### PR TITLE
Add Ament hook to put libdrake.so in LD_LIBRARY_PATH

### LINKED ISSUE #139: Should add ament env hook to make `libdrake.so` discoverable via `LD_LIBRARY_PATH`
Per discussion:
https://github.com/RobotLocomotion/drake-ros/pull/133#pullrequestreview-1111378271

As @sloretz pointed out, relates first bullet point in #135

Goal would be to add the hook to `drake_ros_core`, then remove the `LD_LIBRARY_PATH` changes to CI.

### PR DESCRIPTION
**Pull request by cottsay**
Closes #139

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/143)

### CODE REVIEW

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm_strong: with some code nits / requests for more comments

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/143#-:-NCea4NCCNqODXp9Vh1K:bfw0h85)* status: all files reviewed, 4 unresolved discussions (waiting on @cottsay)

___
*[`drake_ros_core/CMakeLists.txt` line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/143#-NCe_t-aE9TTyrbBMtbK:-NCe_t-aE9TTyrbBMtbL:bnx83iy) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/44873bac55a8b6cce3d0f803f06716c1109f36fe/drake_ros_core/CMakeLists.txt#L88)):*
> ```CMake
> ### End Python bindings
> 
> ### Drake library path environment hook
> ```

nit Location of this code does not entirely make sense to me.

It seems like this would make more sense collocated with / placed after `ament_export_dependencies(drake)` ?
___
*[`drake_ros_core/CMakeLists.txt` line 89 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/143#-NCeZQQFEzQ9cJi0VWnI:-NCeZQQGAM2AZ0vBhERV:b-y1o7c4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/44873bac55a8b6cce3d0f803f06716c1109f36fe/drake_ros_core/CMakeLists.txt#L89)):*
> ```CMake
> 
> ### Drake library path environment hook
> if(NOT WIN32)
> ```

nit Not sure if I understand the `NOT WIN32` part.

Drake itself does not support windows.
Should we instead just do the equivalent of `assert NOT WIN32` rather than nesting this logic?
___
*[`drake_ros_core/CMakeLists.txt` line 92 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/143#-NCeZjQd7pFvrloNZkRl:-NCeZjQd7pFvrloNZkRm:b-4k47yv) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/44873bac55a8b6cce3d0f803f06716c1109f36fe/drake_ros_core/CMakeLists.txt#L92)):*
> ```CMake
>   get_target_property(DRAKE_LIBRARY drake::drake LOCATION)
>   get_filename_component(DRAKE_LIBRARY_DIR ${DRAKE_LIBRARY} DIRECTORY)
>   set(LIBRARY_PATH_HOOK "${AMENT_PACKAGE_TEMPLATE_DIR}/environment_hook/library_path.sh")
> ```

nit Seeing usage of generated file `.sh` before its template `.sh.in` is a bit confusing, esp. that they're so far apart.

I assume `LIBRARY_PATH_HOOK` is some undeclared prereq for `AMENT_CMAKE_ENVIRONMENT_HOOKS` and `ament_environment_hooks`?
If so, can you place this immediately before their invocation, with some description of how it influences things?
(perhaps link to the documentation, if it states as much?)
___
*[`drake_ros_core/env-hooks/drake_library_path.sh.in` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/143#-NCe_FcjBT3S3AXSnqrQ:-NCe_FcjBT3S3AXSnqrR:b67ynug) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/44873bac55a8b6cce3d0f803f06716c1109f36fe/drake_ros_core/env-hooks/drake_library_path.sh.in#L1)):*
> ```
> ament_prepend_unique_value "@LIBRARY_PATH_ENV_VAR@" "@DRAKE_LIBRARY_DIR@"
> ```

nit Missing context, may be unclear to others when/if to remove.

Consider mentioning in comment?
```
# Ensures that ament-style linking (no RPATH) plays well with what Drake itself provides (only RPATH).
# See drake-ros#139 for more details.
```

**Review by cottsay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/143)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`drake_ros_core/CMakeLists.txt` line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/143#-NCe_t-aE9TTyrbBMtbK:-NCfBqPg81qh2FGdRe8T:bvtxfrd) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/44873bac55a8b6cce3d0f803f06716c1109f36fe/drake_ros_core/CMakeLists.txt#L88)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Location of this code does not entirely make sense to me.

It seems like this would make more sense collocated with / placed after `ament_export_dependencies(drake)` ?
</blockquote></details>

Sure, moved.
___
*[`drake_ros_core/CMakeLists.txt` line 89 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/143#-NCeZQQFEzQ9cJi0VWnI:-NCfBs7z-8v-cQiIStOF:b-tzgtzv) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/44873bac55a8b6cce3d0f803f06716c1109f36fe/drake_ros_core/CMakeLists.txt#L89)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Not sure if I understand the `NOT WIN32` part.

Drake itself does not support windows.
Should we instead just do the equivalent of `assert NOT WIN32` rather than nesting this logic?
</blockquote></details>

This was mostly conforming to existing patterns throughout ROS, where WIN32 is a supported platform. Since it's confusing in this context, I just dropped the conditional.
___
*[`drake_ros_core/CMakeLists.txt` line 92 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/143#-NCeZjQd7pFvrloNZkRl:-NCfC3Ho6wqelWNWoucm:b1wfooa) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/44873bac55a8b6cce3d0f803f06716c1109f36fe/drake_ros_core/CMakeLists.txt#L92)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Seeing usage of generated file `.sh` before its template `.sh.in` is a bit confusing, esp. that they're so far apart.

I assume `LIBRARY_PATH_HOOK` is some undeclared prereq for `AMENT_CMAKE_ENVIRONMENT_HOOKS` and `ament_environment_hooks`?
If so, can you place this immediately before their invocation, with some description of how it influences things?
(perhaps link to the documentation, if it states as much?)
</blockquote></details>

This was a holdover from experiments developing the change that I forgot to remove. I dropped the variable.
___
*[`drake_ros_core/env-hooks/drake_library_path.sh.in` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/143#-NCe_FcjBT3S3AXSnqrQ:-NCfCE-m6OocCPxb_khJ:b-omb5dc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/44873bac55a8b6cce3d0f803f06716c1109f36fe/drake_ros_core/env-hooks/drake_library_path.sh.in#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Missing context, may be unclear to others when/if to remove.

Consider mentioning in comment?
```
# Ensures that ament-style linking (no RPATH) plays well with what Drake itself provides (only RPATH).
# See drake-ros#139 for more details.
```
</blockquote></details>

Sure, added. I also added a note about the source of file, which is common among CMake templates in ROS.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/143)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @cottsay and @EricCousineau-TRI)

___
*[`drake_ros_core/CMakeLists.txt` line 89 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/143#-NCeZQQFEzQ9cJi0VWnI:-NCfZz1i7YUQF3xcZsvn:b-w196av) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/44873bac55a8b6cce3d0f803f06716c1109f36fe/drake_ros_core/CMakeLists.txt#L89)):*
<details><summary><i>Previously, cottsay (Scott K Logan) wrote…</i></summary><blockquote>

This was mostly conforming to existing patterns throughout ROS, where WIN32 is a supported platform. Since it's confusing in this context, I just dropped the conditional.
</blockquote></details>

OK Thanks!
___
*[`drake_ros_core/CMakeLists.txt` line 92 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/143#-NCeZjQd7pFvrloNZkRl:-NCf_1g4CFio2u-WiIGI:b-9prov1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/44873bac55a8b6cce3d0f803f06716c1109f36fe/drake_ros_core/CMakeLists.txt#L92)):*
<details><summary><i>Previously, cottsay (Scott K Logan) wrote…</i></summary><blockquote>

This was a holdover from experiments developing the change that I forgot to remove. I dropped the variable.
</blockquote></details>

OK Sweet, much better!
___
*[`drake_ros_core/CMakeLists.txt` line 66 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/143#-NCfZqLR3q25P9CPLMjB:-NCfZqLS85Qw8klvYxKh:b-skyzyl) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/dbd46719b9a391cf4125346a0eaf9fcca5ab9cd0/drake_ros_core/CMakeLists.txt#L66)):*
> ```CMake
> ament_environment_hooks("env-hooks/drake_library_path.sh.in")
> 
> install(TARGETS ${PROJECT_NAME} EXPORT ${PROJECT_NAME}
> ```

nit Perhaps want to introduce a subheading here, just to distinguish from Drake? e.g.
```
# Nominal ament install directives.
```
___
*[`drake_ros_core/env-hooks/drake_library_path.sh.in` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/143#-NCe_FcjBT3S3AXSnqrQ:-NCf_BYRB-Nr5m2oeJH0:b-5b6tzb) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/44873bac55a8b6cce3d0f803f06716c1109f36fe/drake_ros_core/env-hooks/drake_library_path.sh.in#L1)):*
<details><summary><i>Previously, cottsay (Scott K Logan) wrote…</i></summary><blockquote>

Sure, added. I also added a note about the source of file, which is common among CMake templates in ROS.
</blockquote></details>

OK Ah, kind of confusing from my first read on it (looked like accident where it was the same file), but I see now.
Requesting clarification above.
___
*[`drake_ros_core/env-hooks/drake_library_path.sh.in` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/143#-NCf_GRpDRUiDfREtQM1:-NCf_5XC7D3QIBHWZbvX:bktng1p) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/dbd46719b9a391cf4125346a0eaf9fcca5ab9cd0/drake_ros_core/env-hooks/drake_library_path.sh.in#L1)):*
> ```
> # copied from drake_ros_core/env-hooks/drake_library_path.sh.in
> ```

nit The word "copied" seems incorrect here, and may be confusing for users unfamiliar with this convention.

Consider "Generated from template file /a/b/c.sh.in"

**Review by EricCousineau-TRI — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/143)* status: all files reviewed, 4 unresolved discussions (waiting on @cottsay)

**Review by EricCousineau-TRI — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/143)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cottsay)

**Comment by EricCousineau-TRI** [comment]
Thanks!

**Pull request merged**
