### PR TITLE
Follow Drake Python binding conventions more closely

### LINKED ISSUE #168: pybind: Modules should follow Drake pybind11 naming conventions
See https://drake.mit.edu/doxygen_cxx/group__python__bindings.html

* Modules should end with `_py.cc`.
* I am not sure we need separate directory `python_bindings` for now. Let's consider Python first-class citizen (as is done in Anzu).
* We should expose pybind11 helper headers publicly as `_pybind.h` (while we're in unstable / experimental mode)
* We should leverage `py` alias in header files

Ran into this while working on #169 

\cc @sloretz @IanTheEngineer

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #168

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/171)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sloretz for review, please!
\cc @iantheengineer 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/171#-:-NEv9FEb-Qoykn2V3lut:b-goik91)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @sloretz)

**Review by IanTheEngineer — COMMENTED** [review]
I like the conventions you've brought forth here from `pydrake`. The shallower directory structure, more consistent use of namespacing, and the general increasing of Python's visibility all look great.

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/171#-:-NFPjroJBpRrLeNBegmO:b-67lznh)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sloretz)

___
*[`drake_ros_core/BUILD.bazel` line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/171#-NFPlpaNDx3kwBamtJ3G:-NFPlpaO-AfmVc7B-U2v:b3cmjok) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a391b1c412d3d46bcf05af5ce72d5fcd15f1840c/drake_ros_core/BUILD.bazel#L24)):*
> ```Starlark
>   hdrs = glob(
>     ["include/**/*.h"],
>     exclude = PYBIND_EXCLUDES,
> ```

BTW: Nice use of the `exclude` argument. This does make for cleaner BUILD-file reading.



_Code quote:_
```Starlark
exclude = PYBIND_EXCLUDES,
```
___
*[`drake_ros_core/include/drake_ros_core/drake_ros_core_pybind.h` line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/171#-NFPlDI50oDcEA-Ipmm9:-NFPlDI6AF5f6lu9ylMs:b-l2zksk) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a391b1c412d3d46bcf05af5ce72d5fcd15f1840c/drake_ros_core/include/drake_ros_core/drake_ros_core_pybind.h#L3)):*
> ```objc
> #pragma once
> 
> // Provides centralized pybind11 alias and utilities for use in headers for
> ```

 BTW, In #168, you mentioned 
```
We should expose pybind11 helper headers publicly as _pybind.h (while we're in unstable / experimental mode)
```
which I see you've done in here. How would you anticipate we handle the public `*_pybind.h`headers when we're in more of a stable / mature mode?

**Review by IanTheEngineer — APPROVED** [review]
I might as well take over this review as I've already inspected it. 

+@iantheengineer for review, -@sloretz.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/171#-:-NFPn-SgEC1IK6bU1YOt:bjc2g0n)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Thanks!
\cc @jwnimmer-tri re: stability considerations

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/171#-:-NFPo3OYBKWGycYgXSNM:b-1o4wk1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

___
*[`drake_ros_core/BUILD.bazel` line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/171#-NFPlpaNDx3kwBamtJ3G:-NFPnciDAr2IwMuP855v:b-w196av) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a391b1c412d3d46bcf05af5ce72d5fcd15f1840c/drake_ros_core/BUILD.bazel#L24)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

BTW: Nice use of the `exclude` argument. This does make for cleaner BUILD-file reading.
</blockquote></details>

OK Thanks!
___
*[`drake_ros_core/include/drake_ros_core/drake_ros_core_pybind.h` line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/171#-NFPlDI50oDcEA-Ipmm9:-NFPnef0AaIobA6swBWZ:bt7w3il) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a391b1c412d3d46bcf05af5ce72d5fcd15f1840c/drake_ros_core/include/drake_ros_core/drake_ros_core_pybind.h#L3)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

 BTW, In #168, you mentioned 
```
We should expose pybind11 helper headers publicly as _pybind.h (while we're in unstable / experimental mode)
```
which I see you've done in here. How would you anticipate we handle the public `*_pybind.h`headers when we're in more of a stable / mature mode? 
</blockquote></details>

I envision we would treat it similarly to Drake, in that we define our API stability promise, and either explicitly include or exclude them.

I'm not sure if we've encountered a case where we needed to deprecate `pybind` helpers, so we could exclude those from promises initially.

**Pull request merged**
