### PR TITLE
Bump to use Drake v1.13.0

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
lint: Use symlink drake.bzl

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/242)

### CODE REVIEW

**Review by sloretz — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/242)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/242)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/242#-NPrOxTZ3RPRrOZvkpcA:-NPrOxT_7eGlLx1ilFku:bcez615) (no related file):*
Working: Unclear why colcon build against Humble is failing.

I am unable to reproduce this locally (on Apptainer) using https://github.com/RobotLocomotion/drake/tree/f062738a338ab26776d24c14e6d5d79b2280a79c
Will see if this happens if I update my container to latest Drake.

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/242)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/242#-NPrOxTZ3RPRrOZvkpcA:-NPt3YLY8ueRD0u1EVka:b-wxk72s) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Unclear why colcon build against Humble is failing.

I am unable to reproduce this locally (on Apptainer) using https://github.com/RobotLocomotion/drake/tree/f062738a338ab26776d24c14e6d5d79b2280a79c
Will see if this happens if I update my container to latest Drake.
</blockquote></details>

Just got back to this. Upgrade Drake causes the issue, so it's somewhere in this commit range:
https://github.com/RobotLocomotion/drake/compare/v1.13.0...42d86973

I believe the test fails because something in Drake changed to alter how geometries are reported in the past few weeks.

However, I plan to just update the test to be a bit more flexible.

___

**Review by sloretz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/242)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/242#-NPrOxTZ3RPRrOZvkpcA:-NPt52HgE2lLisOLTSGp:b9dncbm) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Just got back to this. Upgrade Drake causes the issue, so it's somewhere in this commit range:
https://github.com/RobotLocomotion/drake/compare/v1.13.0...42d86973

I believe the test fails because something in Drake changed to alter how geometries are reported in the past few weeks.

However, I plan to just update the test to be a bit more flexible.
</blockquote></details>

I recall we talked about pinning in the meeting today. Since we already pin for bazel, maybe `robotlocomotion/drake:jammy-1.13.0`would be the right tag in these two places

https://hub.docker.com/layers/robotlocomotion/drake/jammy-1.13.0/images/sha256-37c55fe7d376e9c5b80a8ee565f06785217ae47be8f200cbe9a08b483f3304ba?context=explore

https://github.com/RobotLocomotion/drake-ros/blob/94a32508bb7e1e1cfb5c422ac7a64bc836d9dd3d/.github/workflows/main.yml#L24
https://github.com/RobotLocomotion/drake-ros/blob/94a32508bb7e1e1cfb5c422ac7a64bc836d9dd3d/.github/workflows/main.yml#L52

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/242)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/242#-NPrOxTZ3RPRrOZvkpcA:-NPtBU5wAYEhsstrD3aF:b1lkqa4) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I recall we talked about pinning in the meeting today. Since we already pin for bazel, maybe `robotlocomotion/drake:jammy-1.13.0`would be the right tag in these two places

https://hub.docker.com/layers/robotlocomotion/drake/jammy-1.13.0/images/sha256-37c55fe7d376e9c5b80a8ee565f06785217ae47be8f200cbe9a08b483f3304ba?context=explore

https://github.com/RobotLocomotion/drake-ros/blob/94a32508bb7e1e1cfb5c422ac7a64bc836d9dd3d/.github/workflows/main.yml#L24
https://github.com/RobotLocomotion/drake-ros/blob/94a32508bb7e1e1cfb5c422ac7a64bc836d9dd3d/.github/workflows/main.yml#L52
</blockquote></details>

OK For this situation, I prefer we keep canary builds alive, so I would prefer we focus on that in its own PR.
However, I think it's worth noting this for the future! (will file issue)

___

**Comment by EricCousineau-TRI** [comment]
Gonna skip last job (maybe we need to fix the caching issues in ci?)

**Pull request merged**
