### PR TITLE
Add C++ and Python dload shim libaries to minimize generated code

### LINKED ISSUE #108: dload: Clean up items
- [x] Minimize generated code. At present, for C++, the [template code is ~80 lines long](https://github.com/RobotLocomotion/drake-ros/blob/1e4da97bc8ad15a0a595e29c2ea390526dd8b3ed/bazel_ros2_rules/ros2/tools/dload_cc.bzl#L14-L94), with character escaping. For both C++ and Python, we should break this down and provide libraries that are then used via `ros_cc` and `ros_py`.
- [x] Do not re-shim environment variables. At present, there are no checks that we're already shimming. We should ideally say something like `_BAZEL_ROS_RULES_SHIM`. If set, we should not inject *any* new environment variables (that should be controlled by entrypoint, similar to runfiles as shown in #106). If unset, then we set env vars, and set this sentinel. This should happen in both C++ and Python.

\cc @IanTheEngineer @sloretz

### PR DESCRIPTION
**Pull request by sloretz**
Resolves #108

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/130)

### CODE REVIEW

**Review by sloretz — COMMENTED** [review]
+@ericcousineau-tri for review please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/130#-:-NAvPbAgB9g8o0QWFU-p:btxkahr)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm_strong: with some minor stuff here and there - much better!

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/130#-:-NAvw1xoCbxQe6WULehx:b-dwbcc6)* status: all files reviewed, 6 unresolved discussions (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/130#-NAvvbppCfmhjqkTac53:-NAvvbppCfmhjqkTac54:btay56g) (no related file):*
nit For both C++ and Python, the results of `_to_cc_list` and `_to_py_list` are not easy to read.

Can you add some simple heuristics to make that a bit more digestible by human eyes? e.g.

```py
def _should_multiline(items, start):
   total_len = 0
   for item in items:
     total_len += len(item)
     if len(item) > 50 or item.startswith(start) or "\n" in item:
       return True
     if total_len > 70:
       return True

def to_list(items, start, end):
  if _should_multiline(items, start):
    return start + indent(",\n".join(items), "  ") + end
  else:
    return start + ", ".join(items) + end

def _to_cc_list(items):
  return to_list(items, "{", "})

def _to_py_list(items):
   return to_list(items, "[", "]")
```

(I assume starlark utilities may have something like `indent()` in them?)

___
___
*[`bazel_ros2_rules/ros2/tools/dload_cc.bzl` line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/130#-NAvsBmX7MtEjpIN3e9B:-NAvsBmX7MtEjpIN3e9C:b-7vnuwy) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2f8aec71e1beae67a37fd8f678315a50e5c98368/bazel_ros2_rules/ros2/tools/dload_cc.bzl#L18)):*
> ```Starlark
> 
> int main(int argc, const char * argv[]) {{
>   return do_dload_shim(argc, argv, "{executable_path}", {names}, {actions});
> ```

nit For slightly improved readability, can you do something like this?

```
const std::string executable_path = "{executable_path}";
const std::vector<std::string> names = {names};
const std::vector<std::vector<std::string>> actions = {actions};
return do_dload_shim(argc, argv( executable_path, names, actions);
```
___
*[`bazel_ros2_rules/ros2/tools/dload_py.bzl` line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/130#-NAvvYoP3yUvpUBYggjW:-NAvvYoP3yUvpUBYggjX:b-snuff8) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2f8aec71e1beae67a37fd8f678315a50e5c98368/bazel_ros2_rules/ros2/tools/dload_py.bzl#L18)):*
> ```Starlark
> assert __name__ == "__main__"
> from bazel_ros2_rules.ros2.tools.dload_shim import do_dload_shim
> do_dload_shim("{executable_path}", {names}, {actions})
> ```

nit Same as above - can you assign interpolated values to variables here?
___
*[`bazel_ros2_rules/ros2/tools/dload_shim.h` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/130#-NAvtCOAD0gV6ww88982:-NAvtCOAD0gV6ww88983:b-bjcflf) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2f8aec71e1beae67a37fd8f678315a50e5c98368/bazel_ros2_rules/ros2/tools/dload_shim.h#L1)):*
> ```objc
> #include <string>
> ```

nit Needs `#pragma once`
___
*[`bazel_ros2_rules/ros2/tools/dload_shim.h` line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/130#-NAvt8qvCDCmdZ3-kRdZ:-NAvt8qvCDCmdZ3-kRd_:b-63drcf) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2f8aec71e1beae67a37fd8f678315a50e5c98368/bazel_ros2_rules/ros2/tools/dload_shim.h#L4)):*
> ```objc
> #include <vector>
> 
> int do_dload_shim(
> ```

nit Can you add brief docstring to this function?
___
*[`bazel_ros2_rules/ros2/tools/dload_shim.cc` line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/130#-NAvsZK5-BCkhF6OIco0:-NAvsZK5-BCkhF6OIco1:balbw4t) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2f8aec71e1beae67a37fd8f678315a50e5c98368/bazel_ros2_rules/ros2/tools/dload_shim.cc#L95)):*
> ```cpp
>         }
>       } else {
>         assert(false);  // should never get here
> ```

nit `assert(false)` may do nothing if NDEBUG is defined.

Can you instead call `std::abort()` or something like that?

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/130)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/130#-NAvvbppCfmhjqkTac53:-NAzWoC4-C6zN6JSep-u:btfu21a) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For both C++ and Python, the results of `_to_cc_list` and `_to_py_list` are not easy to read.

Can you add some simple heuristics to make that a bit more digestible by human eyes? e.g.

```py
def _should_multiline(items, start):
   total_len = 0
   for item in items:
     total_len += len(item)
     if len(item) > 50 or item.startswith(start) or "\n" in item:
       return True
     if total_len > 70:
       return True

def to_list(items, start, end):
  if _should_multiline(items, start):
    return start + indent(",\n".join(items), "  ") + end
  else:
    return start + ", ".join(items) + end

def _to_cc_list(items):
  return to_list(items, "{", "})

def _to_py_list(items):
   return to_list(items, "[", "]")
```

(I assume starlark utilities may have something like `indent()` in them?)
</blockquote></details>

I spent some time on this, but I wasn't able to come up with anything I can say is definitely better.

As a workaround I'd recommend viewing generated files with `clang-format`. Here's a handy function if `bash` is your shell.

```bash
pretty-cc() { clang-format --style=Google "$1" | vim -R - ; }

# Example 
pretty-cc ~/.cache/bazel/_bazel_osrf/*/execroot/ros2_example_bazel_installed/bazel-out/k8-opt/bin/_shimmed_sentinel_cc_shim.cc
```

___
___
*[`bazel_ros2_rules/ros2/tools/dload_cc.bzl` line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/130#-NAvsBmX7MtEjpIN3e9B:-NAzO7mo9_LJRbjNSERO:b96ya5g) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2f8aec71e1beae67a37fd8f678315a50e5c98368/bazel_ros2_rules/ros2/tools/dload_cc.bzl#L18)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For slightly improved readability, can you do something like this?

```
const std::string executable_path = "{executable_path}";
const std::vector<std::string> names = {names};
const std::vector<std::vector<std::string>> actions = {actions};
return do_dload_shim(argc, argv( executable_path, names, actions);
```
</blockquote></details>

Added intermediate variables in 36f4a37
___
*[`bazel_ros2_rules/ros2/tools/dload_py.bzl` line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/130#-NAvvYoP3yUvpUBYggjW:-NAzO5mT2spMBd8VFn8O:b96ya5g) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2f8aec71e1beae67a37fd8f678315a50e5c98368/bazel_ros2_rules/ros2/tools/dload_py.bzl#L18)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Same as above - can you assign interpolated values to variables here?
</blockquote></details>

Added intermediate variables in 36f4a37
___
*[`bazel_ros2_rules/ros2/tools/dload_shim.h` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/130#-NAvtCOAD0gV6ww88982:-NAzAcmQ8PJAvwv8MKNY:be86ta2) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2f8aec71e1beae67a37fd8f678315a50e5c98368/bazel_ros2_rules/ros2/tools/dload_shim.h#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Needs `#pragma once`
</blockquote></details>

`#pragma once` in b2880a9
___
*[`bazel_ros2_rules/ros2/tools/dload_shim.h` line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/130#-NAvt8qvCDCmdZ3-kRdZ:-NAzDUU167GYn0DndVEC:b-rw482a) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2f8aec71e1beae67a37fd8f678315a50e5c98368/bazel_ros2_rules/ros2/tools/dload_shim.h#L4)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you add brief docstring to this function?
</blockquote></details>

Added documentation in b8d5cac
___
*[`bazel_ros2_rules/ros2/tools/dload_shim.cc` line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/130#-NAvsZK5-BCkhF6OIco0:-NAzA8Kp2IS4YV-6FOVN:bm4xo3l) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2f8aec71e1beae67a37fd8f678315a50e5c98368/bazel_ros2_rules/ros2/tools/dload_shim.cc#L95)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `assert(false)` may do nothing if NDEBUG is defined.

Can you instead call `std::abort()` or something like that?
</blockquote></details>

Using `std::abort()` in bc673022199c2a8e109046ea4f1dfc43cc0ac02e

**Review by EricCousineau-TRI — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/130)* status: all files reviewed, 1 unresolved discussion (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/130#-NAvvbppCfmhjqkTac53:-NC5uuCz1ovTBCGOz6RE:b-dzvbv3) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I spent some time on this, but I wasn't able to come up with anything I can say is definitely better.

As a workaround I'd recommend viewing generated files with `clang-format`. Here's a handy function if `bash` is your shell.

```bash
pretty-cc() { clang-format --style=Google "$1" | vim -R - ; }

# Example 
pretty-cc ~/.cache/bazel/_bazel_osrf/*/execroot/ros2_example_bazel_installed/bazel-out/k8-opt/bin/_shimmed_sentinel_cc_shim.cc
```
</blockquote></details>

OK Hm... not convinced there isn't a better solution in code, but will take that on myself.
And will keep `clang-format` in mind as well, thanks!

___

**Review by EricCousineau-TRI — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/130)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

**Pull request merged**
