### PR TITLE
Ignore iceoryx_binding_c rosdep key

### PR DESCRIPTION
**Pull request by sloretz**
---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/50)

### CODE REVIEW

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm:

Not entirely clear on why it's ignored, but good enough for me!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/50#-:-Mz2dbk894anyFhqLfkA:b-5npzqx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

**Comment by EricCousineau-TRI** [comment]
I notice that CI in #22 is failing, for seemingly related reason.

Should this be merged in?

**Review by sloretz — COMMENTED** [review]
It's ignored because a package depends on`iceoryx_binding_c`, but `iceoryx_binding_c` doesn't install its `package.xml`. When rosdep can't find a `package.xml` for a package it assumes it's a system dependency and errors when there's no rosdep key for it.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/50#-:-MzLpkigAOdk3u93k2Oj:b-5lcvo)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

**Review by sloretz — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/50#-:-MzLqfOK94-LGWoChfBP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

**Pull request merged**
