### PR TITLE
Add Python bindings for drake_ros_viz package.

### PR DESCRIPTION
**Pull request by hidmic**
Spin off from #2. Built on top of #23.

- [ ] Add tests for python bindings.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/24)

### CODE REVIEW

**Comment by gbiggs** [comment]
Based on the API used in the sames in PR #39, this PR provides sufficient Python bindings to be useful. I think this is ready for review and merge once #23 goes in.

**Review by sloretz — COMMENTED** [review]
I think this PR looks good, but it could use a test. I would suggest something high level like a test that creates a Drake Diagram including the RVizVisualizer system in Python with a subscriber, and checks to make sure the subscriber receives at least one message.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/24#-:-N0WeTio0S3g0-w6c5ex:b-iquau7)* status: 0 of 63 files reviewed, all discussions resolved

**Comment by gbiggs** [comment]
There's a sample of using the bindings in #39. I'll adapt that to an automatable test.

**Comment by gbiggs** [comment]
I've pushed a somewhat-complex integration test that shows the Python bindings work end-to-end. I think that when we get the C++ tests done and testing individual marker types, this test should be simplified considerably, but it will do for now.

**Review by sloretz — COMMENTED** [review]
> Reviewed 58 of 60 files at r8, 1 of 8 files at r12, 1 of 2 files at r14, 1 of 3 files at r19, 1 of 1 files at r20, 6 of 6 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/24)* status: all files reviewed, 3 unresolved discussions (waiting on @hidmic)

___
*[`drake_ros_viz/test/test_python_bindings.py` line 38 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/24#-N15BCFf2ciYZsxTXW9t:-N15BCFf2ciYZsxTXW9u:b-iar2cu) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3d7944b69a1fe016fbd7de8b1c172dd996687aaa/drake_ros_viz/test/test_python_bindings.py#L38)):*
> ```Python
> 
> 
> class ManagedSubscription:
> ```

[`WaitForTopics` is almost usable here](https://github.com/ros2/launch_ros/blob/f56c76e17609b2eeb9886072537c018bac66bb74/launch_testing_ros/launch_testing_ros/wait_for_topics.py#L25), but it doesn't seem to give a way to get the message that was received on the topic. It would be nice to upstream this class to `launch_testing_ros` in the future. Mind making a ticket on this repo about upstreaming it?
___
*[`drake_ros_viz/test/test_python_bindings.py` line 43 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/24#-N15Bd5yCg01xjqqieBN:-N15Bd5yCg01xjqqieBO:b-v34lgk) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3d7944b69a1fe016fbd7de8b1c172dd996687aaa/drake_ros_viz/test/test_python_bindings.py#L43)):*
> ```Python
>             topic_name='/scene_markers/visual',
>             required_message_count=1):
>         rclpy.init()
> ```

I'd recommend doing this in a (Python) context manager so the default `rclpy.Context`will be shut down even when the test fails

```python3
class ManagedSubscription:

def __init__(self):
   self._context = rclpy.Context()

def __enter__(self):
    self._context.init()
    # ... create subscription and node ...
    return self

def __exit__(self, t, v, tb):
    self._context.try_shutdown()

# ...


def test_receive_visual_marker_array():
    with ManagedSubscription() as managed_subscription:
        # ... test stuff here
```
___
*[`drake_ros_viz/test/test_python_bindings.py` line 72 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/24#-N15Dnfh8BQdtikCWccx:-N15Dnfh8BQdtikCWccy:bezdjln) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3d7944b69a1fe016fbd7de8b1c172dd996687aaa/drake_ros_viz/test/test_python_bindings.py#L72)):*
> ```Python
>         executor.add_node(self._node)
>         while self.continue_spinning(start_time, timeout):
>             executor.spin_once(timeout_sec=1)
> ```

Alternative implementation: spinning thread target is `executor.spin_until_future_complete`, and the `Future` is completed by `callback` setting the result of the future to the message received. The advantage is it removes the up-to 1 second delay of this loop exiting.
___
*[`drake_ros_viz/test/test_python_bindings.py` line 91 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/24#-N15EK-WDs_WHBxi-gFG:-N15EK-WDs_WHBxi-gFH:bz8am3b) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3d7944b69a1fe016fbd7de8b1c172dd996687aaa/drake_ros_viz/test/test_python_bindings.py#L91)):*
> ```Python
> 
> 
> class System:
> ```

`System` seems a little confusing with Drake systems in this context, but I don't have a better name.
___
*[`drake_ros_viz/test/test_python_bindings.py` line 153 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/24#-N15EbAs0VdVReTMLHef:-N15EbAs0VdVReTMLHeg:b-vgapzk) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3d7944b69a1fe016fbd7de8b1c172dd996687aaa/drake_ros_viz/test/test_python_bindings.py#L153)):*
> ```Python
>     # Dissect and check some important values from a marker
>     marker = received_messages[0].markers[1]
>     assert marker.ns == 'Source_19'
> ```

How stable is `Source_19`? If we're unsure, maybe this could be relaxed to check it's a non-empty string.

**Review by sloretz — APPROVED** [review]
I pushed a commit to get the test passing on CI. The stability of `Source_19` is my only concern, but I'm willing to merge first and see if it becomes a problem later. If CI is green this :lgtm: 

> Reviewed 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/24#-:-N1PkyvvCpY7U9q3U4en:b-h3hwqx)* status: all files reviewed, 1 unresolved discussion (waiting on @hidmic)

**Review by sloretz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/24)* status: all files reviewed, 2 unresolved discussions (waiting on @hidmic)

___
*[`drake_ros_viz/test/test_python_bindings.py` line 169 at r24](https://reviewable.io/reviews/robotlocomotion/drake-ros/24#-N1PnWMQ9dPA9HLHkrhP:-N1PnWMQ9dPA9HLHkrhQ:bb9fyt5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48c80777a7704aa8ee3660a52c2aee3854e25f6e/drake_ros_viz/test/test_python_bindings.py#L169)):*
> ```Python
> 
>         # There should be 23 markers in the array
>         assert len(rx_messages[0].markers) == 24
> ```

Hmm, looks like this changed.

```
   6:             # There should be 23 markers in the array
  6: >           assert len(rx_messages[0].markers) == 24
  6: E           AssertionError: assert 25 == 24
  6: E            +  where 25 = len([visualization_msgs.msg.Marker(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=0, nanosec=0), frame_i...anosec=0), frame_locked=True, points=[], colors=[], text='', mesh_resource='', mesh_use_embedded_materials=False), ...])
  6: E            +    where [visualization_msgs.msg.Marker(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=0, nanosec=0), frame_i...anosec=0), frame_locked=True, points=[], colors=[], text='', mesh_resource='', mesh_use_embedded_materials=False), ...] = visualization_msgs.msg.MarkerArray(markers=[visualization_msgs.msg.Marker(header=std_msgs.msg.Header(stamp=builtin_int...e:///opt/drake/share/drake/manipulation/models/iiwa_description/iiwa7/link_5.obj', mesh_use_embedded_materials=False)]).markers
```

I suspect this is an upstream drake change, because the number of markers is 24 with f4005300353b44120cd23b0804282cff228bd0d1 and 25 with 98aa0fe342337ff759ca0bda0fc316e94294946f, but I don't know where in between the change happened.

I think we could relax the check to "2 or more".

**Review by sloretz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/24)* status: all files reviewed, 2 unresolved discussions (waiting on @hidmic)

___
*[`drake_ros_viz/test/test_python_bindings.py` line 169 at r24](https://reviewable.io/reviews/robotlocomotion/drake-ros/24#-N1PnWMQ9dPA9HLHkrhP:-N1PuqF81kNsX9h7VKds:b1coubd) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48c80777a7704aa8ee3660a52c2aee3854e25f6e/drake_ros_viz/test/test_python_bindings.py#L169)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Hmm, looks like this changed.

```
   6:             # There should be 23 markers in the array
  6: >           assert len(rx_messages[0].markers) == 24
  6: E           AssertionError: assert 25 == 24
  6: E            +  where 25 = len([visualization_msgs.msg.Marker(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=0, nanosec=0), frame_i...anosec=0), frame_locked=True, points=[], colors=[], text='', mesh_resource='', mesh_use_embedded_materials=False), ...])
  6: E            +    where [visualization_msgs.msg.Marker(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=0, nanosec=0), frame_i...anosec=0), frame_locked=True, points=[], colors=[], text='', mesh_resource='', mesh_use_embedded_materials=False), ...] = visualization_msgs.msg.MarkerArray(markers=[visualization_msgs.msg.Marker(header=std_msgs.msg.Header(stamp=builtin_int...e:///opt/drake/share/drake/manipulation/models/iiwa_description/iiwa7/link_5.obj', mesh_use_embedded_materials=False)]).markers
```

I suspect this is an upstream drake change, because the number of markers is 24 with f4005300353b44120cd23b0804282cff228bd0d1 and 25 with 98aa0fe342337ff759ca0bda0fc316e94294946f, but I don't know where in between the change happened.

I think we could relax the check to "2 or more".
</blockquote></details>

`git bisect` says https://github.com/RobotLocomotion/drake/commit/b298869c61632f15bd6c62b13ac078c47d4724ae is the commit that makes the number of markers go from 24 to 25, but I don't understand why.

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/24)* status: 67 of 68 files reviewed, all discussions resolved (waiting on @sloretz)

___
*[`drake_ros_viz/test/test_python_bindings.py` line 153 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/24#-N15EbAs0VdVReTMLHef:-N1Pvbar2Q8PUFWx7ymR:b-jrsc6p) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3d7944b69a1fe016fbd7de8b1c172dd996687aaa/drake_ros_viz/test/test_python_bindings.py#L153)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

How stable is `Source_19`? If we're unsure, maybe this could be relaxed to check it's a non-empty string.
</blockquote></details>

Relaxed this check in 77171c443eb3aea90879f9e431b3672c6656e932
___
*[`drake_ros_viz/test/test_python_bindings.py` line 169 at r24](https://reviewable.io/reviews/robotlocomotion/drake-ros/24#-N1PnWMQ9dPA9HLHkrhP:-N1Pv_xm8U2ZvsfaEDGu:b-jrsc6p) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48c80777a7704aa8ee3660a52c2aee3854e25f6e/drake_ros_viz/test/test_python_bindings.py#L169)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

`git bisect` says https://github.com/RobotLocomotion/drake/commit/b298869c61632f15bd6c62b13ac078c47d4724ae is the commit that makes the number of markers go from 24 to 25, but I don't understand why.
</blockquote></details>

Relaxed this check in 77171c443eb3aea90879f9e431b3672c6656e932

**Review by sloretz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/24#-:-N1Pvgj92Tk6X7_JPFj5:bnfp4nl)* status: 67 of 68 files reviewed, all discussions resolved (waiting on @sloretz)

**Review by sloretz — APPROVED** [review]
> Reviewed 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/24)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hidmic)

**Review by gbiggs — COMMENTED** [review]
> Reviewed 1 of 1 files at r20.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/24)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hidmic)

___
*[`drake_ros_viz/test/test_python_bindings.py` line 38 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/24#-N15BCFf2ciYZsxTXW9t:-N1LhFE67NDJ-AQCYve5:bu2ig4l) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3d7944b69a1fe016fbd7de8b1c172dd996687aaa/drake_ros_viz/test/test_python_bindings.py#L38)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

[`WaitForTopics` is almost usable here](https://github.com/ros2/launch_ros/blob/f56c76e17609b2eeb9886072537c018bac66bb74/launch_testing_ros/launch_testing_ros/wait_for_topics.py#L25), but it doesn't seem to give a way to get the message that was received on the topic. It would be nice to upstream this class to `launch_testing_ros` in the future. Mind making a ticket on this repo about upstreaming it?
</blockquote></details>

Issue added [here](https://github.com/RobotLocomotion/drake-ros/issues/80). There's a similar class in C++ in the `rosbag2` repository that I plan on copying for the C++ integration tests for `drake_ros_viz`; that could also be upstreamed, I think.
___
*[`drake_ros_viz/test/test_python_bindings.py` line 72 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/24#-N15Dnfh8BQdtikCWccx:-N1LjycG6xHu81192rNh:bd2pmja) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3d7944b69a1fe016fbd7de8b1c172dd996687aaa/drake_ros_viz/test/test_python_bindings.py#L72)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Alternative implementation: spinning thread target is `executor.spin_until_future_complete`, and the `Future` is completed by `callback` setting the result of the future to the message received. The advantage is it removes the up-to 1 second delay of this loop exiting.
</blockquote></details>

I have no experience with futures in Python. I initially intended to use them to implement this rather than the busy-loop, but when I looked into them they seemed tightly tied to async Python, and everything I read implied that I would have to make every function from `main()` down `async` for a future to work.

Do you have a good reference or sample I can look at to understand how to use a future here?
___
*[`drake_ros_viz/test/test_python_bindings.py` line 91 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/24#-N15EK-WDs_WHBxi-gFG:-N1LkbVY5f0b2Whr1SFs:bp2vzq8) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3d7944b69a1fe016fbd7de8b1c172dd996687aaa/drake_ros_viz/test/test_python_bindings.py#L91)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

`System` seems a little confusing with Drake systems in this context, but I don't have a better name.
</blockquote></details>

I agree that it's not a great name. I renamed it to `DrakeTestSystem` in a4a6000, which is slightly better, I think.
___
*[`drake_ros_viz/test/test_python_bindings.py` line 153 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/24#-N15EbAs0VdVReTMLHef:-N1LklE5CG5TUXOwwVrH:b-z12t3b) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3d7944b69a1fe016fbd7de8b1c172dd996687aaa/drake_ros_viz/test/test_python_bindings.py#L153)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Relaxed this check in 77171c443eb3aea90879f9e431b3672c6656e932
</blockquote></details>

To be completely honest, I don't know. This is the downside of using a complex system for the integration test rather than a simple system where we have complete control over ordering.

**Pull request merged**
