### PR TITLE
Add drake_ros_core package.

### PR DESCRIPTION
**Pull request by hidmic**
Spin off from #2. Includes Drake C++ systems for publishing and subscribing to ROS2 messages.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/5)

### CODE REVIEW

**Comment by hidmic** [comment]
FYI @gbalke.

**Comment by hidmic** [comment]
@IanTheEngineer friendly ping (or should I bump someone else for review?)

**Review by IanTheEngineer — COMMENTED** [review]
I'll take a pass at reviewing. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/5#-:-McAa2VJ8Ukaih7wjPqV:b9qdj37)* status: 0 of 20 files reviewed, all discussions resolved

**Review by IanTheEngineer — CHANGES_REQUESTED** [review]
First pass. Thanks for breaking this package out. The updated interface looks quite clean and well structured. I appreciate the pimpl organization. I have a few minor nits below. I'll take a second pass where I test and build.

> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/5#-:-McF2niBDopxWGSTf4eN:by7irh6)* status: all files reviewed, 6 unresolved discussions (waiting on @hidmic)

___
*[drake_ros_core/CMakeLists.txt, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/5#-McEqKU17SAhK2yHuOC4:-McEqKU23Gj89PzJPXem:b-dqq9ns) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b11ce3e8bf75f7efe3e3ad6fa1603f0b380593f5/drake_ros_core/CMakeLists.txt#L2)):*
> ```CMake
> cmake_minimum_required(VERSION 3.10)
> project(drake_ros_core)
> ```

FYI Great choice of name for the package. Seems clear and rings true to ROS / Drake.
___
*[drake_ros_core/package.xml, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/5#-McEr0Og8FBu6Wn8zVZb:-McEr0Og8FBu6Wn8zVZc:b-x0j2hh) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b11ce3e8bf75f7efe3e3ad6fa1603f0b380593f5/drake_ros_core/package.xml#L16)):*
> ```XML
>   <depend>rosidl_runtime_c</depend>
>   <depend>rosidl_typesupport_cpp</depend>
>   <depend>tf2_ros</depend>
> ```

Minor: It seems `tf2_ros` and `visualization_msgs` are no longer depended upon in this package.
___
*[drake_ros_core/include/drake_ros_core/drake_ros.hpp, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/5#-McErixKB8s1h6d7mDdj:-McErixKB8s1h6d7mDdk:b-4547bd) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b11ce3e8bf75f7efe3e3ad6fa1603f0b380593f5/drake_ros_core/include/drake_ros_core/drake_ros.hpp#L1)):*
> ```cpp
> // Copyright 2020 Open Source Robotics Foundation, Inc.
> ```

Nit: 2021
___
*[drake_ros_core/include/drake_ros_core/drake_ros.hpp, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/5#-McEs4q2-lvGMXg_VuFz:-McEs4q2-lvGMXg_VuG-:b-u03fpg) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b11ce3e8bf75f7efe3e3ad6fa1603f0b380593f5/drake_ros_core/include/drake_ros_core/drake_ros.hpp#L22)):*
> ```
> #include <tf2_ros/transform_broadcaster.h>
> ```
Minor: Seems this include is no longer used.
___
*[drake_ros_core/include/drake_ros_core/drake_ros_interface.hpp, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/5#-McEt81UAOna3NmB4zXk:-McEt81V7FDbFOhcIIes:b-amdakv) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b11ce3e8bf75f7efe3e3ad6fa1603f0b380593f5/drake_ros_core/include/drake_ros_core/drake_ros_interface.hpp#L1)):*
> ```cpp
> // Copyright 2020 Open Source Robotics Foundation, Inc.
> ```

Nit: Add 2021 on all files with a copyright please.
___
*[drake_ros_core/include/drake_ros_core/drake_ros_interface.hpp, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/5#-McEtEb12Ds-4f84jVxT:-McEtEb12Ds-4f84jVxU:b-bbo5x0) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b11ce3e8bf75f7efe3e3ad6fa1603f0b380593f5/drake_ros_core/include/drake_ros_core/drake_ros_interface.hpp#L21)):*
> ```cpp
> #include <rclcpp/qos.hpp>
> #include <rclcpp/serialized_message.hpp>
> #include <tf2_ros/transform_broadcaster.h>
> ```

Minor: Extra include.
___
*[drake_ros_core/include/drake_ros_core/serializer.hpp, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/5#-McEu0Dr9LrpPeUYMY8y:-McEu0Dr9LrpPeUYMY8z:b713p1e) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b11ce3e8bf75f7efe3e3ad6fa1603f0b380593f5/drake_ros_core/include/drake_ros_core/serializer.hpp#L23)):*
> ```cpp
> #include <rosidl_typesupport_cpp/message_type_support.hpp>
> 
> #include <std_msgs/msg/bool.hpp>
> ```

Minor: Both `std_msgs/bool` and `tf2_msgs/tf_message` appear unused.

**Review by hidmic — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/5#-:-McGCka24NRe2neQFB1X:b-9qdoz3)* status: 2 of 20 files reviewed, 5 unresolved discussions (waiting on @IanTheEngineer)

___
*[drake_ros_core/package.xml, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/5#-McEr0Og8FBu6Wn8zVZb:-McG9inbB2VgLXK_eG8v:bota7ql) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b11ce3e8bf75f7efe3e3ad6fa1603f0b380593f5/drake_ros_core/package.xml#L16)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Minor: It seems `tf2_ros` and `visualization_msgs` are no longer depended upon in this package.
</blockquote></details>

Argh. Fixed in a04608af84d52ed4216558f7105306406fedd2b3 
___
*[drake_ros_core/include/drake_ros_core/drake_ros.hpp, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/5#-McErixKB8s1h6d7mDdj:-McGCIwG4LUxZ7Dbn_aX:bh0dsoq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b11ce3e8bf75f7efe3e3ad6fa1603f0b380593f5/drake_ros_core/include/drake_ros_core/drake_ros.hpp#L1)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Nit: 2021
</blockquote></details>

Updated here and everywhere else in c7460c2d40e3b1d63be3cbb1af00469fff716f3e
___
*[drake_ros_core/include/drake_ros_core/drake_ros.hpp, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/5#-McEs4q2-lvGMXg_VuFz:-McGCMbDD9eDjn5iRBfq:b-c6it2g) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b11ce3e8bf75f7efe3e3ad6fa1603f0b380593f5/drake_ros_core/include/drake_ros_core/drake_ros.hpp#L22)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

> ```
> #include <tf2_ros/transform_broadcaster.h>
> ```
Minor: Seems this include is no longer used.
</blockquote></details>

Indeed, see a04608af84d52ed4216558f7105306406fedd2b3
___
*[drake_ros_core/include/drake_ros_core/drake_ros_interface.hpp, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/5#-McEt81UAOna3NmB4zXk:-McGCOUSD23rXtGntCCl:b-xoh859) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b11ce3e8bf75f7efe3e3ad6fa1603f0b380593f5/drake_ros_core/include/drake_ros_core/drake_ros_interface.hpp#L1)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Nit: Add 2021 on all files with a copyright please.
</blockquote></details>

Done in c7460c2d40e3b1d63be3cbb1af00469fff716f3e
___
*[drake_ros_core/include/drake_ros_core/drake_ros_interface.hpp, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/5#-McEtEb12Ds-4f84jVxT:-McGCTuUDAInXOgmWubi:b-5tjeot) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b11ce3e8bf75f7efe3e3ad6fa1603f0b380593f5/drake_ros_core/include/drake_ros_core/drake_ros_interface.hpp#L21)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Minor: Extra include.
</blockquote></details>

Removed in a04608af84d52ed4216558f7105306406fedd2b3
___
*[drake_ros_core/include/drake_ros_core/serializer.hpp, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/5#-McEu0Dr9LrpPeUYMY8y:-McGCi0l7P9uLxYks5bY:b-xvj74p) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b11ce3e8bf75f7efe3e3ad6fa1603f0b380593f5/drake_ros_core/include/drake_ros_core/serializer.hpp#L23)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Minor: Both `std_msgs/bool` and `tf2_msgs/tf_message` appear unused.
</blockquote></details>

Yes! Removed in a04608af84d52ed4216558f7105306406fedd2b3

**Comment by hidmic** [comment]
Uh, Reviewable didn't hyperlink commit hashes?

**Review by IanTheEngineer — COMMENTED** [review]
I've looked through all the changes, and things look quite good. I'll do a bit more testing on my end, but I think we're close!

> Reviewed 14 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/5#-:-Mf4V1l7-XHhWkc8gnAN:bv5v33d)* status: 16 of 20 files reviewed, 1 unresolved discussion (waiting on @IanTheEngineer)

**Comment by IanTheEngineer** [comment]
@hidmic could you please target the `develop` branch?

**Comment by hidmic** [comment]
Only had to change the base branch :)

**Review by IanTheEngineer — APPROVED** [review]
:lgtm: Thanks for iterating on this. 

> Reviewed 4 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/5#-:-Mh03c7V5gDMpnrAW8Md:bkelrmx)* status: all files reviewed, 1 unresolved discussion (waiting on @IanTheEngineer)

**Review by IanTheEngineer — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hidmic)

**Pull request merged**
