### PR TITLE
Python bazel rules to drake_ros_core

### PR DESCRIPTION
**Pull request by sloretz**
~Requires #75~ (merged)
Part of #68

This adds Python rules for `drake_ros_core`

+@EricCousineau-TRI for review please

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/84)

### CODE REVIEW

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/84)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`drake_ros_core/BUILD.bazel` line 89 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-N2lHfjSCT7bQwgQV4JJ:-N2lHfjT5vqrD0KiEagU:b-h8pb4g) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3959aa9477280a2bb4fb3b298a8c34e4f46a9854/drake_ros_core/BUILD.bazel#L89)):*
> ```Starlark
> ros_py_test(
>   name = 'test_pub_sub_py',
>   deps = [
> ```

Working: Minor stylization nit. Will use Drake's `buildifer` lint tool to fixup.
___
*[`drake_ros_core/test/test_pub_sub.py` line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-N2lH_yR85sC7nMMj75_:-N2lH_yR85sC7nMMj75a:b-bo7ls1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3959aa9477280a2bb4fb3b298a8c34e4f46a9854/drake_ros_core/test/test_pub_sub.py#L37)):*
> ```Python
> def test_nominal_case():
>     if 'TEST_TMPDIR' in os.environ:
>         from rmw_isolation import isolate_rmw_by_path
> ```

Working: Let's make this import unconditional. Better to fail fast for unseen imports.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/84)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`drake_ros_core/BUILD.bazel` line 89 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-N2lHfjSCT7bQwgQV4JJ:-N2lKWdiEEzHNDrg4CoE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3959aa9477280a2bb4fb3b298a8c34e4f46a9854/drake_ros_core/BUILD.bazel#L89)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Minor stylization nit. Will use Drake's `buildifer` lint tool to fixup.
</blockquote></details>

Done.
___
*[`drake_ros_core/test/test_pub_sub.py` line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-N2lH_yR85sC7nMMj75_:-N2lKXKB4VxBJ0BJNjIy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3959aa9477280a2bb4fb3b298a8c34e4f46a9854/drake_ros_core/test/test_pub_sub.py#L37)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Let's make this import unconditional. Better to fail fast for unseen imports.
</blockquote></details>

Done.

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/84)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`drake_ros_core/test/test_pub_sub.py` line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-N2lZRx14SlAOz4r1TPp:-N2lZRx21SLboPQfoDHM:b-nw1o3c) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/98c161f09bd2a4d9175ace6e8925c4ffa163fff8/drake_ros_core/test/test_pub_sub.py#L33)):*
> ```Python
> from drake_ros_core import RosPublisherSystem
> from drake_ros_core import RosSubscriberSystem
> from rmw_isolation import isolate_rmw_by_path
> ```

Working; Ah, not available in CMake.

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/84)* status: 0 of 29 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-N2lIZQxAaNdqxzJ445V:-N49gn8I9P-ppgVQ-HRx:bo2dozl) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Requires rebase on #75
</blockquote></details>

Rebased on develop

___
___
*[`drake_ros_core/BUILD.bazel` line 89 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-N2lHfjSCT7bQwgQV4JJ:-N49gqHv-vF75DWWG0aH:bg6uaz6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3959aa9477280a2bb4fb3b298a8c34e4f46a9854/drake_ros_core/BUILD.bazel#L89)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ran buildifier again in 712ad03
___
*[`drake_ros_core/test/test_pub_sub.py` line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-N2lH_yR85sC7nMMj75_:-N49h4s-9oTpS2iejnVj:b-espdxc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3959aa9477280a2bb4fb3b298a8c34e4f46a9854/drake_ros_core/test/test_pub_sub.py#L37)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did isolation and import at top level so it works in CMake and would fail fast on import error in 8f17f11
___
*[`drake_ros_core/test/test_pub_sub.py` line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-N2lZRx14SlAOz4r1TPp:-N49gxg2Atyvf-GbVTLL:b-espdxc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/98c161f09bd2a4d9175ace6e8925c4ffa163fff8/drake_ros_core/test/test_pub_sub.py#L33)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working; Ah, not available in CMake.
</blockquote></details>

Did isolation and import at top level so it works in CMake and would fail fast on import error in 8f17f11

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/84)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-NH_Vpbo3-vDkjCVJkTs:-NH_Vpbo3-vDkjCVJkTt:bxuairi) (no related file):*
@sloretz Is this stuff ready to re-up, given our newer usages in Anzu, linting, etc.?
Should we continue in this PR, or make a new one?

___

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/84)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-NH_Vpbo3-vDkjCVJkTs:-NI01HJ_-e-06rFx5_A3:b-gfp1ow) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

@sloretz Is this stuff ready to re-up, given our newer usages in Anzu, linting, etc.?
Should we continue in this PR, or make a new one?
</blockquote></details>

I rebased this PR and made sure `bazel test //...` in `drake_ros_core` passes.

I see a build warning that I'll investigate tomorrow

```
INFO: From Compiling src/module_py.cc:
In file included from src/module_py.cc:27:
bazel-out/k8-fastbuild/bin/_virtual_includes/python_bindings_internal_hdrs/drake_ros_core/serializer_interface_pybind.h:31:7: warning: 'drake_ros_core::drake_ros_core_py::PySerializerInterface' declared with greater visibility than its base 'pybind11::wrapper<drake_ros_core::SerializerInterface>' [-Wattributes]
   31 | class PySerializerInterface : public py::wrapper<SerializerInterface> {
      |       ^~~~~~~~~~~~~~~~~~~~~
```

___

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/84)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-NH_Vpbo3-vDkjCVJkTs:-NI2rD-tE_ZkbQhmjGE_:b-v8m7ms) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I rebased this PR and made sure `bazel test //...` in `drake_ros_core` passes.

I see a build warning that I'll investigate tomorrow

```
INFO: From Compiling src/module_py.cc:
In file included from src/module_py.cc:27:
bazel-out/k8-fastbuild/bin/_virtual_includes/python_bindings_internal_hdrs/drake_ros_core/serializer_interface_pybind.h:31:7: warning: 'drake_ros_core::drake_ros_core_py::PySerializerInterface' declared with greater visibility than its base 'pybind11::wrapper<drake_ros_core::SerializerInterface>' [-Wattributes]
   31 | class PySerializerInterface : public py::wrapper<SerializerInterface> {
      |       ^~~~~~~~~~~~~~~~~~~~~
```
</blockquote></details>

Yeah, we've seen that in Drake before. Basically, just need to make sure the symbol is not publicly exported in shared lib.
I forgot exactly how we fixed it in Drake. Let me briefly check.

___
___
*[`drake_ros_core/test/test_pub_sub.py` line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-N2lH_yR85sC7nMMj75_:-NI2qp9L9WxV6ZLVMGeF:b-uuw5ys) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3959aa9477280a2bb4fb3b298a8c34e4f46a9854/drake_ros_core/test/test_pub_sub.py#L37)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Did isolation and import at top level so it works in CMake and would fail fast on import error in 8f17f11
</blockquote></details>

Hm... I'd prefer this happen in a function; I don't love top-level logic if we can avoid it.

For example, please see Anzu, `anzu/.../test/integration_test_common.py`, `get_ros_isolation_env`

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/84)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-NH_Vpbo3-vDkjCVJkTs:-NI2t4ds0BfBScqkrXjE:b-y1l5y5) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yeah, we've seen that in Drake before. Basically, just need to make sure the symbol is not publicly exported in shared lib.
I forgot exactly how we fixed it in Drake. Let me briefly check.
</blockquote></details>

From perusing Drake source, I still can't exactly pin it down.

However, I'd suggest trying to encapsulate / avoid leaking those classes as much as possible, e.g. anonymous `namespace { ... }` as done here:
https://github.com/RobotLocomotion/drake/blob/8ef936ce6e215d733270e38e2ccdb375326f3f19/bindings/pydrake/systems/lcm_py.cc#L28-L32

I believe we should avoid decorating namespaces with private linkage and/or smacking stuff with a translation-wide compiler flags / pragmas if we can; this may merit some small refactoring of the code to reflect what I (and others) have done in Drake for the equivalent pattern for LCM, e.g.
https://github.com/RobotLocomotion/drake/blob/8ef936ce6e215d733270e38e2ccdb375326f3f19/bindings/pydrake/systems/lcm_pybind.h

___

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/84)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-NH_Vpbo3-vDkjCVJkTs:-NI3WJjc0SKqsRjQPNlf:b-cqlu6n) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

From perusing Drake source, I still can't exactly pin it down.

However, I'd suggest trying to encapsulate / avoid leaking those classes as much as possible, e.g. anonymous `namespace { ... }` as done here:
https://github.com/RobotLocomotion/drake/blob/8ef936ce6e215d733270e38e2ccdb375326f3f19/bindings/pydrake/systems/lcm_py.cc#L28-L32

I believe we should avoid decorating namespaces with private linkage and/or smacking stuff with a translation-wide compiler flags / pragmas if we can; this may merit some small refactoring of the code to reflect what I (and others) have done in Drake for the equivalent pattern for LCM, e.g.
https://github.com/RobotLocomotion/drake/blob/8ef936ce6e215d733270e38e2ccdb375326f3f19/bindings/pydrake/systems/lcm_pybind.h
</blockquote></details>

Using an anonymous namespace in 5c2465e seems to have gotten rid of the warning

___
___
*[`drake_ros_core/test/test_pub_sub.py` line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-N2lH_yR85sC7nMMj75_:-NI3TaV8-PwiXk2syFEY:brx934t) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3959aa9477280a2bb4fb3b298a8c34e4f46a9854/drake_ros_core/test/test_pub_sub.py#L37)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Hm... I'd prefer this happen in a function; I don't love top-level logic if we can avoid it.

For example, please see Anzu, `anzu/.../test/integration_test_common.py`, `get_ros_isolation_env`
</blockquote></details>

Put into function in de9a34d

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
:lgtm_strong: pending CI fixes

> Reviewed 1 of 2 files at r4, 1 of 2 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-:-NI4Ejr7BTdhyP8fEvkc:b-lh0jtn)* status: all files reviewed, 4 unresolved discussions (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-NH_Vpbo3-vDkjCVJkTs:-NI4Eiqy6oDhzqJMz_rK:b-w196av) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Using an anonymous namespace in 5c2465e seems to have gotten rid of the warning
</blockquote></details>

OK Thanks!

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-NI4F5XR9M-XZAHc9s0P:-NI4F5XR9M-XZAHc9s0Q:b-cuiogc) (no related file):*
CI is presently failing:
```
@lcm//:lcm-gen depends on @glib//:glib in repository @glib which failed to fetch [...]
```

___
___
*[`drake_ros_core/BUILD.bazel` line 69 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-NI4EZMB-NpF6LXvBSzw:-NI4EZMCCahZifV8jSLF:bujarff) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5c2465ebbd9ba6c0b6139b7aaceb3a504268f65c/drake_ros_core/BUILD.bazel#L69)):*
> ```Starlark
>     ],
>     cc_so_name = "_drake_ros_core",
>     cc_srcs = glob(["**/*_py.cc"]),
> ```

nit This may pull in things beyond `srcs`.

Why not `srcs/**/*_py.cc`?
___
*[`drake_ros_core/test/test_pub_sub.py` line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-N2lH_yR85sC7nMMj75_:-NI4EfU1DgXH9nc6c_HI:b-w196av) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3959aa9477280a2bb4fb3b298a8c34e4f46a9854/drake_ros_core/test/test_pub_sub.py#L37)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Put into function in de9a34d
</blockquote></details>

OK Thanks!

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/84)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-NH_Vpbo3-vDkjCVJkTs:-NI9a2KP70PkZ3yZwbW6:b-cmrxn3) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Thanks!
</blockquote></details>

Using an anonymous namespace was causing `cpplint` test failures in CI because it forbids anonymous namespaces in headers. The best solution I could think of was to move the class to `module_py.cc`:  c2d4ee9 

___
___
*[`drake_ros_core/BUILD.bazel` line 69 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-NI4EZMB-NpF6LXvBSzw:-NI9aQc23AlbypMH9wbw:brbeul) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5c2465ebbd9ba6c0b6139b7aaceb3a504268f65c/drake_ros_core/BUILD.bazel#L69)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This may pull in things beyond `srcs`.

Why not `srcs/**/*_py.cc`?
</blockquote></details>

6360e04

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/84)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-NI4F5XR9M-XZAHc9s0P:-NI9dMBI3DlqCGH2NHa6:bonmauf) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

CI is presently failing:
```
@lcm//:lcm-gen depends on @glib//:glib in repository @glib which failed to fetch [...]
```
</blockquote></details>

I think the missing `@glib` when building drake is caused by not running drake's `install_prereqs.sh` script in CI. CI is [expecting bazel to download drake](https://github.com/RobotLocomotion/drake-ros/blob/6bf405fdf0470c94d14b5bd1cbc89f685fde2452/drake_ros_core/WORKSPACE#L47-L54). Any ideas on how to ask bazel to just do the download, then get a path to the downloaded [`install_prereqs.sh`](https://github.com/RobotLocomotion/drake/blob/master/setup/ubuntu/install_prereqs.sh) script so CI can run it?

___

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/84)* status: all files reviewed, 1 unresolved discussion (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-NH_Vpbo3-vDkjCVJkTs:-NI9kM3y3cEgO5Rks3Jb:b-pb53tg) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Using an anonymous namespace was causing `cpplint` test failures in CI because it forbids anonymous namespaces in headers. The best solution I could think of was to move the class to `module_py.cc`:  c2d4ee9 
</blockquote></details>

Ah, gotcha. Looks much better!

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-NI4F5XR9M-XZAHc9s0P:-NI9jUYqBTcOV9xJ47Zz:b-rw0yuo) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I think the missing `@glib` when building drake is caused by not running drake's `install_prereqs.sh` script in CI. CI is [expecting bazel to download drake](https://github.com/RobotLocomotion/drake-ros/blob/6bf405fdf0470c94d14b5bd1cbc89f685fde2452/drake_ros_core/WORKSPACE#L47-L54). Any ideas on how to ask bazel to just do the download, then get a path to the downloaded [`install_prereqs.sh`](https://github.com/RobotLocomotion/drake/blob/master/setup/ubuntu/install_prereqs.sh) script so CI can run it?
</blockquote></details>

I *think* you should be able to do something like this, maybe?
```
bazel build @drake//:module_py
sudo ./bazel-{workspace}/external/drake/setup/ubuntu/install_prereqs.sh
```

Did this in Anzu after `bazel clean --expunge --async` and it seemed.
In general, repository fetches can be independent (and should be maximally independent).

___

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/84)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-NI4F5XR9M-XZAHc9s0P:-NIEtvoV4Ho2C-80Z9rQ:biajnzy) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I *think* you should be able to do something like this, maybe?
```
bazel build @drake//:module_py
sudo ./bazel-{workspace}/external/drake/setup/ubuntu/install_prereqs.sh
```

Did this in Anzu after `bazel clean --expunge --async` and it seemed.
In general, repository fetches can be independent (and should be maximally independent).
</blockquote></details>

Your idea worked!

I found Bazel was hanging in CI when beginning to build`drake_ros_core`.  I wasn't able to figure out the cause, but moving the test steps from `bazelized.yaml`to their own workflow resolved the issue.

<details><summary> Bazel hang log</summary>

```

Run bazel build //...
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 10 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 30 seconds, waiting at most 60)
INFO: Waited 60 seconds for server process (pid=20569) to terminate.
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 10)
WARNING: Waiting for server process to terminate (waited 10 seconds, waiting at most 10)
INFO: Waited 10 seconds for server process (pid=20569) to terminate.
FATAL: Attempted to kill stale server process (pid=20569) using SIGKILL, but it did not die in a timely fashion.
```
</details>

___

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/84)* status: all files reviewed, 1 unresolved discussion (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-NI4F5XR9M-XZAHc9s0P:-NIFofbhEQmWBCo5WuOY:bbzy6va) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Your idea worked!

I found Bazel was hanging in CI when beginning to build`drake_ros_core`.  I wasn't able to figure out the cause, but moving the test steps from `bazelized.yaml`to their own workflow resolved the issue.

<details><summary> Bazel hang log</summary>

```

Run bazel build //...
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 10 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 30 seconds, waiting at most 60)
INFO: Waited 60 seconds for server process (pid=20569) to terminate.
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 10)
WARNING: Waiting for server process to terminate (waited 10 seconds, waiting at most 10)
INFO: Waited 10 seconds for server process (pid=20569) to terminate.
FATAL: Attempted to kill stale server process (pid=20569) using SIGKILL, but it did not die in a timely fashion.
```
</details>
</blockquote></details>

Huh... yeah, I guess I'm a bit surprised that it hangs at all?

But upon inspection, it looks like the drake-ros version of Bazel (5.1.0) lags behind Drake's (5.3.1), so it could be because it's shutting down / spinning up a new version of Bazel.

Could you put a TODO in `bazel_ros2_rules/setup/install_prereqs.sh` to ensure we use same exact version as Drake? (either using linting, or by using the same trick there?)

___

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/84)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-NI4F5XR9M-XZAHc9s0P:-NIIyrqGDsOo26sup25o:b5wtveg) (no related file):*
> But upon inspection, it looks like the drake-ros version of Bazel (5.1.0) lags behind Drake's (5.3.1), so it could be because it's shutting down / spinning up a new version of Bazel.

I thought that might have been it too, but bazel still hung with this commit: https://github.com/RobotLocomotion/drake-ros/pull/84/commits/ad31c7dd586f5700b2e5099cf2d9a79b83274983 . I reverted it since it didn't fix the issue and was otherwise unrelated to this PR.

> Could you put a TODO in bazel_ros2_rules/setup/install_prereqs.sh to ensure we use same exact version as Drake? (either using linting, or by using the same trick there?)

Added TODO in 4cd00cb

___

**Review by EricCousineau-TRI — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/84)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/84#-NI4F5XR9M-XZAHc9s0P:-NIJIgva3C2iEB3HJhcb:by5s5kf) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

> But upon inspection, it looks like the drake-ros version of Bazel (5.1.0) lags behind Drake's (5.3.1), so it could be because it's shutting down / spinning up a new version of Bazel.

I thought that might have been it too, but bazel still hung with this commit: https://github.com/RobotLocomotion/drake-ros/pull/84/commits/ad31c7dd586f5700b2e5099cf2d9a79b83274983 . I reverted it since it didn't fix the issue and was otherwise unrelated to this PR.

> Could you put a TODO in bazel_ros2_rules/setup/install_prereqs.sh to ensure we use same exact version as Drake? (either using linting, or by using the same trick there?)

Added TODO in 4cd00cb
</blockquote></details>

Gotcha, thanks!

___

**Pull request merged**
