### PR TITLE
Add DrakeRos constructor that accepts externally created Node

### PR DESCRIPTION
**Pull request by sloretz**
Towards Anzu PR 9950

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/203)

### CODE REVIEW

**Review by sloretz — COMMENTED** [review]
+@ericcousineau-tri for review please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/203#-:-NIoAUTE-I4nDdxcAWg1:btxkahr)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Not sure if I understand motivation here - can you reference a PR, issue, or a convo that motivates this?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/203#-:-NIqxXXX86fwrn3la4Gx:b-61j1pr)* status: 0 of 3 files reviewed, all discussions resolved

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm: locally, thanks! But adding request for motivation

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/203#-:-NIqxk-pBAmZ91rpTPWn:b-8qse2v)* status: all files reviewed, 1 unresolved discussion (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/203#-NIqxksm1d2XIGne1edZ:-NIqxksm1d2XIGne1ed_:bmlsg28) (no related file):*
nit Requesting motivation (just to ensure this addresses it)

___

**Review by EricCousineau-TRI — APPROVED** [review]
FYI CI is presently failing?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/203#-:-NIr9fVd4vT6R6uH03Yp:bqig2n2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/203#-NIqxksm1d2XIGne1edZ:-NIr9a9x5emdD19-rPaM:b-vvsa3q) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Requesting motivation (just to ensure this addresses it)
</blockquote></details>

Done. Ah, it was Anzu PR 9950. Edited overview to reflect that.

___

**Review by sloretz — COMMENTED** [review]
Last CI failure needs #204 to be fixed.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/203#-:-NL8f6jU42JrjtCDSHUd:bsg6gep)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

**Comment by EricCousineau-TRI** [comment]
Is this still necessary for Anzu PR 9950?

**Pull request closed without merging**
