### PR TITLE
[py] Make Python modules more hierarchical

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards #151

Effectively addresses part of @jwnimmer-tri's comment in https://github.com/RobotLocomotion/drake-ros/issues/237#issuecomment-1448496494

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sloretz for review, please!

I'd like to land this by EOD today.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238#-:-NPO-ggk9sMLM5goHLs0:b8wwc0g)* status: 0 of 23 files reviewed, all discussions resolved (waiting on @sloretz)

**Review by sloretz — CHANGES_REQUESTED** [review]
> Reviewed 22 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238)* status: 22 of 23 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`drake_ros/BUILD.bazel` line 6 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238#-NPO1LByENOwIKcAZrx3:-NPO1LByENOwIKcAZrx4:b-hlz9ns) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/6ec9e69ad5eb8a7dece702f4fec89314285c30a6/drake_ros/BUILD.bazel#L6)):*
> ```Starlark
>     name = "module_py",
>     srcs = ["__init__.py"],
>     imports = [".."],
> ```

It looks like this is saying the parent directory should be added to PYTHONPATH. What does bazel do with this? Does it make the path absolute, or is the parent of the current working directory always importable?
___
*[`drake_ros_examples/examples/multirobot/test/multirobot_test.py` line 23 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238#-NPO2gai34eUnWr-VT25:-NPO2gai34eUnWr-VT26:b9yuftk) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/6ec9e69ad5eb8a7dece702f4fec89314285c30a6/drake_ros_examples/examples/multirobot/test/multirobot_test.py#L23)):*
> ```Python
> 
>     check_binary("drake_ros.examples/examples/multirobot/multirobot")
>     check_binary("drake_ros.examples/examples/multirobot/multirobot_py")
> ```

Accidental find/replace? This should still be `drake_ros_examples`.



_Code quote:_
```Python
    check_binary("drake_ros.examples/examples/multirobot/multirobot")
    check_binary("drake_ros.examples/examples/multirobot/multirobot_py")
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238)* status: 20 of 23 files reviewed, 1 unresolved discussion (waiting on @sloretz)

___
*[`drake_ros/BUILD.bazel` line 6 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238#-NPO1LByENOwIKcAZrx3:-NPO57Rk9RW9pNWUH7jA:byzvbj7) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/6ec9e69ad5eb8a7dece702f4fec89314285c30a6/drake_ros/BUILD.bazel#L6)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

It looks like this is saying the parent directory should be added to PYTHONPATH. What does bazel do with this? Does it make the path absolute, or is the parent of the current working directory always importable?
</blockquote></details>

OK I believe Bazel's philosophy is "always make it predictable", so it should be the absolute path relative to the executing binary, not the PWD.
I'd like us to move forward with this unless we have clear failure.
___
*[`drake_ros_examples/examples/multirobot/test/multirobot_test.py` line 23 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238#-NPO2gai34eUnWr-VT25:-NPO5Wj808MrsNylzun_:b-emrda) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/6ec9e69ad5eb8a7dece702f4fec89314285c30a6/drake_ros_examples/examples/multirobot/test/multirobot_test.py#L23)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Accidental find/replace? This should still be `drake_ros_examples`.
</blockquote></details>

Done - oops!

**Review by sloretz — COMMENTED** [review]
> Reviewed 1 of 23 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238)* status: all files reviewed, 1 unresolved discussion (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238#-NPOH1Zy1NCetCkFBLZ_:-NPOH1Zy1NCetCkFBLZa:bme2sqh) (no related file):*
Needs fixes for CMake.

___

**Comment by jwnimmer-tri** [comment]
I had another thought.  Would it be easier to do it this way?

```py
from drake_ros import RosInterfaceSystem, RvizVisualizer 
```

Python style tends to prefer fewer, less-nested modules.  There aren't _that_ many classes here.

This way seems simpler for the user, at least.  Possibly its simpler for the build system as well.

**Comment by EricCousineau-TRI** [comment]
I would be fine with that as part of #237 as long as the C++ code is consistent!

We have intermediate path that we can use to make things work and ultimately address #151.
But yeah, if we spend too much time fighting both build systems, then we should pull the trigger sooner than later.

**Review by sloretz — CHANGES_REQUESTED** [review]
> Reviewed 19 of 27 files at r5, 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238#-NPOH1Zy1NCetCkFBLZ_:-NPtF7zz6m3ZFUWUSquU:b-yvkeix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Needs fixes for CMake.
</blockquote></details>

Looks like it needs linter fixes. LGTM once that's done.

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238)* status: all files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238#-NPtIpIW-PDcojl9ne3f:-NPtIpIXEEGZJ1TAxO1w:bzgezsl) (no related file):*
Working: Waiting for #242 to land.

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238)* status: 21 of 43 files reviewed, all discussions resolved (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238#-NPOH1Zy1NCetCkFBLZ_:-NPtfLeC71couN9mqy6V:b-dtkds3) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Looks like it needs linter fixes. LGTM once that's done.
</blockquote></details>

Done, thanks!

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238#-NPtIpIW-PDcojl9ne3f:-NPtfMWL-9akB46KX2vc:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Waiting for #242 to land.
</blockquote></details>

Done.

___

**Review by sloretz — APPROVED** [review]
LGTM with green CI

> Reviewed 22 of 22 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238#-:-NPtfhOnB29C8wAlAMBr:bmar89i)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238)* status: all files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`drake_ros/CMakeLists.txt` line 25 at r7](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238#-NPtfYUTA-MIfJKqNLgq:-NPtfYUUDyFgqLQgEs00:b-kfoiqr) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/d0239e29daf48d3189bb716f3e35b6737a402dfb/drake_ros/CMakeLists.txt#L25)):*
> ```CMake
> add_subdirectory(drake_ros)
> 
> # Install python package must happen at top level CMakeLists.txt
> ```

Working: Should qualify this per https://github.com/EricCousineau-TRI/drake-ros/pull/6#discussion_r1125164067
___
*[`drake_ros/CMakeLists.txt` line 28 at r7](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238#-NPtfSN24oXXdoiCN7DI:-NPtfSN24oXXdoiCN7DJ:b-a7picu) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/d0239e29daf48d3189bb716f3e35b6737a402dfb/drake_ros/CMakeLists.txt#L28)):*
> ```CMake
> # TODO(sloretz) exclude drake_ros/test folder
> ament_python_install_package(drake_ros)
> # Generate same python package in build directory for use in tests
> ```

Working: Should reference https://github.com/ros2/ros2_documentation/issues/3373

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238)* status: 42 of 43 files reviewed, all discussions resolved (waiting on @sloretz)

___
*[`drake_ros/CMakeLists.txt` line 25 at r7](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238#-NPtfYUTA-MIfJKqNLgq:-NPtgSmEDcy9RXFY2aFj:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/d0239e29daf48d3189bb716f3e35b6737a402dfb/drake_ros/CMakeLists.txt#L25)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Should qualify this per https://github.com/EricCousineau-TRI/drake-ros/pull/6#discussion_r1125164067
</blockquote></details>

Done.
___
*[`drake_ros/CMakeLists.txt` line 28 at r7](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238#-NPtfSN24oXXdoiCN7DI:-NPtgTRM1XKrMKG9YS9f:bxtqc4k) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/d0239e29daf48d3189bb716f3e35b6737a402dfb/drake_ros/CMakeLists.txt#L28)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Should reference https://github.com/ros2/ros2_documentation/issues/3373
</blockquote></details>

Done. \cc @cottsay

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 31 files at r1, 11 of 31 files at r5, 5 of 11 files at r6, 10 of 22 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/238)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Pull request merged**
