### PR TITLE
Update README to reflect development status

### PR DESCRIPTION
**Pull request by IanTheEngineer**
While the `develop` branch is not stable, it would be useful for external
visitors to have us point to it in the `main` README.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/58)

### CODE REVIEW

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm: with small nit - thanks!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/58#-:-N-4DLXv1StHsFyNE5Of:b-o79346)* status: all files reviewed, 1 unresolved discussion (waiting on @IanTheEngineer)

___
*[README.md, line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/58#-N-4DFaq5uS-uv7fYR7w:-N-4DFaq5uS-uv7fYR7x:b-ikd8cb) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2827866f168f42be00d7440e45b6d60da7a5f350/README.md#L4)):*
> ```Markdown
> 
> The repository contains experimental code to interface ROS2 with Drake (and Bazel). Prototype work is happening on the [develop branch](https://github.com/RobotLocomotion/drake-ros/tree/develop), but please excercise caution if you are attempting to using this code. Both the functionality and API's on the `develop` branch are likely to change regularly.
> ```

nit Consider line-wrapping to 80-characeters.

**Review by EricCousineau-TRI — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/58)* status: all files reviewed, 3 unresolved discussions (waiting on @IanTheEngineer)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/58#-N-4DQv_4sMjbkihf_yl:-N-4DQv_4sMjbkihf_ym:bqcqymi) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2827866f168f42be00d7440e45b6d60da7a5f350/README.md#L3)):*
> ```Markdown
> # drake_ros
> 
> The repository contains experimental code to interface ROS2 with Drake (and Bazel). Prototype work is happening on the [develop branch](https://github.com/RobotLocomotion/drake-ros/tree/develop), but please excercise caution if you are attempting to using this code. Both the functionality and API's on the `develop` branch are likely to change regularly.
> ```

nit "to using" => "to use"
___
*[README.md, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/58#-N-4DT-e38yG1WA2Bo-n:-N-4DT-e38yG1WA2Bo-o:b1lj5yx) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2827866f168f42be00d7440e45b6d60da7a5f350/README.md#L3)):*
> ```Markdown
> # drake_ros
> 
> The repository contains experimental code to interface ROS2 with Drake (and Bazel). Prototype work is happening on the [develop branch](https://github.com/RobotLocomotion/drake-ros/tree/develop), but please excercise caution if you are attempting to using this code. Both the functionality and API's on the `develop` branch are likely to change regularly.
> ```

nit "API's" => "API"

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/58)* status: all files reviewed, 4 unresolved discussions (waiting on @IanTheEngineer)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/58#-N-4DMUq9amOHZmg-5qV:-N-4DMUq9amOHZmg-5qW:bl5i0wt) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2827866f168f42be00d7440e45b6d60da7a5f350/README.md#L3)):*
> ```Markdown
> # drake_ros
> 
> The repository contains experimental code to interface ROS2 with Drake (and Bazel). Prototype work is happening on the [develop branch](https://github.com/RobotLocomotion/drake-ros/tree/develop), but please excercise caution if you are attempting to using this code. Both the functionality and API's on the `develop` branch are likely to change regularly.
> ```

I'd recommend doing one sentence per line. It makes it a lot easier to review diffs, and the rendering will combine them into a paragraph anyways.

**Comment by EricCousineau-TRI** [comment]
*[README.md, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/58#-N-4DT-e38yG1WA2Bo-n:-N-4DW3vEcxQAGN5xScB:b-sfly1s) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2827866f168f42be00d7440e45b6d60da7a5f350/README.md#L3)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "API's" => "API"
</blockquote></details>

er, => "APIs"

**Review by IanTheEngineer — COMMENTED** [review]
I think I addressed all your comments. Feel free to look again.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/58#-:-N-4GMED4CnQ6XpGiCEr:b-62dsja)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sloretz)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/58#-N-4DMUq9amOHZmg-5qV:-N-4GRHG-D20cYM5NY_Y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2827866f168f42be00d7440e45b6d60da7a5f350/README.md#L3)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I'd recommend doing one sentence per line. It makes it a lot easier to review diffs, and the rendering will combine them into a paragraph anyways.
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/58)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @sloretz)

**Review by IanTheEngineer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/58)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @sloretz)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/58#-N-4DMUq9amOHZmg-5qV:-N-4KujY1iEPwzSllp71:b89wif0) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2827866f168f42be00d7440e45b6d60da7a5f350/README.md#L3)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@sloretz I'm not sure if you intended it this way, but without one of the magic keywords, you marked this as a blocking issue. Was that intended?

**Review by sloretz — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/58#-:-N-4MlsO-wLArw5_chir:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @IanTheEngineer)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/58#-N-4DMUq9amOHZmg-5qV:-N-4Mn_B9L8mvKWO0Pp2:b905y3y) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2827866f168f42be00d7440e45b6d60da7a5f350/README.md#L3)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

@sloretz I'm not sure if you intended it this way, but without one of the magic keywords, you marked this as a blocking issue. Was that intended?
</blockquote></details>

No, that wasn't intentional. I made the review a "comment" thinking that it would make it non-blocking. What do I need to do in reviewable to mark this as not blocking?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/58)* status: all files reviewed, 1 unresolved discussion (waiting on @sloretz)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/58#-N-4DMUq9amOHZmg-5qV:-N-4NOWa6dDY_KPoMvKP:b-1ksnx) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2827866f168f42be00d7440e45b6d60da7a5f350/README.md#L3)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

No, that wasn't intentional. I made the review a "comment" thinking that it would make it non-blocking. What do I need to do in reviewable to mark this as not blocking?
</blockquote></details>

OK See https://docs.reviewable.io/discussions.html#checking-and-changing-dispositions

**Review by sloretz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/58)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IanTheEngineer)

**Pull request merged**
