### PR TITLE
[setup] Add instructions for installing dev tools

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
\cc @adeeb10abbas I think this would help w/ `colcon` and `rosdep`?

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/264)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/264)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @adeeb10abbas)

___
*[`drake_ros_examples/README.md` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/264#-NQzWlcv0vpVPqB9lYUJ:-NQzr2v27-1MSUSxpT41:bc7k4if) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/bf0cec4cdc2aebdf18b90a50d5dd049a76a64fc2/drake_ros_examples/README.md#L26)):*
<details><summary><i>Previously, adeeb10abbas (Adeeb Abbas) wrote…</i></summary><blockquote>

Should it be `ros-humble-desktop-full`? 
https://repo.ros2.org/ubuntu/building/pool/main/r/ros-humble-desktop-full/
</blockquote></details>

Done. Nah, but good point on explicitly mentioning entry points.

**Review by cottsay — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/264#-:-NQzuKe65m6nwGvQy0xH:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @adeeb10abbas)

**Review by adityapande-1995 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/264)* status: all files reviewed, 1 unresolved discussion (waiting on @adeeb10abbas)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Dismissed @adeeb10abbas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/264)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Pull request merged**
