### PR TITLE
Merge develop in main

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Pre-merge:
- [x] Remove intermediate merges s.t. we only have one non-fast-forward commit

At merge:
- Do NOT squash merge.

Post-merge:
- [ ] Enable branch protection
- [ ] Retarget all current PRs to `main`
- [ ]  Delete `develop` branch

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/136)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@iantheengineer and +@sloretz for review, please.
This does not include the README update. That is a separate PR, to remove the noise.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/136#-:-NC6nt_R40aGvLS9mqYW:bbpadch)* status: 0 of 201 files reviewed, all discussions resolved (waiting on @IanTheEngineer and @sloretz)

**Review by IanTheEngineer — APPROVED** [review]
:LGTM: Looking through all of these files, there's certainly still cleanup to be done here, but I think operating out of the `main` branch makes more sense at this point in our development. It increases visibility, and makes our development process more obvious to the typical community observer. I would like to see #137 merge very soon after this merges, to ensure our main README is up to date for anyone finding this repo for the first time. 

> Reviewed 201 of 201 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/136#-:-NEbti6983_XcnpCgyfu:b-91w94)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

**Review by EricCousineau-TRI — COMMENTED** [review]
Thanks! Yes, #137 has a discussion item to merge shortly after this - onwards!

-@sloretz (on travel, I believe - enjoy!)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/136#-:-NEfRLkeCdRWkxLNixYk:b9hcsqq)* status: 173 of 204 files reviewed, all discussions resolved (waiting on @IanTheEngineer)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 173 of 201 files at r1, 31 of 31 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/136)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
kinda confused, but assuming that some status-reporting web service is dragging its feet:
> image

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/136)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/136#-NEfVEMKABobA9sjE7JH:-NEfVEMKABobA9sjE7JI:bmjo9i3) (no related file):*
Working: Enabling PR merging temporarily.

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/136)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/136#-NEfVEMKABobA9sjE7JH:-NEfVU0b1vx5TrTgVD8u:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Enabling PR merging temporarily.
</blockquote></details>

Done.

___

**Comment by EricCousineau-TRI** [comment]
added branch protection rules
image

**Pull request merged**
