### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by ahcorde**
CI is broken, trying to fix it

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/325)

### CODE REVIEW

**Comment by ahcorde** [comment]
I can see this error, any thoughts?
```bash
ERROR: /home/runner/.cache/bazel/_bazel_runner/d07b19e4bc14c7eead45599d9bb941ba/external/drake/tools/install/libdrake/BUILD.bazel:54:25: in cc_whole_archive_library rule @@drake//tools/install/libdrake:libdrake_components_whole_archive: 
Traceback (most recent call last):
	File "/home/runner/.cache/bazel/_bazel_runner/d07b19e4bc14c7eead45599d9bb941ba/external/drake/third_party/com_github_bazelbuild_rules_cc/whole_archive.bzl", line 36, column 38, in _cc_whole_archive_library_impl
		cc_toolchain = _find_cc_toolchain(ctx)
	File "/home/runner/.cache/bazel/_bazel_runner/d07b19e4bc14c7eead45[59](https://github.com/RobotLocomotion/drake-ros/actions/runs/7347700014/job/20004559821?pr=325#step:15:60)9d9bb941ba/external/drake/third_party/com_github_bazelbuild_rules_cc/whole_archive.bzl", line 23, column 13, in _find_cc_toolchain
		fail("In order to use find_cc_toolchain, your rule has to depend on C++ toolchain. See find_cc_toolchain.bzl docs for details.")  # noqa
Error in fail: In order to use find_cc_toolchain, your rule has to depend on C++ toolchain. See find_cc_toolchain.bzl docs for details.
```

**Comment by jwnimmer-tri** [comment]
> ```
> 2023-12-28T12:44:17.9668208Z 2023/12/28 12:44:17 Downloading https://releases.bazel.build/7.0.0/release/bazel-7.0.0-linux-x86_64...
> 2023-12-28T12:44:18.4654157Z Extracting Bazel installation...
> ```

If you're going to use Bazel 7, then you need https://github.com/RobotLocomotion/drake/pull/20658 which was released in [Drake v1.24.0](https://drake.mit.edu/release_notes/v1.24.0.html), underway at https://github.com/RobotLocomotion/drake-ros/pull/322.

**Review by adityapande-1995 — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/325)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ahcorde)

**Review by adityapande-1995 — APPROVED** [review]

**Comment by ahcorde** [comment]
Thank you @jwnimmer-tri I included the change in this PR and now CI is green!

**Review by adityapande-1995 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/325#-:-NmlsIlg-dg1OiHfb9Tm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ahcorde)

**Pull request merged**
