### PR TITLE
Consolidate drake_ros_core, drake_ros_tf2, and drake_ros_viz packages

### PR DESCRIPTION
**Pull request by sloretz**
Proposal for #201

To update existing code to reflect new structure, the following `sed` scripts should help:
```sh
find . -name "*.h" -o -name "*.cc" -o -name "*.cpp" | xargs sed -i 's:^#include \("\|<\)drake_ros_\(core\|tf2\|viz\):#include \1drake_ros/\2:'
find . -name "*.bazel" -o -name "BUILD" | xargs sed -i 's @drake_ros_\(core\|tf2\|viz\) @drake_ros '
find . -name "*.bazel" -o -name "BUILD" | xargs sed -i 's :drake_ros_\(core\|tf2\|viz\) :\1 '
```

This combines core, tf2, and viz into a single package called "drake_ros". I made this PR only change CMake and bazel files. No source files are changed other than moving or renaming them to match Drake/Anzu's placement.

`bazel build //... && bazel test //...` passes. Building with Colcon succeeds, but linter tests fails mostly due to moving files and expected include guard names, but also because drake_ros_viz seems to not have had python linting tests before.

`drake_ros_examples` is buildable as well.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/205)

### CODE REVIEW

**Review by sloretz — COMMENTED** [review]
+@ericcousineau-tri for review! What do you think of this layout?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/205#-:-NKyxpI8989PZqHR3KZz:b-84vatv)* status: 0 of 86 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Looks excellent to me! Would you be up for spiffing this up to land as a real PR?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/205#-:-NLNgnW49u0p0qstv5PL:b3dl3nb)* status: 0 of 86 files reviewed, all discussions resolved

**Review by sloretz — COMMENTED** [review]
Updated! Include directives changed, but C++ namespaces did not. I'd be happy to change C++ namespaces, but it may be easier to review that it's done in a follow up PR.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/205#-:-NLXHWKB5g38PZe--VVC:b-mh9vmw)* status: 0 of 89 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/205#-NLTE8H-5s656xx69ek4:-NLTE8H-5s656xx69ek5:bxevwfg) (no related file):*
Here's a command to update `#include` directives. For example, `#include <drake_ros_core/ros_interface_system.h>` would now be included as `#include <drake_ros/core/ros_interface_system.h>`. I had to change these to satisfy cpplint.

```
find . -name "*.h" -o -name "*.cc" -o -name "*.cpp" | xargs sed -i 's:^#include \("\|<\)drake_ros_\(core\|tf2\|viz\):#include \1drake_ros/\2:'
```

___

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/205)* status: 0 of 89 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/205#-NLXITWQ9fq16_OhkF1X:-NLXITWQ9fq16_OhkF1Y:by59fvz) (no related file):*
Ah, I need to update CI actions now that there's only one package.

___

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/205)* status: 0 of 90 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/205#-NLXITWQ9fq16_OhkF1X:-NLYPOm02NRcIseo_H8k:baa3tez) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Ah, I need to update CI actions now that there's only one package.
</blockquote></details>

CI scripts are updated, though #210 is needed for CI to pass

___

**Review by EricCousineau-TRI — COMMENTED** [review]
I'd like to see us land this soon (next few days).
Is that possible?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/205#-:-NOQPUyHBy5hnbpwLeJq:bxods14)* status: 0 of 90 files reviewed, 1 unresolved discussion

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
:lgtm:, will resolve one more item.

@sloretz Can I ask that you do a pass-through just to ensure this is all good for you?
If so, we should merge forward!

> Reviewed 37 of 86 files at r1, 37 of 42 files at r2, 5 of 6 files at r3, 10 of 10 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/205#-:-NORnIqg9-tjCneYz9VA:b-fdr95p)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`drake_ros/viz/CMakeLists.txt` line 94 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/205#-NORmwEI6XCaftbhiH7R:-NORmwEJ8Ynut2SYAxFa:bi9qcif) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/aeaafe589d9335e93ce44859d1b3f8b4734de4e9/drake_ros/viz/CMakeLists.txt#L94)):*
> ```CMake
> 
>   ament_add_pytest_test(test_python_bindings test/test_python_bindings.py)
> endif()
> ```

Working: Should have newline.

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/205)* status: all files reviewed, 2 unresolved discussions (waiting on @sloretz)

___
*[`drake_ros/tf2/CMakeLists.txt` line 102 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/205#-NORnt_Q55_I7IX6L4hT:-NORnt_Q55_I7IX6L4hU:bi9qcif) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/aeaafe589d9335e93ce44859d1b3f8b4734de4e9/drake_ros/tf2/CMakeLists.txt#L102)):*
> ```CMake
>     drake_ros_tf2
>   )
> endif()
> ```

Working: Should have newline.

**Comment by EricCousineau-TRI** [comment]
Newline-adding script:
```
find bazel_ros2_rules/ drake_* -type f | xargs sed -i -e '$a\'
```
per https://unix.stackexchange.com/a/31955/304032

**Review by EricCousineau-TRI — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/205)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

___
*[`drake_ros/tf2/CMakeLists.txt` line 102 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/205#-NORnt_Q55_I7IX6L4hT:-NORojoW2_Eg0llypJ_r:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/aeaafe589d9335e93ce44859d1b3f8b4734de4e9/drake_ros/tf2/CMakeLists.txt#L102)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Should have newline.
</blockquote></details>

Done.
___
*[`drake_ros/viz/CMakeLists.txt` line 94 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/205#-NORmwEI6XCaftbhiH7R:-NORokjJ5AvXXRP9oYQ0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/aeaafe589d9335e93ce44859d1b3f8b4734de4e9/drake_ros/viz/CMakeLists.txt#L94)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Should have newline.
</blockquote></details>

Done.

**Review by sloretz — COMMENTED** [review]
I think this is ready for another review. I made a couple changes

* I had to replace `ros-tooling/action-ros-ci` with colcon build and test directly in the archive jobs because they were installing the `ros-humble-` debian packages on top of the archive. That caused test failures where python tests could not import libraries for tf2_msgs because the debian packages replaced the setup scripts with ones that expected a merged workspace instead of an isolated workspace. I think we didn't see this before because we weren't doing any python testing of drake_ros_viz before this PR
* I had to manually install `libconsole-bridge-dev` because `bazel_ros2_rules` needed it installed to inspect the archive. I don't know why that's failing in this PR. There seems to be a chicken and egg problem that we can't solve the same way we did with `Drake`'s perquisites script.
   * We're using bazel to download the archive via a repository rule, but that same repository rule needs to inspect the archive to generate a `BUILD.bazel`, and it needs the archive's `buildtool_depend`encies installed to inspect the archive, but we can't query what the dependencies are until the archive is downloaded.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/205#-:-NP-PpJQ8ZIWiC7NZ-iM:b-2eb6pc)* status: 88 of 92 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/205#-NLTE8H-5s656xx69ek4:-NP-Pe_r2dtHNFLLau2v:b7voy4k) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per Slack, can you provide command-line invocations for also adjusting CMake and Bazel targets?
https://drakedevelopers.slack.com/archives/C2CP2E50A/p1676595313778179?thread_ts=1676595133.045519&cid=C2CP2E50A
</blockquote></details>

How about this one?

```
find . -name "*.bazel" -o -name "BUILD" | xargs sed -i 's @drake_ros_\(core\|tf2\|viz\) @drake_ros '
find . -name "*.bazel" -o -name "BUILD" | xargs sed -i 's :drake_ros_\(core\|tf2\|viz\) :\1 '
```

___

**Comment by EricCousineau-TRI** [comment]
> How about this one?

Sweet, thanks! Will edit overview to have these commands for ease of finding.

**Review by EricCousineau-TRI — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/205)* status: all files reviewed, 1 unresolved discussion (waiting on @sloretz)

___
*[`.github/workflows/bazelized_drake_ros.yml` line 39 at r7](https://reviewable.io/reviews/RobotLocomotion/drake-ros/205#-NP-aldTBBtMtTjTO60y:-NP-aldTBBtMtTjTO60z:b-eg41cl) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/889cc853a8eed7a41ecc31af9b90e6721f490a7f/.github/workflows/bazelized_drake_ros.yml#L39)):*
> ```YAML
>         working-directory: drake_ros
>       - name: Install ROS tarball's dependencies
>         # TODO(sloretz) can't use rosdep here because we need the archive downloaded,
> ```

BTW I think I understand the chicken-and-end problem, in that our `install_prereqs` couples both installation of Bazel and ROS tarball.

That being said, I think we could decouple it!

**Review by EricCousineau-TRI — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/205)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

**Comment by sloretz** [comment]
Better commands for updating bazel target rules (used in #207)

```
find . -name "*.bazel" -o -name "BUILD" | xargs sed -i 's @drake_ros_\(core\|tf2\|viz\) @drake_ros '
find . -name "*.bazel" -o -name "BUILD" | xargs sed -i 's :drake_ros_\(core\|tf2\|viz\) \1:\1 '
```

**Comment by EricCousineau-TRI** [comment]
It will effectively be part of Anzu PR 9950 which we should be able to land this week.

Do you need it sooner? If so, I can do the porting by tomorrow.

**Comment by jwnimmer-tri** [comment]
It's holding up #233 testing, which is holding up the Bazel 6.0 upgrade in Anzu.  Neither is necessarily urgent, but as always the less time we have with an unresolved breaking change in a dependency hanging over Anzu, the better.  It means that no other bug fixes here can flow until Anzu until the porting lands first.

**Comment by EricCousineau-TRI** [comment]
Aye, I'll take a quick stab at it then.

**Pull request merged**
