### PR TITLE
Fix environment variable name and Default ROS_LOCALHOST_ONLY to True

### PR DESCRIPTION
**Pull request by sloretz**
It looks like I got the environment variable name in #94 wrong. The environment vairable is [ROS_LOCALHOST_ONLY](https://github.com/ros2/rcl/blob/191b13bc2eb8578e40799eb6b50c74b885e7066e/rcl/src/rcl/localhost.c#L25). I confused it with variable names [ at the RMW layer](https://docs.ros2.org/foxy/api/rmw/localhost_8h.html#a9a2385caf8e01f02d7600b5feb02b8ef).

This PR fixes that bug, and after this morning's discussion it also makes the default value to True. I tested this locally using two machines and the examples in this repo.

By default I'm only able to see the `/oracle` node on the same machine.

```
bazel run //ros2_example_apps:oracle_cc
```

And I can override the environment variable to see the node on another machine with the same `ROS_DOMAIN_ID`

```
ROS_LOCALHOST_ONLY=0 bazel run //ros2_example_apps:oracle_cc
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/98)

### CODE REVIEW

**Review by IanTheEngineer — COMMENTED** [review]
> The environment vairable is ROS_LOCALHOST_ONLY. I confused it with variable names  at the RMW layer.
What is the difference between these two variables? I can't find the relevant doc on the "ROS" side.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/98#-:-N8PxVr8CZbInPLwp9ta:bcr1e3h)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @EricCousineau-TRI and @IanTheEngineer)

**Review by IanTheEngineer — COMMENTED** [review]
Bah. Newlines are hard: What is the difference between these variables? I can't find the relevant doc on the "ROS" side.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/98#-:-N8PxM8pEfW7vhVk40SQ:brko9md)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @EricCousineau-TRI and @IanTheEngineer)

**Review by sloretz — COMMENTED** [review]
`ROS_LOCALHOST_ONLY` is the name of the environment variable. `RMW_LOCALHOST_ONLY_*` are constants use in C at the RMW layer. `rcl` uses the environment variable value to initialize the middleware via an `rmw_init_options_t` with either `RMW_LOCALHOST_ONLY_ENABLED` or `RMW_LOCALHOST_ONLY_DISABLED`.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/98#-:-N8PzXdN8IZLVYb9XEGB:b-vmhpx7)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @EricCousineau-TRI and @IanTheEngineer)

**Review by IanTheEngineer — APPROVED** [review]
:lgtm: Thanks for the explanation. The changes look good to me. Thanks for catching this bug and supplying the fix.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/98#-:-N8Q-vmz26aSh6Yidg_K:b-bqbrb7)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @IanTheEngineer)

**Comment by EricCousineau-TRI** [comment]
is there an issue / PR already open to improve upstream documentation?

**Comment by IanTheEngineer** [comment]
> is there an issue / PR already open to improve upstream documentation?

There is an issue, but no PR as far as I've found: https://github.com/ros2/ros2_documentation/issues/2615

**Comment by EricCousineau-TRI** [comment]
sweet, thanks!

**Pull request merged**
