### PR TITLE
Fix drake-ros CI against ROS 2 Rolling

### LINKED ISSUE #41: CI is broken due to rolling + Ubuntu 22.04 shift
Currently, CI uses Docker images for rolling, and it's support (22.04) has shifted away from Drake's (20.04).

One possible solution is to use tarball approach to provision CI, even for non-Bazel workflows.

Drake Slack: https://drakedevelopers.slack.com/archives/C01B5B320QY/p1644958013772819

### PR DESCRIPTION
**Pull request by hidmic**
Closes #41 by installing ROS 2 from Rolling on Focal tarballs.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/42)

### CODE REVIEW

**Comment by hidmic** [comment]
@cottsay `ament_cmake_clang_format` seems to be missing from the Rolling on Focal archive?

**Comment by hidmic** [comment]
Also, it doesn't seem like I can prevent `action-ros-ci` from attempting to install dependencies from debs via `rosdep`. It'll fail silently, but it's not a great solution.

I'm starting to think that rolling out a `RobotLocomotion/drake-ros:focal` Docker image may be a better approach. CC @EricCousineau-TRI @sloretz @cottsay.

**Comment by hidmic** [comment]
@cottsay ahh, I see. To build and test `drake-ros` we'll need:

- `rclcpp`
- `rclpy`
- `geometry_msgs`
- `visualization_msgs`
- `test_msgs`
- `tf2_ros`
- `tf2_ros_py`
- `ament_cmake_clang_format`
- `ament_cmake_cpplint`
- `ament_cmake_gtest`
- `ament_cmake_pycodestyle`
- `rosidl_*` packages
- `rmw_*` packages

and their recursive dependencies.

**Review by aaronchongth — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/42)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hidmic)

**Comment by aaronchongth** [comment]
Thanks! LGTM

**Pull request merged**
