### PR TITLE
Add failing example of importing tf2_py

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Reproduces error in #177

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/178)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/178)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`ros2_example_bazel_installed/WORKSPACE` line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/178#-NEwf-U9Ck4IJiBdLi2B:-NEwf-U9Ck4IJiBdLi2C:b-l43lpu) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7a99349b25bd3a0d59c9c120df2dfbd6817eb0cb/ros2_example_bazel_installed/WORKSPACE#L47)):*
> ```Starlark
>     "rclcpp",
>     "rclpy",
>     "ros2cli",
> ```

nit Here's a suggestion to improve readability:



_Suggestion:_
```Starlark
    "ros2cli",
    "ros2cli_common_extensions",
    "tf2_py",
] + [
    # These are the possible RMW implementations.
    # Uncomment one and only one to change implementations.
    "rmw_cyclonedds_cpp",
    # "rmw_fastrtps_cpp",
]
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/178)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`ros2_example_bazel_installed/WORKSPACE` line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/178#-NEwf-U9Ck4IJiBdLi2B:-NEwgHKD7DGLU8WyLLZC:b-lwn3kn) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7a99349b25bd3a0d59c9c120df2dfbd6817eb0cb/ros2_example_bazel_installed/WORKSPACE#L47)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Here's a suggestion to improve readability:
</blockquote></details>

OK Thanks! Moved to #180

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/178)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

___
*[`ros2_example_bazel_installed/WORKSPACE` line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/178#-NEwf-U9Ck4IJiBdLi2B:-NEwzWNI4mJqMgVaCDaS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7a99349b25bd3a0d59c9c120df2dfbd6817eb0cb/ros2_example_bazel_installed/WORKSPACE#L47)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Thanks! Moved to #180 
</blockquote></details>

Done.

**Comment by EricCousineau-TRI** [comment]
Incorporated by #181

**Pull request closed without merging**
