### PR TITLE
Use cmake-file-api instead of cmake-server

### LINKED ISSUE #149: CMake Error: CMake server mode has been removed in favor of the file-api.
The [`bazel_ros2_rules` CMake scraping code uses the CMake server api](https://github.com/RobotLocomotion/drake-ros/blob/develop/bazel_ros2_rules/ros2/resources/cmake_tools/server_mode.py) - but it's been removed as of CMake 3.20. `bazel build //...` in `drake_ros_core` fails with a lot of the same message printed to the console:

```
CMake Error: CMake server mode has been removed in favor of the file-api.
```

@IanTheEngineer FYI this will need to be fixed to enable upgrading to Jammy.

### PR DESCRIPTION
**Pull request by sloretz**
Resolves #149 

@IanTheEngineer FYI This is needed for Ubuntu Jammy, and should work for Ubuntu Focal, but won't work on Ubuntu Bionic.

This uses the [cmake-file-api](https://cmake.org/cmake/help/latest/manual/cmake-file-api.7.html#object-kinds) instead of the [cmake-server](https://cmake.org/cmake/help/v3.19/manual/cmake-server.7.html#manual:cmake-server(7)) API to get information about packages in a ROS workspace. The server mode API was dropped in CMake 3.20. The file API exists since CMake 3.14.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/150)

### CODE REVIEW

**Review by IanTheEngineer — APPROVED** [review]
:LGTM: Thanks for implementing this CMake File API. The updates look good to me, with very small comments / nits.

> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/150#-:-NEbGx5fDu-sbci_Zhhn:b-56xh4d)* status: all files reviewed, 3 unresolved discussions (waiting on @sloretz)

___
*[`bazel_ros2_rules/ros2/resources/cmake_tools/file_api.py` line 8 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/150#-NEbF8aD5T-xDhXMw5Nd:-NEbF8aD5T-xDhXMw5Ne:b6lpsdx) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5fbb7198406be20a76e834ab6c947d71148f347e/bazel_ros2_rules/ros2/resources/cmake_tools/file_api.py#L8)):*
> ```Python
> 
> class Target:
> ```

Nit:  A single line summary doc-string would be helpful in these data classes.
___
*[`bazel_ros2_rules/ros2/resources/cmake_tools/file_api.py` line 103 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/150#-NEbCaJDAK2zKbzp8r1F:-NEbCaJDAK2zKbzp8r1G:b-s6rd68) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5fbb7198406be20a76e834ab6c947d71148f347e/bazel_ros2_rules/ros2/resources/cmake_tools/file_api.py#L103)):*
> ```Python
> 
> 
> def get_cmake_codemodel(project_path: Path, build_path: Path):
> ```

Nit: For consistency's sake, as you have it for the arguments already, consider adding the return type annotation here as well ```-> CodeModel```. In general, these annotations aren't required for Drake, but I believe consistency takes precedence here.



_Code quote:_
```Python
get_cmake_codemodel(project_path: Path, build_path: Path)
```
___
*[`bazel_ros2_rules/ros2/resources/ros2bzl/scraping/properties.py` line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/150#-NEbGUYwAewidakdgH8A:-NEbGUYxBWATTCyAeeph:b-4e1ih2) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5fbb7198406be20a76e834ab6c947d71148f347e/bazel_ros2_rules/ros2/resources/ros2bzl/scraping/properties.py#L18)):*
> ```Python
> 
> class CcProperties:
> ```

BTW: These classes are quite obvious, so a docstring isn't required here. If you felt so inclined, a top level documentation string would be more than sufficient.

**Review by IanTheEngineer — APPROVED** [review]
Ah, I thought you assigned me already: +@iantheengineer for review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/150#-:-NEbVVvdEcdmnZaTIbpQ:b-9kgunt)* status: all files reviewed, 3 unresolved discussions (waiting on @sloretz)

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/150)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

___
*[`bazel_ros2_rules/ros2/resources/cmake_tools/file_api.py` line 8 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/150#-NEbF8aD5T-xDhXMw5Nd:-NEbsKFQAHsyKc7V6G5a:bz08ihi) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5fbb7198406be20a76e834ab6c947d71148f347e/bazel_ros2_rules/ros2/resources/cmake_tools/file_api.py#L8)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Nit:  A single line summary doc-string would be helpful in these data classes.
</blockquote></details>

Added docstrings for Target and CodeModel in 8f0ea76
___
*[`bazel_ros2_rules/ros2/resources/cmake_tools/file_api.py` line 103 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/150#-NEbCaJDAK2zKbzp8r1F:-NEbsXoL0retElqXVbNs:bu4pivq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5fbb7198406be20a76e834ab6c947d71148f347e/bazel_ros2_rules/ros2/resources/cmake_tools/file_api.py#L103)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Nit: For consistency's sake, as you have it for the arguments already, consider adding the return type annotation here as well ```-> CodeModel```. In general, these annotations aren't required for Drake, but I believe consistency takes precedence here.
</blockquote></details>

Added return type annotation in 4416cfc
___
*[`bazel_ros2_rules/ros2/resources/ros2bzl/scraping/properties.py` line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/150#-NEbGUYwAewidakdgH8A:-NEbt4Nh3xqjcvNsu8Gd:b-ydghnx) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5fbb7198406be20a76e834ab6c947d71148f347e/bazel_ros2_rules/ros2/resources/ros2bzl/scraping/properties.py#L18)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

BTW: These classes are quite obvious, so a docstring isn't required here. If you felt so inclined, a top level documentation string would be more than sufficient.
</blockquote></details>

Added module level docstr in d0da748

**Review by IanTheEngineer — APPROVED** [review]
Looks great! Thanks for the updates.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/150#-:-NEbxzpCBygAWm8ZjJU-:b-faboa)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

**Comment by IanTheEngineer** [comment]
I believe it does close #149, but I'll re-run `bazel build //...` on Jammy today just to be sure prior to closing.

**Comment by EricCousineau-TRI** [comment]
For more major changes like this, we should probably start testing against Anzu before merging?

**Pull request merged**
