### PR TITLE
[drake_ros] Use modern drake::systems::Event API

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
See https://github.com/RobotLocomotion/drake/pull/19989.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/292)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for reviews, please.

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
:lgtm:, thanks!

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/292#-:-NbtgZwb1FHcrLTEwFxY:bpqxd5f)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/292#-Nbtgjij6MuMoshytuPY:-Nbtgjij6MuMoshytuPZ:blx08lv) (no related file):*
Working: Will wait for #294, just in case.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/292)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/292#-Nbtgjij6MuMoshytuPY:-NbuWvd38sjnMs_KRV4q:b-h1zqxz) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Will wait for #294, just in case.
</blockquote></details>

Between the two PRs, I agree it makes sense to merge one, then retest the other, to avoid merge races.

However, my vote would be to merge this one first, and then iterate on the other one.  This one is the smaller of the two changes.

___

**Review by EricCousineau-TRI — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/292)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/292#-Nbtgjij6MuMoshytuPY:-Nbuol3x96jlUwXmPY3S:bf3vzfj) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Between the two PRs, I agree it makes sense to merge one, then retest the other, to avoid merge races.

However, my vote would be to merge this one first, and then iterate on the other one.  This one is the smaller of the two changes.
</blockquote></details>

OK SGTM. I will chalk the current CI failure to a flake. \cc @IanTheEngineer @calderpg-tri

___

**Pull request merged**
